"""WARP-3672 — scripts/test-rag.sh must never weaken a box's authentication.

The script used to rewrite the repository's real `.env` in place to force
`AUTH_ENABLED=false`, with no check that it was running on a development
machine and nothing restoring the value on exit. Run on an appliance to debug
retrieval, it silently left the box with sign-in off. Now:

  * it refuses to run on a provisioned appliance (relocated `.env` symlink,
    the encrypted `/data` mount, or the device-identity provisioned marker),
    BEFORE the EXIT trap that runs `compose down -v`, and changes nothing;
  * it never edits `.env`; auth is turned off for the test stack only by
    docker/docker-compose.test.override.yml, and the script verifies the
    effective value in the running orchestrator.

Every case runs a COPY of the script inside a sandbox repo root (the script
derives REPO_ROOT from its own location) with fake `docker`, `curl`, `npx`
and `findmnt` on PATH, so nothing touches a real stack or the real `.env`.
Skipped automatically if `bash` isn't on PATH.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "scripts" / "test-rag.sh"
BASH = shutil.which("bash")

pytestmark = pytest.mark.skipif(BASH is None, reason="bash not available")

ENV_BODY = "# generated by setup.sh\nAUTH_ENABLED=true\nJWT_SECRET=not-a-real-secret\n"


def _fake(path: Path, body: str) -> None:
    path.write_text("#!/bin/bash\n" + body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR)


def _sandbox(tmp_path: Path, *, effective_auth: str = "false"):
    """A repo-shaped sandbox plus a PATH of fakes that log every docker call."""
    root = tmp_path / "repo"
    (root / "scripts").mkdir(parents=True)
    (root / "docker").mkdir()
    (root / "tests" / "node_modules").mkdir(parents=True)
    shutil.copy(SCRIPT, root / "scripts" / "test-rag.sh")
    for name in (
        "docker-compose.yml",
        "docker-compose.test.override.yml",
        "docker-compose.test.macos.yml",
    ):
        (root / "docker" / name).write_text("services: {}\n", encoding="utf-8")

    bindir = tmp_path / "bin"
    bindir.mkdir()
    log = tmp_path / "docker.log"
    _fake(
        bindir / "docker",
        f'echo "$@" >> "{log}"\n'
        f'case "$*" in *printenv*) echo "{effective_auth}";; esac\n'
        "exit 0\n",
    )
    _fake(bindir / "curl", "exit 0\n")
    _fake(bindir / "npx", "exit 0\n")
    # No marker by default: findmnt reports nothing for /data.
    _fake(bindir / "findmnt", "exit 1\n")
    return root, bindir, log


def _run(root: Path, bindir: Path, tmp_path: Path, extra_env: dict | None = None):
    env = dict(os.environ)
    env["PATH"] = f"{bindir}{os.pathsep}{env['PATH']}"
    # Point every appliance marker at an empty place unless a case overrides it.
    env["DROPLET_DI_STORAGE"] = str(tmp_path / "no-tpm")
    env.pop("TPM_STORAGE", None)
    env["DROPLET_DATA_MOUNT"] = str(tmp_path / "no-data")
    if extra_env:
        env.update(extra_env)
    return subprocess.run(
        [BASH, str(root / "scripts" / "test-rag.sh")],
        env=env, capture_output=True, text=True, timeout=60, cwd=root,
    )


def test_refuses_when_env_is_relocated_onto_the_encrypted_volume(tmp_path):
    root, bindir, log = _sandbox(tmp_path)
    real = tmp_path / "data-env"
    real.write_text(ENV_BODY, encoding="utf-8")
    (root / ".env").symlink_to(real)

    proc = _run(root, bindir, tmp_path)

    assert proc.returncode == 77, proc.stderr
    assert "Refusing to run on a provisioned Droplet appliance" in proc.stderr
    assert real.read_text(encoding="utf-8") == ENV_BODY
    assert not log.exists(), "docker was invoked on an appliance"


def test_refuses_when_the_encrypted_data_mount_is_present(tmp_path):
    root, bindir, log = _sandbox(tmp_path)
    (root / ".env").write_text(ENV_BODY, encoding="utf-8")
    _fake(bindir / "findmnt", 'echo "/dev/mapper/droplet-data-crypt"\n')

    proc = _run(root, bindir, tmp_path)

    assert proc.returncode == 77, proc.stderr
    assert "encrypted data mount" in proc.stderr
    assert (root / ".env").read_text(encoding="utf-8") == ENV_BODY
    assert not log.exists(), "docker was invoked on an appliance"


def test_refuses_when_the_device_identity_is_provisioned(tmp_path):
    root, bindir, log = _sandbox(tmp_path)
    (root / ".env").write_text(ENV_BODY, encoding="utf-8")
    storage = tmp_path / "tpm"
    storage.mkdir()
    (storage / "provisioned.json").write_text("{}", encoding="utf-8")

    proc = _run(root, bindir, tmp_path, {"DROPLET_DI_STORAGE": str(storage)})

    assert proc.returncode == 77, proc.stderr
    assert "provisioned.json" in proc.stderr
    assert (root / ".env").read_text(encoding="utf-8") == ENV_BODY
    assert not log.exists(), "docker was invoked on an appliance"


def test_refusal_comes_before_the_teardown_trap():
    """cleanup() runs `compose down -v`; on a real box that deletes the live
    stack's volumes, so the refusal must be installed above the trap."""
    body = SCRIPT.read_text(encoding="utf-8")
    assert body.index("Refusing to run on a provisioned") < body.index(
        "trap cleanup EXIT INT TERM"
    )


def test_a_dev_run_leaves_env_byte_identical(tmp_path):
    """The headline: a normal run (fake docker, no appliance marker) must not
    change AUTH_ENABLED or anything else in .env, and leaves no .env.bak."""
    root, bindir, log = _sandbox(tmp_path)
    (root / ".env").write_text(ENV_BODY, encoding="utf-8")

    proc = _run(root, bindir, tmp_path)

    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert (root / ".env").read_text(encoding="utf-8") == ENV_BODY
    assert not (root / ".env.bak").exists()
    assert "AUTH_ENABLED=false" not in (root / ".env").read_text(encoding="utf-8")
    # It did run the stack (via the compose override), so the guard is not
    # passing vacuously.
    assert "up -d" in log.read_text(encoding="utf-8")


def test_fails_fast_when_the_override_did_not_disable_auth(tmp_path):
    """If the compose override does not take effect the script stops with the
    real cause instead of letting every test 401 — and still leaves .env alone."""
    root, bindir, _log = _sandbox(tmp_path, effective_auth="true")
    (root / ".env").write_text(ENV_BODY, encoding="utf-8")

    proc = _run(root, bindir, tmp_path)

    assert proc.returncode == 1
    assert "expected 'false'" in proc.stderr
    assert (root / ".env").read_text(encoding="utf-8") == ENV_BODY


def test_script_no_longer_contains_an_env_rewrite_of_auth_enabled():
    body = SCRIPT.read_text(encoding="utf-8")
    assert "s/^AUTH_ENABLED=.*/AUTH_ENABLED=false/" not in body
    assert 'echo "AUTH_ENABLED=false" >>' not in body
