"""WARP-2621 — every scripts/lib/secrets.sh .env writer must write THROUGH the
symlink, not over it.

Once `relocate_secrets_to_data` has run, the repo `.env` is a SYMLINK onto the
encrypted `/data`. A writer that stages a temp file beside the LINK and renames
it onto the link does two harmful things at once: it replaces the link with a
plain file on the unencrypted boot disk (so DEVICE_SECRET_KEY and every other
secret leaves the LUKS boundary, and compose's `../.env` env_file breaks), and
the staged sibling is itself a full-secrets copy written to that same
unencrypted disk. That is the WARP-232 regression class — closed for
`_upsert_env_kv` / `generate_env`'s heredoc write, for
`scripts/host/droplet-set-nvr-media.sh` by WARP-2522 and for the box-name /
public-fqdn host scripts by WARP-2537, and still open in three secrets.sh
writers until this suite.

The three writers under test, each driven in isolation against a sandbox
REPO_ROOT (the same incantation `tests/fips-mode.test.sh` uses to exercise
`apply_fips_mode`):

  * `_rewrite_database_url_sslmode` — the FIPS flip's DATABASE_URL rewrite
  * `generate_env`'s torn-.env restore leg — resolved late, so this earlier
    writer ran against the unresolved path
  * `migrate_env` — the `.env.migrate.$$` stage + rename

Skipped automatically if a POSIX `bash` isn't on PATH.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import time
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
LIB = REPO_ROOT / "scripts" / "lib"
BASH = shutil.which("bash")

pytestmark = pytest.mark.skipif(BASH is None, reason="bash not available")

# Symlinks are POSIX-shaped; on a Windows checkout the fixture would error
# rather than exercise the writer.
posix_only = pytest.mark.skipif(os.name == "nt", reason="POSIX-only fixture")

_HEADER = "# generated by setup.sh\n"
_CORE = (
    "POSTGRES_PASSWORD=pg\n"
    "REDIS_PASSWORD=rd\n"
    "NEXTCLOUD_ADMIN_PASSWORD=nc\n"
    "DEVICE_SECRET=ds\n"
    "DEVICE_SECRET_KEY=dsk\n"
)


def _drive(sandbox: Path, snippet: str, extra_env: dict | None = None):
    """Source logging.sh + secrets.sh against a sandbox REPO_ROOT and run one
    writer. Mirrors tests/fips-mode.test.sh: the Docker/TLS helpers only
    generate_env's full path needs are stubbed out."""
    (sandbox / ".data").mkdir(exist_ok=True)
    script = "\n".join([
        "set -uo pipefail",
        f"export REPO_ROOT={shlex.quote(str(sandbox))}",
        'export LOG_FILE="$REPO_ROOT/.data/setup.log"',
        f". {shlex.quote(str(LIB / 'logging.sh'))}",
        "_write_mosquitto_conf() { return 0; }",
        "_generate_tls_cert()    { return 0; }",
        f". {shlex.quote(str(LIB / 'secrets.sh'))}",
        snippet,
    ])
    env = dict(os.environ)
    if extra_env:
        env.update(extra_env)
    return subprocess.run(
        [BASH, "-c", script], env=env, capture_output=True, text=True, timeout=60,
    )


def _link_env(sandbox: Path, content: str) -> tuple[Path, Path]:
    """Build the post-relocate_secrets_to_data shape: <sandbox>/.env is a
    symlink onto <sandbox>/data/.env — the same basename relocate_secrets_to_data
    uses in production (/data/droplet/env/.env), so the writers' `.env.<suffix>`
    sibling names are the real ones on both sides of the link."""
    real = sandbox / "data" / ".env"
    real.parent.mkdir(parents=True, exist_ok=True)
    real.write_text(content, encoding="utf-8")
    link = sandbox / ".env"
    link.symlink_to(real)
    return link, real


def _assert_link_intact(link: Path, real: Path) -> None:
    assert link.is_symlink(), "the .env symlink was replaced by a plain file"
    assert os.readlink(link) == str(real), "the .env symlink was repointed"


def _stray_siblings(sandbox: Path) -> list[str]:
    """Staging siblings left beside the LINK — each one a full-secrets copy on
    the unencrypted boot disk."""
    return sorted(
        p.name
        for p in sandbox.iterdir()
        if p.name.startswith(".env.")
        and any(m in p.name for m in (".tmp.", ".upsert.", ".migrate."))
    )


@posix_only
def test_rewrite_database_url_sslmode_writes_through_the_symlink(tmp_path):
    link, real = _link_env(
        tmp_path,
        _HEADER + _CORE + "DATABASE_URL=postgresql://u:p@db:5432/d?sslmode=require\n",
    )
    proc = _drive(
        tmp_path,
        '_rewrite_database_url_sslmode disable',
        {"ENV_FILE": str(link)},
    )
    assert proc.returncode == 0, proc.stderr
    _assert_link_intact(link, real)
    body = real.read_text(encoding="utf-8")
    assert "DATABASE_URL=postgresql://u:p@db:5432/d?sslmode=disable\n" in body
    assert "DEVICE_SECRET_KEY=dsk\n" in body
    assert _stray_siblings(tmp_path) == []


@posix_only
def test_generate_env_torn_restore_writes_through_the_symlink(tmp_path):
    # A torn .env (our header, but the write died before DEVICE_SECRET_KEY)
    # plus a complete backup beside the link: generate_env restores the backup
    # and returns before any secret generation.
    torn = _HEADER + "POSTGRES_PASSWORD=pg\nREDIS_PASSWORD=rd\n"
    link, real = _link_env(tmp_path, torn)
    backup = tmp_path / f".env.bak.{int(time.time())}"
    backup.write_text(_HEADER + _CORE + "JWT_SECRET=restored\n", encoding="utf-8")

    proc = _drive(tmp_path, "generate_env")
    assert proc.returncode == 0, proc.stderr
    _assert_link_intact(link, real)
    body = real.read_text(encoding="utf-8")
    assert "JWT_SECRET=restored\n" in body, "the backup was not restored through the link"
    assert "DEVICE_SECRET_KEY=dsk\n" in body
    assert _stray_siblings(tmp_path) == []


@posix_only
def test_migrate_env_writes_through_the_symlink(tmp_path):
    # A complete-but-old .env: migrate_env backfills the keys added since, and
    # the backfilled file must land at the link's real target.
    link, real = _link_env(tmp_path, _HEADER + _CORE)

    proc = _drive(tmp_path, "migrate_env")
    assert proc.returncode == 0, proc.stderr
    _assert_link_intact(link, real)
    body = real.read_text(encoding="utf-8")
    assert "DEVICE_SECRET_KEY=dsk\n" in body
    assert len(body) > len(_HEADER + _CORE), (
        "migrate_env appended nothing at the link's target — the backfill "
        "either did not run or landed on the wrong file"
    )
    assert _stray_siblings(tmp_path) == []


# --------------------------------------------------------------------------
# WARP-2624 — the .bak.* / .torn.* SNAPSHOTS must land beside the target too
# --------------------------------------------------------------------------
# A pre-migration backup and a torn-file quarantine are complete copies of
# every device secret. Writing them beside the LINK put them on the
# unencrypted boot disk even when the live .env itself was written correctly.


def _snapshots(d: Path) -> list[str]:
    """.env.bak.* / .env.torn.* in one directory."""
    return sorted(
        p.name
        for p in d.iterdir()
        if p.name.startswith(".env.") and (".bak." in p.name or ".torn." in p.name)
    )


@posix_only
def test_generate_env_torn_quarantine_lands_beside_the_target(tmp_path):
    """generate_env's torn-file quarantine (.env.torn.<epoch>) is a full copy of
    the torn secrets — it must be written beside the link's real target, and the
    pre-WARP-2624 backup beside the LINK must still be found and restored from
    (an upgraded box has its only backup there)."""
    torn = _HEADER + "POSTGRES_PASSWORD=pg\nREDIS_PASSWORD=rd\n"
    link, real = _link_env(tmp_path, torn)
    legacy_backup = tmp_path / f".env.bak.{int(time.time())}"
    legacy_backup.write_text(_HEADER + _CORE + "JWT_SECRET=restored\n", encoding="utf-8")

    proc = _drive(tmp_path, "generate_env")
    assert proc.returncode == 0, proc.stderr
    _assert_link_intact(link, real)
    assert "JWT_SECRET=restored\n" in real.read_text(encoding="utf-8")

    # The quarantine copy landed beside the TARGET, never beside the link.
    assert any(n.startswith(".env.torn.") for n in _snapshots(real.parent)), (
        "no torn quarantine beside the resolved target"
    )
    assert [n for n in _snapshots(tmp_path) if n.startswith(".env.torn.")] == [], (
        "a torn quarantine (full secrets copy) was left on the unencrypted disk"
    )


@posix_only
def test_generate_env_regen_backup_lands_beside_the_target(tmp_path):
    """The --regenerate-env pre-rotation backup is the documented recovery path
    AND a full secrets copy — beside the target, never beside the link."""
    link, real = _link_env(tmp_path, _HEADER + _CORE)
    proc = _drive(tmp_path, "REGENERATE_ENV=true generate_env")
    assert proc.returncode == 0, proc.stderr
    # The regenerated .env landed at the target, through the link (WARP-232).
    assert "generated by setup.sh" in real.read_text(encoding="utf-8")
    _assert_link_intact(link, real)
    assert any(n.startswith(".env.bak.") for n in _snapshots(real.parent)), (
        "no regeneration backup beside the resolved target"
    )
    assert [n for n in _snapshots(tmp_path) if n.startswith(".env.bak.")] == [], (
        "a .env.bak.* (full secrets copy) was left on the unencrypted disk"
    )


@posix_only
def test_migrate_env_backup_lands_beside_the_target(tmp_path):
    """migrate_env's pre-migration backup is a full secrets copy — beside the
    target, never beside the link."""
    link, real = _link_env(tmp_path, _HEADER + _CORE)

    proc = _drive(tmp_path, "migrate_env")
    assert proc.returncode == 0, proc.stderr
    _assert_link_intact(link, real)
    assert any(n.startswith(".env.bak.") for n in _snapshots(real.parent)), (
        "migrate_env wrote no backup beside the resolved target"
    )
    assert _snapshots(tmp_path) == [], (
        "a .env.bak.* (full secrets copy) was left on the unencrypted disk"
    )
