package com.droplet.mobile

/**
 * Parsed `droplet://pair?server=<url>&code=<XXXXXX>` URI.
 *
 * Generated by the orchestrator's `POST /api/devices/pair` route and rendered
 * as a QR code in the dashboard. The native app scans (or receives it via
 * deep link), parses, and exchanges the code through `/api/devices/pair/claim`.
 */
data class DropletPairUri(
    val server: String,
    val code: String,
) {
    companion object {
        private const val SCHEME = "droplet://"
        private const val HOST_AND_PATH = "pair"

        /** Returns `null` if the string is not a well-formed Droplet pairing URI. */
        fun parseOrNull(raw: String): DropletPairUri? {
            if (!raw.startsWith(SCHEME)) return null
            val afterScheme = raw.removePrefix(SCHEME)
            val (path, query) = when (val q = afterScheme.indexOf('?')) {
                -1 -> return null
                else -> afterScheme.substring(0, q) to afterScheme.substring(q + 1)
            }
            if (path.trimEnd('/') != HOST_AND_PATH) return null

            var server: String? = null
            var code: String? = null
            for (kv in query.split('&')) {
                val eq = kv.indexOf('=')
                if (eq <= 0) continue
                val key = kv.substring(0, eq)
                val value = urlDecode(kv.substring(eq + 1))
                when (key) {
                    "server" -> server = value
                    "code" -> code = value
                }
            }
            val s = server?.takeIf { it.isNotBlank() } ?: return null
            val c = code?.takeIf { it.isNotBlank() } ?: return null
            // Codes are 6 chars from a 32-char alphabet (no 0/O/1/I); the server
            // enforces this on /pair/claim, but rejecting early gives a better
            // error than a round-trip 400.
            if (c.length != 6) return null
            // Server URL must be absolute http(s).
            if (!s.startsWith("http://") && !s.startsWith("https://")) return null
            return DropletPairUri(server = s.trimEnd('/'), code = c)
        }
    }
}

private fun urlDecode(value: String): String {
    val bytes = ArrayList<Byte>(value.length)
    var i = 0
    while (i < value.length) {
        when (val ch = value[i]) {
            '+' -> {
                bytes.add(' '.code.toByte())
                i++
            }
            '%' -> {
                if (i + 2 >= value.length) {
                    bytes.add(ch.code.toByte())
                    i++
                } else {
                    val hex = value.substring(i + 1, i + 3)
                    val byte = hex.toIntOrNull(16)
                    if (byte == null) {
                        bytes.add(ch.code.toByte())
                        i++
                    } else {
                        bytes.add(byte.toByte())
                        i += 3
                    }
                }
            }
            else -> {
                bytes.add(ch.code.toByte())
                i++
            }
        }
    }
    return bytes.toByteArray().decodeToString()
}
