"""WARP-233 — Python twin of the orchestrator column-crypto module.

Locks the dcv1 wire format (iv(12) || ct || tag(16), tag LAST) in lockstep with
apps/orchestrator/src/services/column-crypto.service.ts via a golden vector
generated by the real TS module (dek = 32x0x01, iv = 12x0x02, plaintext
"interop").
"""

import base64

import pytest

from column_crypto import (
    ENC_PREFIX, derive_doc_kek, generate_dek, wrap_dek, unwrap_dek,
    encrypt_text, decrypt_text, is_encrypted,
)

TEST_KEY_B64 = base64.b64encode(bytes([7] * 32)).decode()


def test_round_trip_and_prefix():
    dek = generate_dek()
    blob = encrypt_text(dek, "patient has type-2 diabetes")
    assert blob.startswith(ENC_PREFIX)
    assert "diabetes" not in blob
    assert decrypt_text(dek, blob) == "patient has type-2 diabetes"


def test_wrap_binds_key_id():
    kek = derive_doc_kek(TEST_KEY_B64)
    dek = generate_dek()
    wrapped = wrap_dek(kek, dek, "brain:abc123")
    assert unwrap_dek(kek, wrapped, "brain:abc123") == dek
    with pytest.raises(Exception):
        unwrap_dek(kek, wrapped, "brain:OTHER")


def test_wire_format_layout():
    # iv(12) + ct + tag(16), tag LAST — must match the TS module byte-for-byte.
    dek = bytes([1] * 32)
    blob = encrypt_text(dek, "interop")
    raw = base64.b64decode(blob[len(ENC_PREFIX):])
    assert len(raw) == 12 + len(b"interop") + 16


def test_decrypts_ts_produced_blob():
    # Golden vector produced by the TS module (column-crypto.service.ts seal())
    # with dek = 32x0x01, iv = 12x0x02. Stable because the iv is pinned. This
    # locks cross-language compatibility forever.
    dek = bytes([1] * 32)
    golden = "dcv1:AgICAgICAgICAgICbri9LDg4saWIdAwRlGealM6wjc5fdiE="
    assert decrypt_text(dek, golden) == "interop"
