/**
 * WARP-1277 — globals.css must stay in lockstep with the design-and-style
 * token canon.
 *
 * `src/lib/design-tokens.lock.json` is generated by
 * DropletByWarpLab/design-and-style (`dist/json/web-lock.json`) and vendored
 * here so CI needs no cross-repo access. This guard extends the DASH-09
 * pattern (brand.theme-color.test.ts) from one anchor value to the whole
 * custom-property surface: every token in `:root`, `.dark`, and the
 * `[data-density]` blocks must match the canon — in BOTH directions, so a new
 * token has to land in design-and-style first (`npm run tokens:sync` refreshes
 * the lock).
 *
 * The scanner is depth-aware and string-safe (ported from the canon repo's
 * scripts/check-drift.mjs after adversarial review): contract blocks may live
 * at top level or under @layer, and a locked property declared ANYWHERE else
 * (@media, a compound like `:root.dark`, any other selector) fails as a
 * cascade override — those win in the browser while the contract blocks still
 * look clean.
 *
 * Path resolution uses `__dirname`, the one anchoring idiom this package uses
 * (WARP-2654) — see `src/__tests__/helpers/test-paths.ts` for why it is
 * spelled this way here. It is NOT that `import.meta.url` is unsafe on
 * Windows: `fileURLToPath` converts it correctly, and only
 * `new URL(...).pathname` yields the `/C:/...` that `path.resolve` doubles.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import lock from "@/lib/design-tokens.lock.json";

const SRC_ROOT = resolve(__dirname, "..");
const rawCss = readFileSync(resolve(SRC_ROOT, "app", "globals.css"), "utf8");

interface Decl {
  prop: string;
  value: string;
  stack: string[];
}

const S_SEMI = String.fromCharCode(1);
const S_OPEN = String.fromCharCode(2);
const S_CLOSE = String.fromCharCode(3);
const unmask = (s: string): string =>
  s.replaceAll(S_SEMI, ";").replaceAll(S_OPEN, "{").replaceAll(S_CLOSE, "}");

/** Every custom-property declaration in the sheet, with its block ancestry. */
function scanCss(source: string): Decl[] {
  // Strip comments, then mask structural chars inside string literals so the
  // block scanner can't be derailed by e.g. content: "}".
  const css = source.replace(/\/\*[\s\S]*?\*\//g, "");
  let masked = "";
  let quote: string | null = null;
  for (let i = 0; i < css.length; i++) {
    const ch = css[i];
    if (quote) {
      if (ch === "\\") {
        masked += ch + (css[i + 1] ?? "");
        i++;
        continue;
      }
      if (ch === quote) quote = null;
      masked += ch === ";" ? S_SEMI : ch === "{" ? S_OPEN : ch === "}" ? S_CLOSE : ch;
      continue;
    }
    if (ch === '"' || ch === "'") quote = ch;
    masked += ch;
  }

  const decls: Decl[] = [];
  const stack: string[] = [];
  let buf = "";

  const flushDecls = (text: string): void => {
    for (const seg of text.split(";")) {
      const m = /^\s*(--[\w-]+)\s*:\s*([\s\S]+?)\s*$/.exec(seg);
      if (m) {
        decls.push({
          prop: m[1],
          value: unmask(m[2]).trim().replace(/\s+/g, " "),
          stack: [...stack],
        });
      }
    }
  };

  for (let i = 0; i < masked.length; i++) {
    const ch = masked[i];
    if (ch === "{") {
      const parts = buf.split(";");
      const selector = (parts.pop() ?? "").trim();
      flushDecls(parts.join(";")); // declarations preceding a nested block
      stack.push(selector);
      buf = "";
    } else if (ch === "}") {
      flushDecls(buf);
      stack.pop();
      buf = "";
    } else {
      buf += ch;
    }
  }
  flushDecls(buf);
  return decls;
}

const matchesSelector = (selectorList: string, target: string): boolean =>
  selectorList.split(",").some((s) => s.trim() === target);

/** Contract scope: the target selector, wrapped by nothing or only @layer. */
const isContractStack = (stack: string[], target: string): boolean =>
  stack.length >= 1 &&
  matchesSelector(stack[stack.length - 1], target) &&
  stack.slice(0, -1).every((s) => s.startsWith("@layer"));

const scopes: ReadonlyArray<{ name: string; selector: string; expected: Record<string, string> }> = [
  { name: ":root", selector: ":root", expected: lock.root },
  { name: ".dark", selector: ".dark", expected: lock.dark },
  { name: '[data-density="dense"]', selector: '[data-density="dense"]', expected: lock.density.dense },
  { name: '[data-density="roomy"]', selector: '[data-density="roomy"]', expected: lock.density.roomy },
];

const allDecls = scanCss(rawCss);
const lockedProps = new Set(scopes.flatMap(({ expected }) => Object.keys(expected)));

describe("WARP-1277 design-token drift gate (globals.css ↔ design-and-style canon)", () => {
  for (const { name, selector, expected } of scopes) {
    it(`${name} custom properties match the canon exactly (both directions)`, () => {
      const actual: Record<string, string> = {};
      for (const d of allDecls) {
        if (isContractStack(d.stack, selector)) actual[d.prop] = d.value; // last wins, like the cascade
      }
      // toEqual gives a readable per-property diff on failure. A missing,
      // drifted, OR extra property fails — extra means the token needs to
      // land in DropletByWarpLab/design-and-style tokens/ first, then
      // `npm run tokens:sync` here.
      expect(actual).toEqual(expected);
    });
  }

  it("no locked property is re-declared outside the contract scopes (cascade override)", () => {
    const overrides = allDecls
      .filter((d) => lockedProps.has(d.prop))
      .filter((d) => !scopes.some(({ selector }) => isContractStack(d.stack, selector)))
      .map((d) => `${d.prop} at [${d.stack.join(" > ") || "(top level)"}] = ${d.value}`);
    expect(overrides).toEqual([]);
  });

  it("the lock itself is non-trivial (sanity: refuses an empty vendored file)", () => {
    expect(Object.keys(lock.root).length).toBeGreaterThan(30);
    expect(Object.keys(lock.dark).length).toBeGreaterThan(25);
    expect(lock.root["--color-accent"]).toBe("#6366f1");
  });
});
