/**
 * WARP-1277 — globals.css must stay in lockstep with the design-and-style
 * token canon.
 *
 * `src/lib/design-tokens.lock.json` is generated by
 * DropletByWarpLab/design-and-style (`dist/json/web-lock.json`) and vendored
 * here so CI needs no cross-repo access. This guard extends the DASH-09
 * pattern (brand.theme-color.test.ts) from one anchor value to the whole
 * custom-property surface: every token in `:root`, `.dark`, and the
 * `[data-density]` blocks must match the canon — in BOTH directions, so a new
 * token has to land in design-and-style first (`npm run tokens:sync` refreshes
 * the lock).
 *
 * Path resolution uses CommonJS `__dirname` (NOT `import.meta.url`), which is
 * the Windows-safe pattern other source-reading guards in this suite use.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import lock from "@/lib/design-tokens.lock.json";

const SRC_ROOT = resolve(__dirname, "..");

const css = readFileSync(resolve(SRC_ROOT, "app", "globals.css"), "utf8")
  // Strip comments so commented-out declarations never count.
  .replace(/\/\*[\s\S]*?\*\//g, "");

/**
 * Collect custom properties from every top-level block whose selector list
 * contains `selector` as a standalone selector. Multiple blocks merge (last
 * declaration wins), matching the cascade.
 */
function collectVars(selector: string): Record<string, string> {
  const vars: Record<string, string> = {};
  let idx = 0;
  while (idx < css.length) {
    const open = css.indexOf("{", idx);
    if (open === -1) break;
    const prevClose = css.lastIndexOf("}", open);
    // Selector text = since the previous `}` (or start), minus any preceding
    // `;`-terminated statements (@tailwind, @import, declarations).
    const selText = (css.slice(prevClose + 1, open).split(";").pop() ?? "").trim();
    const close = css.indexOf("}", open);
    if (close === -1) break;
    if (selText.split(",").some((s) => s.trim() === selector)) {
      const body = css.slice(open + 1, close);
      for (const m of body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
        vars[m[1]] = m[2].trim().replace(/\s+/g, " ");
      }
    }
    idx = close + 1;
  }
  return vars;
}

const scopes: ReadonlyArray<{ name: string; selector: string; expected: Record<string, string> }> = [
  { name: ":root", selector: ":root", expected: lock.root },
  { name: ".dark", selector: ".dark", expected: lock.dark },
  { name: '[data-density="dense"]', selector: '[data-density="dense"]', expected: lock.density.dense },
  { name: '[data-density="roomy"]', selector: '[data-density="roomy"]', expected: lock.density.roomy },
];

describe("WARP-1277 design-token drift gate (globals.css ↔ design-and-style canon)", () => {
  for (const { name, selector, expected } of scopes) {
    it(`${name} custom properties match the canon exactly (both directions)`, () => {
      const actual = collectVars(selector);
      // toEqual gives a readable per-property diff on failure. A missing,
      // drifted, OR extra property fails — extra means the token needs to
      // land in DropletByWarpLab/design-and-style tokens/ first, then
      // `npm run tokens:sync` here.
      expect(actual).toEqual(expected);
    });
  }

  it("the lock itself is non-trivial (sanity: refuses an empty vendored file)", () => {
    expect(Object.keys(lock.root).length).toBeGreaterThan(30);
    expect(Object.keys(lock.dark).length).toBeGreaterThan(25);
    expect(lock.root["--color-accent"]).toBe("#6366f1");
  });
});
