# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import device_identity_pb2 as device__identity__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceIdentityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sign = channel.unary_unary(
                '/droplet.device_identity.DeviceIdentityService/Sign',
                request_serializer=device__identity__pb2.SignRequest.SerializeToString,
                response_deserializer=device__identity__pb2.SignResponse.FromString,
                _registered_method=True)
        self.GetCert = channel.unary_unary(
                '/droplet.device_identity.DeviceIdentityService/GetCert',
                request_serializer=device__identity__pb2.GetCertRequest.SerializeToString,
                response_deserializer=device__identity__pb2.GetCertResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/droplet.device_identity.DeviceIdentityService/GetStatus',
                request_serializer=device__identity__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=device__identity__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.Reseal = channel.unary_unary(
                '/droplet.device_identity.DeviceIdentityService/Reseal',
                request_serializer=device__identity__pb2.ResealRequest.SerializeToString,
                response_deserializer=device__identity__pb2.ResealResponse.FromString,
                _registered_method=True)


class DeviceIdentityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sign(self, request, context):
        """Sign a payload with the device's non-extractable identity key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCert(self, request, context):
        """Return the device's self-signed X.509 cert (PEM-encoded).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Report on provisioning state + seal validity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reseal(self, request, context):
        """Re-bind the sealed identity blob to the current PCR snapshot.
        Requires a fresh operator-auth nonce issued by the orchestrator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceIdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=device__identity__pb2.SignRequest.FromString,
                    response_serializer=device__identity__pb2.SignResponse.SerializeToString,
            ),
            'GetCert': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCert,
                    request_deserializer=device__identity__pb2.GetCertRequest.FromString,
                    response_serializer=device__identity__pb2.GetCertResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=device__identity__pb2.GetStatusRequest.FromString,
                    response_serializer=device__identity__pb2.GetStatusResponse.SerializeToString,
            ),
            'Reseal': grpc.unary_unary_rpc_method_handler(
                    servicer.Reseal,
                    request_deserializer=device__identity__pb2.ResealRequest.FromString,
                    response_serializer=device__identity__pb2.ResealResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'droplet.device_identity.DeviceIdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('droplet.device_identity.DeviceIdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceIdentityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droplet.device_identity.DeviceIdentityService/Sign',
            device__identity__pb2.SignRequest.SerializeToString,
            device__identity__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droplet.device_identity.DeviceIdentityService/GetCert',
            device__identity__pb2.GetCertRequest.SerializeToString,
            device__identity__pb2.GetCertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droplet.device_identity.DeviceIdentityService/GetStatus',
            device__identity__pb2.GetStatusRequest.SerializeToString,
            device__identity__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reseal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/droplet.device_identity.DeviceIdentityService/Reseal',
            device__identity__pb2.ResealRequest.SerializeToString,
            device__identity__pb2.ResealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
