// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v3.19.1
// source: device_identity.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "droplet.device_identity";

/**
 * WARP-230 — Device identity sidecar gRPC interface.
 *
 * Backed by TPM 2.0 in production (real backend) and a pure-Python in-memory
 * mock in dev/CI. The same interface is satisfied by both.
 */

export interface SignRequest {
  /**
   * Bytes to sign. Caller hashes if needed; sidecar feeds directly into
   * ECDSA(SHA-256) signer.
   */
  payload: Uint8Array;
}

export interface SignResponse {
  /** DER-encoded ECDSA signature */
  signature: Uint8Array;
  /** "ECDSA-P256-SHA256" */
  algorithm: string;
}

export interface GetCertRequest {
}

export interface GetCertResponse {
  /** PEM-encoded X.509 cert (self-signed v1) */
  certPem: string;
}

export interface GetStatusRequest {
}

export interface GetStatusResponse {
  provisioned: boolean;
  /** "real" | "mock" */
  backend: string;
  certSubject: string;
  /** "sha256:<hex>" */
  certFingerprint: string;
  /** ISO 8601 */
  certExpiresAt: string;
  sealingPcrs: number[];
  sealValid: boolean;
  /** ISO 8601 or empty */
  lastResealAt: string;
  /** PCR index → hex digest */
  currentPcrSnapshot: { [key: number]: string };
}

export interface GetStatusResponse_CurrentPcrSnapshotEntry {
  key: number;
  value: string;
}

export interface ResealRequest {
  /**
   * Operator-auth nonce issued by the orchestrator after MFA re-auth.
   * Single-use, validated against a short-lived (60s) table inside the
   * sidecar.
   */
  operatorAuthNonce: string;
}

export interface ResealResponse {
  resealed: boolean;
  /** ISO 8601 */
  sealedAt: string;
  newPcrSnapshotIndices: number[];
}

function createBaseSignRequest(): SignRequest {
  return { payload: new Uint8Array(0) };
}

export const SignRequest: MessageFns<SignRequest> = {
  encode(message: SignRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignRequest {
    return { payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0) };
  },

  toJSON(message: SignRequest): unknown {
    const obj: any = {};
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create(base?: DeepPartial<SignRequest>): SignRequest {
    return SignRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignRequest>): SignRequest {
    const message = createBaseSignRequest();
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSignResponse(): SignResponse {
  return { signature: new Uint8Array(0), algorithm: "" };
}

export const SignResponse: MessageFns<SignResponse> = {
  encode(message: SignResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signature.length !== 0) {
      writer.uint32(10).bytes(message.signature);
    }
    if (message.algorithm !== "") {
      writer.uint32(18).string(message.algorithm);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signature = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.algorithm = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignResponse {
    return {
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
      algorithm: isSet(object.algorithm) ? globalThis.String(object.algorithm) : "",
    };
  },

  toJSON(message: SignResponse): unknown {
    const obj: any = {};
    if (message.signature.length !== 0) {
      obj.signature = base64FromBytes(message.signature);
    }
    if (message.algorithm !== "") {
      obj.algorithm = message.algorithm;
    }
    return obj;
  },

  create(base?: DeepPartial<SignResponse>): SignResponse {
    return SignResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SignResponse>): SignResponse {
    const message = createBaseSignResponse();
    message.signature = object.signature ?? new Uint8Array(0);
    message.algorithm = object.algorithm ?? "";
    return message;
  },
};

function createBaseGetCertRequest(): GetCertRequest {
  return {};
}

export const GetCertRequest: MessageFns<GetCertRequest> = {
  encode(_: GetCertRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCertRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCertRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetCertRequest {
    return {};
  },

  toJSON(_: GetCertRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<GetCertRequest>): GetCertRequest {
    return GetCertRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetCertRequest>): GetCertRequest {
    const message = createBaseGetCertRequest();
    return message;
  },
};

function createBaseGetCertResponse(): GetCertResponse {
  return { certPem: "" };
}

export const GetCertResponse: MessageFns<GetCertResponse> = {
  encode(message: GetCertResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certPem !== "") {
      writer.uint32(10).string(message.certPem);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCertResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCertResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certPem = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCertResponse {
    return {
      certPem: isSet(object.certPem)
        ? globalThis.String(object.certPem)
        : isSet(object.cert_pem)
        ? globalThis.String(object.cert_pem)
        : "",
    };
  },

  toJSON(message: GetCertResponse): unknown {
    const obj: any = {};
    if (message.certPem !== "") {
      obj.certPem = message.certPem;
    }
    return obj;
  },

  create(base?: DeepPartial<GetCertResponse>): GetCertResponse {
    return GetCertResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetCertResponse>): GetCertResponse {
    const message = createBaseGetCertResponse();
    message.certPem = object.certPem ?? "";
    return message;
  },
};

function createBaseGetStatusRequest(): GetStatusRequest {
  return {};
}

export const GetStatusRequest: MessageFns<GetStatusRequest> = {
  encode(_: GetStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetStatusRequest {
    return {};
  },

  toJSON(_: GetStatusRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<GetStatusRequest>): GetStatusRequest {
    return GetStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetStatusRequest>): GetStatusRequest {
    const message = createBaseGetStatusRequest();
    return message;
  },
};

function createBaseGetStatusResponse(): GetStatusResponse {
  return {
    provisioned: false,
    backend: "",
    certSubject: "",
    certFingerprint: "",
    certExpiresAt: "",
    sealingPcrs: [],
    sealValid: false,
    lastResealAt: "",
    currentPcrSnapshot: {},
  };
}

export const GetStatusResponse: MessageFns<GetStatusResponse> = {
  encode(message: GetStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.provisioned !== false) {
      writer.uint32(8).bool(message.provisioned);
    }
    if (message.backend !== "") {
      writer.uint32(18).string(message.backend);
    }
    if (message.certSubject !== "") {
      writer.uint32(26).string(message.certSubject);
    }
    if (message.certFingerprint !== "") {
      writer.uint32(34).string(message.certFingerprint);
    }
    if (message.certExpiresAt !== "") {
      writer.uint32(42).string(message.certExpiresAt);
    }
    writer.uint32(50).fork();
    for (const v of message.sealingPcrs) {
      writer.int32(v);
    }
    writer.join();
    if (message.sealValid !== false) {
      writer.uint32(56).bool(message.sealValid);
    }
    if (message.lastResealAt !== "") {
      writer.uint32(66).string(message.lastResealAt);
    }
    globalThis.Object.entries(message.currentPcrSnapshot).forEach(([key, value]: [string, string]) => {
      GetStatusResponse_CurrentPcrSnapshotEntry.encode({ key: key as any, value }, writer.uint32(74).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.provisioned = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.backend = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.certSubject = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.certFingerprint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.certExpiresAt = reader.string();
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.sealingPcrs.push(reader.int32());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.sealingPcrs.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.sealValid = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.lastResealAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const entry9 = GetStatusResponse_CurrentPcrSnapshotEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.currentPcrSnapshot[entry9.key] = entry9.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStatusResponse {
    return {
      provisioned: isSet(object.provisioned) ? globalThis.Boolean(object.provisioned) : false,
      backend: isSet(object.backend) ? globalThis.String(object.backend) : "",
      certSubject: isSet(object.certSubject)
        ? globalThis.String(object.certSubject)
        : isSet(object.cert_subject)
        ? globalThis.String(object.cert_subject)
        : "",
      certFingerprint: isSet(object.certFingerprint)
        ? globalThis.String(object.certFingerprint)
        : isSet(object.cert_fingerprint)
        ? globalThis.String(object.cert_fingerprint)
        : "",
      certExpiresAt: isSet(object.certExpiresAt)
        ? globalThis.String(object.certExpiresAt)
        : isSet(object.cert_expires_at)
        ? globalThis.String(object.cert_expires_at)
        : "",
      sealingPcrs: globalThis.Array.isArray(object?.sealingPcrs)
        ? object.sealingPcrs.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.sealing_pcrs)
        ? object.sealing_pcrs.map((e: any) => globalThis.Number(e))
        : [],
      sealValid: isSet(object.sealValid)
        ? globalThis.Boolean(object.sealValid)
        : isSet(object.seal_valid)
        ? globalThis.Boolean(object.seal_valid)
        : false,
      lastResealAt: isSet(object.lastResealAt)
        ? globalThis.String(object.lastResealAt)
        : isSet(object.last_reseal_at)
        ? globalThis.String(object.last_reseal_at)
        : "",
      currentPcrSnapshot: isObject(object.currentPcrSnapshot)
        ? (globalThis.Object.entries(object.currentPcrSnapshot) as [string, any][]).reduce(
          (acc: { [key: number]: string }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.current_pcr_snapshot)
        ? (globalThis.Object.entries(object.current_pcr_snapshot) as [string, any][]).reduce(
          (acc: { [key: number]: string }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: GetStatusResponse): unknown {
    const obj: any = {};
    if (message.provisioned !== false) {
      obj.provisioned = message.provisioned;
    }
    if (message.backend !== "") {
      obj.backend = message.backend;
    }
    if (message.certSubject !== "") {
      obj.certSubject = message.certSubject;
    }
    if (message.certFingerprint !== "") {
      obj.certFingerprint = message.certFingerprint;
    }
    if (message.certExpiresAt !== "") {
      obj.certExpiresAt = message.certExpiresAt;
    }
    if (message.sealingPcrs?.length) {
      obj.sealingPcrs = message.sealingPcrs.map((e) => Math.round(e));
    }
    if (message.sealValid !== false) {
      obj.sealValid = message.sealValid;
    }
    if (message.lastResealAt !== "") {
      obj.lastResealAt = message.lastResealAt;
    }
    if (message.currentPcrSnapshot) {
      const entries = globalThis.Object.entries(message.currentPcrSnapshot) as [string, string][];
      if (entries.length > 0) {
        obj.currentPcrSnapshot = {};
        entries.forEach(([k, v]) => {
          obj.currentPcrSnapshot[k] = v;
        });
      }
    }
    return obj;
  },

  create(base?: DeepPartial<GetStatusResponse>): GetStatusResponse {
    return GetStatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStatusResponse>): GetStatusResponse {
    const message = createBaseGetStatusResponse();
    message.provisioned = object.provisioned ?? false;
    message.backend = object.backend ?? "";
    message.certSubject = object.certSubject ?? "";
    message.certFingerprint = object.certFingerprint ?? "";
    message.certExpiresAt = object.certExpiresAt ?? "";
    message.sealingPcrs = object.sealingPcrs?.map((e) => e) || [];
    message.sealValid = object.sealValid ?? false;
    message.lastResealAt = object.lastResealAt ?? "";
    message.currentPcrSnapshot = (globalThis.Object.entries(object.currentPcrSnapshot ?? {}) as [string, string][])
      .reduce((acc: { [key: number]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.String(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseGetStatusResponse_CurrentPcrSnapshotEntry(): GetStatusResponse_CurrentPcrSnapshotEntry {
  return { key: 0, value: "" };
}

export const GetStatusResponse_CurrentPcrSnapshotEntry: MessageFns<GetStatusResponse_CurrentPcrSnapshotEntry> = {
  encode(message: GetStatusResponse_CurrentPcrSnapshotEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatusResponse_CurrentPcrSnapshotEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatusResponse_CurrentPcrSnapshotEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStatusResponse_CurrentPcrSnapshotEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: GetStatusResponse_CurrentPcrSnapshotEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<GetStatusResponse_CurrentPcrSnapshotEntry>): GetStatusResponse_CurrentPcrSnapshotEntry {
    return GetStatusResponse_CurrentPcrSnapshotEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<GetStatusResponse_CurrentPcrSnapshotEntry>,
  ): GetStatusResponse_CurrentPcrSnapshotEntry {
    const message = createBaseGetStatusResponse_CurrentPcrSnapshotEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseResealRequest(): ResealRequest {
  return { operatorAuthNonce: "" };
}

export const ResealRequest: MessageFns<ResealRequest> = {
  encode(message: ResealRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operatorAuthNonce !== "") {
      writer.uint32(10).string(message.operatorAuthNonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResealRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResealRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operatorAuthNonce = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResealRequest {
    return {
      operatorAuthNonce: isSet(object.operatorAuthNonce)
        ? globalThis.String(object.operatorAuthNonce)
        : isSet(object.operator_auth_nonce)
        ? globalThis.String(object.operator_auth_nonce)
        : "",
    };
  },

  toJSON(message: ResealRequest): unknown {
    const obj: any = {};
    if (message.operatorAuthNonce !== "") {
      obj.operatorAuthNonce = message.operatorAuthNonce;
    }
    return obj;
  },

  create(base?: DeepPartial<ResealRequest>): ResealRequest {
    return ResealRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResealRequest>): ResealRequest {
    const message = createBaseResealRequest();
    message.operatorAuthNonce = object.operatorAuthNonce ?? "";
    return message;
  },
};

function createBaseResealResponse(): ResealResponse {
  return { resealed: false, sealedAt: "", newPcrSnapshotIndices: [] };
}

export const ResealResponse: MessageFns<ResealResponse> = {
  encode(message: ResealResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resealed !== false) {
      writer.uint32(8).bool(message.resealed);
    }
    if (message.sealedAt !== "") {
      writer.uint32(18).string(message.sealedAt);
    }
    writer.uint32(26).fork();
    for (const v of message.newPcrSnapshotIndices) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResealResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResealResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.resealed = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sealedAt = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.newPcrSnapshotIndices.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.newPcrSnapshotIndices.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResealResponse {
    return {
      resealed: isSet(object.resealed) ? globalThis.Boolean(object.resealed) : false,
      sealedAt: isSet(object.sealedAt)
        ? globalThis.String(object.sealedAt)
        : isSet(object.sealed_at)
        ? globalThis.String(object.sealed_at)
        : "",
      newPcrSnapshotIndices: globalThis.Array.isArray(object?.newPcrSnapshotIndices)
        ? object.newPcrSnapshotIndices.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.new_pcr_snapshot_indices)
        ? object.new_pcr_snapshot_indices.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: ResealResponse): unknown {
    const obj: any = {};
    if (message.resealed !== false) {
      obj.resealed = message.resealed;
    }
    if (message.sealedAt !== "") {
      obj.sealedAt = message.sealedAt;
    }
    if (message.newPcrSnapshotIndices?.length) {
      obj.newPcrSnapshotIndices = message.newPcrSnapshotIndices.map((e) => Math.round(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ResealResponse>): ResealResponse {
    return ResealResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResealResponse>): ResealResponse {
    const message = createBaseResealResponse();
    message.resealed = object.resealed ?? false;
    message.sealedAt = object.sealedAt ?? "";
    message.newPcrSnapshotIndices = object.newPcrSnapshotIndices?.map((e) => e) || [];
    return message;
  },
};

export type DeviceIdentityServiceService = typeof DeviceIdentityServiceService;
export const DeviceIdentityServiceService = {
  /** Sign a payload with the device's non-extractable identity key. */
  sign: {
    path: "/droplet.device_identity.DeviceIdentityService/Sign" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SignRequest): Buffer => Buffer.from(SignRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SignRequest => SignRequest.decode(value),
    responseSerialize: (value: SignResponse): Buffer => Buffer.from(SignResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SignResponse => SignResponse.decode(value),
  },
  /** Return the device's self-signed X.509 cert (PEM-encoded). */
  getCert: {
    path: "/droplet.device_identity.DeviceIdentityService/GetCert" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetCertRequest): Buffer => Buffer.from(GetCertRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCertRequest => GetCertRequest.decode(value),
    responseSerialize: (value: GetCertResponse): Buffer => Buffer.from(GetCertResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetCertResponse => GetCertResponse.decode(value),
  },
  /** Report on provisioning state + seal validity. */
  getStatus: {
    path: "/droplet.device_identity.DeviceIdentityService/GetStatus" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetStatusRequest): Buffer => Buffer.from(GetStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetStatusRequest => GetStatusRequest.decode(value),
    responseSerialize: (value: GetStatusResponse): Buffer => Buffer.from(GetStatusResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetStatusResponse => GetStatusResponse.decode(value),
  },
  /**
   * Re-bind the sealed identity blob to the current PCR snapshot.
   * Requires a fresh operator-auth nonce issued by the orchestrator.
   */
  reseal: {
    path: "/droplet.device_identity.DeviceIdentityService/Reseal" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ResealRequest): Buffer => Buffer.from(ResealRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ResealRequest => ResealRequest.decode(value),
    responseSerialize: (value: ResealResponse): Buffer => Buffer.from(ResealResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ResealResponse => ResealResponse.decode(value),
  },
} as const;

export interface DeviceIdentityServiceServer extends UntypedServiceImplementation {
  /** Sign a payload with the device's non-extractable identity key. */
  sign: handleUnaryCall<SignRequest, SignResponse>;
  /** Return the device's self-signed X.509 cert (PEM-encoded). */
  getCert: handleUnaryCall<GetCertRequest, GetCertResponse>;
  /** Report on provisioning state + seal validity. */
  getStatus: handleUnaryCall<GetStatusRequest, GetStatusResponse>;
  /**
   * Re-bind the sealed identity blob to the current PCR snapshot.
   * Requires a fresh operator-auth nonce issued by the orchestrator.
   */
  reseal: handleUnaryCall<ResealRequest, ResealResponse>;
}

export interface DeviceIdentityServiceClient extends Client {
  /** Sign a payload with the device's non-extractable identity key. */
  sign(request: SignRequest, callback: (error: ServiceError | null, response: SignResponse) => void): ClientUnaryCall;
  sign(
    request: SignRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SignResponse) => void,
  ): ClientUnaryCall;
  sign(
    request: SignRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SignResponse) => void,
  ): ClientUnaryCall;
  /** Return the device's self-signed X.509 cert (PEM-encoded). */
  getCert(
    request: GetCertRequest,
    callback: (error: ServiceError | null, response: GetCertResponse) => void,
  ): ClientUnaryCall;
  getCert(
    request: GetCertRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetCertResponse) => void,
  ): ClientUnaryCall;
  getCert(
    request: GetCertRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetCertResponse) => void,
  ): ClientUnaryCall;
  /** Report on provisioning state + seal validity. */
  getStatus(
    request: GetStatusRequest,
    callback: (error: ServiceError | null, response: GetStatusResponse) => void,
  ): ClientUnaryCall;
  getStatus(
    request: GetStatusRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetStatusResponse) => void,
  ): ClientUnaryCall;
  getStatus(
    request: GetStatusRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetStatusResponse) => void,
  ): ClientUnaryCall;
  /**
   * Re-bind the sealed identity blob to the current PCR snapshot.
   * Requires a fresh operator-auth nonce issued by the orchestrator.
   */
  reseal(
    request: ResealRequest,
    callback: (error: ServiceError | null, response: ResealResponse) => void,
  ): ClientUnaryCall;
  reseal(
    request: ResealRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ResealResponse) => void,
  ): ClientUnaryCall;
  reseal(
    request: ResealRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ResealResponse) => void,
  ): ClientUnaryCall;
}

export const DeviceIdentityServiceClient = makeGenericClientConstructor(
  DeviceIdentityServiceService,
  "droplet.device_identity.DeviceIdentityService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): DeviceIdentityServiceClient;
  service: typeof DeviceIdentityServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
