// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v3.19.1
// source: inference.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "droplet.inference";

export interface ChatRequest {
  model: string;
  messages: Message[];
  temperature: number;
  maxTokens?: number | undefined;
  provider?:
    | string
    | undefined;
  /** Priority: 0 = user-initiated, 5 = automation, 10 = background */
  priority: number;
}

export interface Message {
  role: string;
  content: string;
}

export interface ChatResponse {
  content: string;
  model: string;
  usage: Usage | undefined;
  finishReason: string;
}

export interface ChatChunk {
  delta: string;
  done: boolean;
  usage?: Usage | undefined;
}

export interface Usage {
  promptTokens: number;
  completionTokens: number;
}

export interface Empty {
}

export interface ModelList {
  models: ModelInfo[];
}

export interface ModelInfo {
  id: string;
  provider: string;
  name: string;
  contextWindow?: number | undefined;
}

export interface EmbedRequest {
  /** Texts to embed. Max batch size is model-dependent (typically 256). */
  texts: string[];
  /**
   * Model override. Default: "bge-small-en-v1.5" (384-dim, 512-token
   * window, CPU-friendly). Empty string means the gateway default; any
   * other value must be in the gateway's EmbedText allow-list.
   */
  model?: string | undefined;
}

export interface EmbedResponse {
  embeddings: FloatArray[];
}

export interface FloatArray {
  values: number[];
}

export interface RerankRequest {
  /** The user query. */
  query: string;
  /** Candidate passages to score, in caller-defined order. */
  passages: string[];
  /** Model id. Default: "bge-reranker-base". */
  model?: string | undefined;
}

export interface RerankResponse {
  /** One float per input passage, same order. */
  scores: number[];
}

export interface ClassifyQueryRequest {
  query: string;
  /** Optional model override. Default: "MoritzLaurer/deberta-v3-base-zeroshot-v2.0". */
  model?: string | undefined;
}

export interface ClassifyQueryResponse {
  /** One of: "factual" | "analytical" | "conversational" | "navigational" | "unknown". */
  class: string;
  /**
   * Top-1 confidence in [0, 1]. Server-side floor is applied via
   * CLASSIFIER_CONFIDENCE_FLOOR; below the floor the class is "unknown".
   */
  confidence: number;
}

function createBaseChatRequest(): ChatRequest {
  return { model: "", messages: [], temperature: 0, maxTokens: undefined, provider: undefined, priority: 0 };
}

export const ChatRequest: MessageFns<ChatRequest> = {
  encode(message: ChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.model !== "") {
      writer.uint32(10).string(message.model);
    }
    for (const v of message.messages) {
      Message.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.temperature !== 0) {
      writer.uint32(29).float(message.temperature);
    }
    if (message.maxTokens !== undefined) {
      writer.uint32(32).int32(message.maxTokens);
    }
    if (message.provider !== undefined) {
      writer.uint32(42).string(message.provider);
    }
    if (message.priority !== 0) {
      writer.uint32(48).int32(message.priority);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.temperature = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxTokens = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.priority = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatRequest {
    return {
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      messages: globalThis.Array.isArray(object?.messages) ? object.messages.map((e: any) => Message.fromJSON(e)) : [],
      temperature: isSet(object.temperature) ? globalThis.Number(object.temperature) : 0,
      maxTokens: isSet(object.maxTokens)
        ? globalThis.Number(object.maxTokens)
        : isSet(object.max_tokens)
        ? globalThis.Number(object.max_tokens)
        : undefined,
      provider: isSet(object.provider) ? globalThis.String(object.provider) : undefined,
      priority: isSet(object.priority) ? globalThis.Number(object.priority) : 0,
    };
  },

  toJSON(message: ChatRequest): unknown {
    const obj: any = {};
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => Message.toJSON(e));
    }
    if (message.temperature !== 0) {
      obj.temperature = message.temperature;
    }
    if (message.maxTokens !== undefined) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    if (message.provider !== undefined) {
      obj.provider = message.provider;
    }
    if (message.priority !== 0) {
      obj.priority = Math.round(message.priority);
    }
    return obj;
  },

  create(base?: DeepPartial<ChatRequest>): ChatRequest {
    return ChatRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChatRequest>): ChatRequest {
    const message = createBaseChatRequest();
    message.model = object.model ?? "";
    message.messages = object.messages?.map((e) => Message.fromPartial(e)) || [];
    message.temperature = object.temperature ?? 0;
    message.maxTokens = object.maxTokens ?? undefined;
    message.provider = object.provider ?? undefined;
    message.priority = object.priority ?? 0;
    return message;
  },
};

function createBaseMessage(): Message {
  return { role: "", content: "" };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.role !== "") {
      writer.uint32(10).string(message.role);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    return obj;
  },

  create(base?: DeepPartial<Message>): Message {
    return Message.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Message>): Message {
    const message = createBaseMessage();
    message.role = object.role ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseChatResponse(): ChatResponse {
  return { content: "", model: "", usage: undefined, finishReason: "" };
}

export const ChatResponse: MessageFns<ChatResponse> = {
  encode(message: ChatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.model !== "") {
      writer.uint32(18).string(message.model);
    }
    if (message.usage !== undefined) {
      Usage.encode(message.usage, writer.uint32(26).fork()).join();
    }
    if (message.finishReason !== "") {
      writer.uint32(34).string(message.finishReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.usage = Usage.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.finishReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatResponse {
    return {
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      usage: isSet(object.usage) ? Usage.fromJSON(object.usage) : undefined,
      finishReason: isSet(object.finishReason)
        ? globalThis.String(object.finishReason)
        : isSet(object.finish_reason)
        ? globalThis.String(object.finish_reason)
        : "",
    };
  },

  toJSON(message: ChatResponse): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.usage !== undefined) {
      obj.usage = Usage.toJSON(message.usage);
    }
    if (message.finishReason !== "") {
      obj.finishReason = message.finishReason;
    }
    return obj;
  },

  create(base?: DeepPartial<ChatResponse>): ChatResponse {
    return ChatResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChatResponse>): ChatResponse {
    const message = createBaseChatResponse();
    message.content = object.content ?? "";
    message.model = object.model ?? "";
    message.usage = (object.usage !== undefined && object.usage !== null) ? Usage.fromPartial(object.usage) : undefined;
    message.finishReason = object.finishReason ?? "";
    return message;
  },
};

function createBaseChatChunk(): ChatChunk {
  return { delta: "", done: false, usage: undefined };
}

export const ChatChunk: MessageFns<ChatChunk> = {
  encode(message: ChatChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.delta !== "") {
      writer.uint32(10).string(message.delta);
    }
    if (message.done !== false) {
      writer.uint32(16).bool(message.done);
    }
    if (message.usage !== undefined) {
      Usage.encode(message.usage, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.delta = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.done = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.usage = Usage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatChunk {
    return {
      delta: isSet(object.delta) ? globalThis.String(object.delta) : "",
      done: isSet(object.done) ? globalThis.Boolean(object.done) : false,
      usage: isSet(object.usage) ? Usage.fromJSON(object.usage) : undefined,
    };
  },

  toJSON(message: ChatChunk): unknown {
    const obj: any = {};
    if (message.delta !== "") {
      obj.delta = message.delta;
    }
    if (message.done !== false) {
      obj.done = message.done;
    }
    if (message.usage !== undefined) {
      obj.usage = Usage.toJSON(message.usage);
    }
    return obj;
  },

  create(base?: DeepPartial<ChatChunk>): ChatChunk {
    return ChatChunk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChatChunk>): ChatChunk {
    const message = createBaseChatChunk();
    message.delta = object.delta ?? "";
    message.done = object.done ?? false;
    message.usage = (object.usage !== undefined && object.usage !== null) ? Usage.fromPartial(object.usage) : undefined;
    return message;
  },
};

function createBaseUsage(): Usage {
  return { promptTokens: 0, completionTokens: 0 };
}

export const Usage: MessageFns<Usage> = {
  encode(message: Usage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.promptTokens !== 0) {
      writer.uint32(8).int32(message.promptTokens);
    }
    if (message.completionTokens !== 0) {
      writer.uint32(16).int32(message.completionTokens);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Usage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.promptTokens = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.completionTokens = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Usage {
    return {
      promptTokens: isSet(object.promptTokens)
        ? globalThis.Number(object.promptTokens)
        : isSet(object.prompt_tokens)
        ? globalThis.Number(object.prompt_tokens)
        : 0,
      completionTokens: isSet(object.completionTokens)
        ? globalThis.Number(object.completionTokens)
        : isSet(object.completion_tokens)
        ? globalThis.Number(object.completion_tokens)
        : 0,
    };
  },

  toJSON(message: Usage): unknown {
    const obj: any = {};
    if (message.promptTokens !== 0) {
      obj.promptTokens = Math.round(message.promptTokens);
    }
    if (message.completionTokens !== 0) {
      obj.completionTokens = Math.round(message.completionTokens);
    }
    return obj;
  },

  create(base?: DeepPartial<Usage>): Usage {
    return Usage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Usage>): Usage {
    const message = createBaseUsage();
    message.promptTokens = object.promptTokens ?? 0;
    message.completionTokens = object.completionTokens ?? 0;
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<Empty>): Empty {
    return Empty.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<Empty>): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseModelList(): ModelList {
  return { models: [] };
}

export const ModelList: MessageFns<ModelList> = {
  encode(message: ModelList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.models) {
      ModelInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModelList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModelList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.models.push(ModelInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModelList {
    return {
      models: globalThis.Array.isArray(object?.models) ? object.models.map((e: any) => ModelInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: ModelList): unknown {
    const obj: any = {};
    if (message.models?.length) {
      obj.models = message.models.map((e) => ModelInfo.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ModelList>): ModelList {
    return ModelList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ModelList>): ModelList {
    const message = createBaseModelList();
    message.models = object.models?.map((e) => ModelInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseModelInfo(): ModelInfo {
  return { id: "", provider: "", name: "", contextWindow: undefined };
}

export const ModelInfo: MessageFns<ModelInfo> = {
  encode(message: ModelInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.provider !== "") {
      writer.uint32(18).string(message.provider);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.contextWindow !== undefined) {
      writer.uint32(32).int32(message.contextWindow);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModelInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModelInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.contextWindow = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModelInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      contextWindow: isSet(object.contextWindow)
        ? globalThis.Number(object.contextWindow)
        : isSet(object.context_window)
        ? globalThis.Number(object.context_window)
        : undefined,
    };
  },

  toJSON(message: ModelInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.contextWindow !== undefined) {
      obj.contextWindow = Math.round(message.contextWindow);
    }
    return obj;
  },

  create(base?: DeepPartial<ModelInfo>): ModelInfo {
    return ModelInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ModelInfo>): ModelInfo {
    const message = createBaseModelInfo();
    message.id = object.id ?? "";
    message.provider = object.provider ?? "";
    message.name = object.name ?? "";
    message.contextWindow = object.contextWindow ?? undefined;
    return message;
  },
};

function createBaseEmbedRequest(): EmbedRequest {
  return { texts: [], model: undefined };
}

export const EmbedRequest: MessageFns<EmbedRequest> = {
  encode(message: EmbedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.texts) {
      writer.uint32(10).string(v!);
    }
    if (message.model !== undefined) {
      writer.uint32(18).string(message.model);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.texts.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.model = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmbedRequest {
    return {
      texts: globalThis.Array.isArray(object?.texts) ? object.texts.map((e: any) => globalThis.String(e)) : [],
      model: isSet(object.model) ? globalThis.String(object.model) : undefined,
    };
  },

  toJSON(message: EmbedRequest): unknown {
    const obj: any = {};
    if (message.texts?.length) {
      obj.texts = message.texts;
    }
    if (message.model !== undefined) {
      obj.model = message.model;
    }
    return obj;
  },

  create(base?: DeepPartial<EmbedRequest>): EmbedRequest {
    return EmbedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EmbedRequest>): EmbedRequest {
    const message = createBaseEmbedRequest();
    message.texts = object.texts?.map((e) => e) || [];
    message.model = object.model ?? undefined;
    return message;
  },
};

function createBaseEmbedResponse(): EmbedResponse {
  return { embeddings: [] };
}

export const EmbedResponse: MessageFns<EmbedResponse> = {
  encode(message: EmbedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.embeddings) {
      FloatArray.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.embeddings.push(FloatArray.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmbedResponse {
    return {
      embeddings: globalThis.Array.isArray(object?.embeddings)
        ? object.embeddings.map((e: any) => FloatArray.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EmbedResponse): unknown {
    const obj: any = {};
    if (message.embeddings?.length) {
      obj.embeddings = message.embeddings.map((e) => FloatArray.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<EmbedResponse>): EmbedResponse {
    return EmbedResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EmbedResponse>): EmbedResponse {
    const message = createBaseEmbedResponse();
    message.embeddings = object.embeddings?.map((e) => FloatArray.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFloatArray(): FloatArray {
  return { values: [] };
}

export const FloatArray: MessageFns<FloatArray> = {
  encode(message: FloatArray, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.values) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FloatArray {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFloatArray();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.values.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.values.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FloatArray {
    return {
      values: globalThis.Array.isArray(object?.values) ? object.values.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: FloatArray): unknown {
    const obj: any = {};
    if (message.values?.length) {
      obj.values = message.values;
    }
    return obj;
  },

  create(base?: DeepPartial<FloatArray>): FloatArray {
    return FloatArray.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FloatArray>): FloatArray {
    const message = createBaseFloatArray();
    message.values = object.values?.map((e) => e) || [];
    return message;
  },
};

function createBaseRerankRequest(): RerankRequest {
  return { query: "", passages: [], model: undefined };
}

export const RerankRequest: MessageFns<RerankRequest> = {
  encode(message: RerankRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    for (const v of message.passages) {
      writer.uint32(18).string(v!);
    }
    if (message.model !== undefined) {
      writer.uint32(26).string(message.model);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RerankRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRerankRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.passages.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.model = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RerankRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      passages: globalThis.Array.isArray(object?.passages) ? object.passages.map((e: any) => globalThis.String(e)) : [],
      model: isSet(object.model) ? globalThis.String(object.model) : undefined,
    };
  },

  toJSON(message: RerankRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.passages?.length) {
      obj.passages = message.passages;
    }
    if (message.model !== undefined) {
      obj.model = message.model;
    }
    return obj;
  },

  create(base?: DeepPartial<RerankRequest>): RerankRequest {
    return RerankRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RerankRequest>): RerankRequest {
    const message = createBaseRerankRequest();
    message.query = object.query ?? "";
    message.passages = object.passages?.map((e) => e) || [];
    message.model = object.model ?? undefined;
    return message;
  },
};

function createBaseRerankResponse(): RerankResponse {
  return { scores: [] };
}

export const RerankResponse: MessageFns<RerankResponse> = {
  encode(message: RerankResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.scores) {
      writer.float(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RerankResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRerankResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 13) {
            message.scores.push(reader.float());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.scores.push(reader.float());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RerankResponse {
    return {
      scores: globalThis.Array.isArray(object?.scores) ? object.scores.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: RerankResponse): unknown {
    const obj: any = {};
    if (message.scores?.length) {
      obj.scores = message.scores;
    }
    return obj;
  },

  create(base?: DeepPartial<RerankResponse>): RerankResponse {
    return RerankResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RerankResponse>): RerankResponse {
    const message = createBaseRerankResponse();
    message.scores = object.scores?.map((e) => e) || [];
    return message;
  },
};

function createBaseClassifyQueryRequest(): ClassifyQueryRequest {
  return { query: "", model: undefined };
}

export const ClassifyQueryRequest: MessageFns<ClassifyQueryRequest> = {
  encode(message: ClassifyQueryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.model !== undefined) {
      writer.uint32(18).string(message.model);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClassifyQueryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClassifyQueryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.model = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClassifyQueryRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      model: isSet(object.model) ? globalThis.String(object.model) : undefined,
    };
  },

  toJSON(message: ClassifyQueryRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.model !== undefined) {
      obj.model = message.model;
    }
    return obj;
  },

  create(base?: DeepPartial<ClassifyQueryRequest>): ClassifyQueryRequest {
    return ClassifyQueryRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ClassifyQueryRequest>): ClassifyQueryRequest {
    const message = createBaseClassifyQueryRequest();
    message.query = object.query ?? "";
    message.model = object.model ?? undefined;
    return message;
  },
};

function createBaseClassifyQueryResponse(): ClassifyQueryResponse {
  return { class: "", confidence: 0 };
}

export const ClassifyQueryResponse: MessageFns<ClassifyQueryResponse> = {
  encode(message: ClassifyQueryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.class !== "") {
      writer.uint32(10).string(message.class);
    }
    if (message.confidence !== 0) {
      writer.uint32(21).float(message.confidence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClassifyQueryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClassifyQueryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.class = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClassifyQueryResponse {
    return {
      class: isSet(object.class) ? globalThis.String(object.class) : "",
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
    };
  },

  toJSON(message: ClassifyQueryResponse): unknown {
    const obj: any = {};
    if (message.class !== "") {
      obj.class = message.class;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    return obj;
  },

  create(base?: DeepPartial<ClassifyQueryResponse>): ClassifyQueryResponse {
    return ClassifyQueryResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ClassifyQueryResponse>): ClassifyQueryResponse {
    const message = createBaseClassifyQueryResponse();
    message.class = object.class ?? "";
    message.confidence = object.confidence ?? 0;
    return message;
  },
};

export type InferenceServiceService = typeof InferenceServiceService;
export const InferenceServiceService = {
  /** Unary chat completion */
  chat: {
    path: "/droplet.inference.InferenceService/Chat" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ChatRequest): Buffer => Buffer.from(ChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatRequest => ChatRequest.decode(value),
    responseSerialize: (value: ChatResponse): Buffer => Buffer.from(ChatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatResponse => ChatResponse.decode(value),
  },
  /** Server-side streaming chat completion */
  streamChat: {
    path: "/droplet.inference.InferenceService/StreamChat" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: ChatRequest): Buffer => Buffer.from(ChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatRequest => ChatRequest.decode(value),
    responseSerialize: (value: ChatChunk): Buffer => Buffer.from(ChatChunk.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatChunk => ChatChunk.decode(value),
  },
  /** List available models */
  listModels: {
    path: "/droplet.inference.InferenceService/ListModels" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: ModelList): Buffer => Buffer.from(ModelList.encode(value).finish()),
    responseDeserialize: (value: Buffer): ModelList => ModelList.decode(value),
  },
  /** Text embedding — used by the file-indexer for semantic search (Phase 4) */
  embedText: {
    path: "/droplet.inference.InferenceService/EmbedText" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: EmbedRequest): Buffer => Buffer.from(EmbedRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EmbedRequest => EmbedRequest.decode(value),
    responseSerialize: (value: EmbedResponse): Buffer => Buffer.from(EmbedResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): EmbedResponse => EmbedResponse.decode(value),
  },
  /**
   * Text reranker — used by the orchestrator for hybrid retrieval (WARP-286).
   * Scores each passage against the query using a cross-encoder.
   */
  rerank: {
    path: "/droplet.inference.InferenceService/Rerank" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RerankRequest): Buffer => Buffer.from(RerankRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RerankRequest => RerankRequest.decode(value),
    responseSerialize: (value: RerankResponse): Buffer => Buffer.from(RerankResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RerankResponse => RerankResponse.decode(value),
  },
  /**
   * Zero-shot query classifier — used by the orchestrator's adaptive
   * retrieval router (WARP-437). Returns one of {factual, analytical,
   * conversational, navigational, unknown}.
   */
  classifyQuery: {
    path: "/droplet.inference.InferenceService/ClassifyQuery" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ClassifyQueryRequest): Buffer => Buffer.from(ClassifyQueryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ClassifyQueryRequest => ClassifyQueryRequest.decode(value),
    responseSerialize: (value: ClassifyQueryResponse): Buffer =>
      Buffer.from(ClassifyQueryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ClassifyQueryResponse => ClassifyQueryResponse.decode(value),
  },
} as const;

export interface InferenceServiceServer extends UntypedServiceImplementation {
  /** Unary chat completion */
  chat: handleUnaryCall<ChatRequest, ChatResponse>;
  /** Server-side streaming chat completion */
  streamChat: handleServerStreamingCall<ChatRequest, ChatChunk>;
  /** List available models */
  listModels: handleUnaryCall<Empty, ModelList>;
  /** Text embedding — used by the file-indexer for semantic search (Phase 4) */
  embedText: handleUnaryCall<EmbedRequest, EmbedResponse>;
  /**
   * Text reranker — used by the orchestrator for hybrid retrieval (WARP-286).
   * Scores each passage against the query using a cross-encoder.
   */
  rerank: handleUnaryCall<RerankRequest, RerankResponse>;
  /**
   * Zero-shot query classifier — used by the orchestrator's adaptive
   * retrieval router (WARP-437). Returns one of {factual, analytical,
   * conversational, navigational, unknown}.
   */
  classifyQuery: handleUnaryCall<ClassifyQueryRequest, ClassifyQueryResponse>;
}

export interface InferenceServiceClient extends Client {
  /** Unary chat completion */
  chat(request: ChatRequest, callback: (error: ServiceError | null, response: ChatResponse) => void): ClientUnaryCall;
  chat(
    request: ChatRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ChatResponse) => void,
  ): ClientUnaryCall;
  chat(
    request: ChatRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ChatResponse) => void,
  ): ClientUnaryCall;
  /** Server-side streaming chat completion */
  streamChat(request: ChatRequest, options?: Partial<CallOptions>): ClientReadableStream<ChatChunk>;
  streamChat(
    request: ChatRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<ChatChunk>;
  /** List available models */
  listModels(request: Empty, callback: (error: ServiceError | null, response: ModelList) => void): ClientUnaryCall;
  listModels(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ModelList) => void,
  ): ClientUnaryCall;
  listModels(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ModelList) => void,
  ): ClientUnaryCall;
  /** Text embedding — used by the file-indexer for semantic search (Phase 4) */
  embedText(
    request: EmbedRequest,
    callback: (error: ServiceError | null, response: EmbedResponse) => void,
  ): ClientUnaryCall;
  embedText(
    request: EmbedRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: EmbedResponse) => void,
  ): ClientUnaryCall;
  embedText(
    request: EmbedRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: EmbedResponse) => void,
  ): ClientUnaryCall;
  /**
   * Text reranker — used by the orchestrator for hybrid retrieval (WARP-286).
   * Scores each passage against the query using a cross-encoder.
   */
  rerank(
    request: RerankRequest,
    callback: (error: ServiceError | null, response: RerankResponse) => void,
  ): ClientUnaryCall;
  rerank(
    request: RerankRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RerankResponse) => void,
  ): ClientUnaryCall;
  rerank(
    request: RerankRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RerankResponse) => void,
  ): ClientUnaryCall;
  /**
   * Zero-shot query classifier — used by the orchestrator's adaptive
   * retrieval router (WARP-437). Returns one of {factual, analytical,
   * conversational, navigational, unknown}.
   */
  classifyQuery(
    request: ClassifyQueryRequest,
    callback: (error: ServiceError | null, response: ClassifyQueryResponse) => void,
  ): ClientUnaryCall;
  classifyQuery(
    request: ClassifyQueryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ClassifyQueryResponse) => void,
  ): ClientUnaryCall;
  classifyQuery(
    request: ClassifyQueryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ClassifyQueryResponse) => void,
  ): ClientUnaryCall;
}

export const InferenceServiceClient = makeGenericClientConstructor(
  InferenceServiceService,
  "droplet.inference.InferenceService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): InferenceServiceClient;
  service: typeof InferenceServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
