-- =============================================================================
-- WARP-1542 — documented schema-drift baseline.
--
-- THIS IS NOT A MIGRATION. Nothing ever executes this file. It is the frozen,
-- reviewed answer to `prisma migrate diff --from-migrations
-- --to-schema-datamodel`, i.e. "replay every migration into an empty database
-- — what would still have to change for it to match schema.prisma?"
--
-- scripts/check-schema-drift.sh regenerates that diff in CI (the pg-integration
-- job in .github/workflows/orchestrator-tests.yml) and compares it to the
-- statements below. Any NEW drift fails the job. Drift that gets CLOSED also
-- fails, so this file cannot quietly decay into a blanket exemption.
--
-- WHY A BASELINE INSTEAD OF AN EMPTY DIFF
-- ---------------------------------------
-- main already carried a six-entry delta when the gate was added (measured on
-- 479f2569). WARP-2634 closed the four closable entries; what remains can
-- NEVER be closed — Prisma has no datamodel syntax for a GENERATED column
-- expression, a GIN index, or an index on an `Unsupported()` vector column, so
-- `migrate diff` reports these three statements on every run by construction.
-- A gate demanding an empty diff would therefore be red forever. Freezing the
-- measured delta gates every FUTURE divergence without pretending the
-- permanent one isn't there.
--
-- THE ENTRIES, ANNOTATED
-- ----------------------
-- Everything still below the sentinel is PRISMA-INEXPRESSIBLE: permanent, by
-- construction, and must never be "fixed".
--
--  A. FileContentChunk.text_tsv loses its generated expression, and
--     FileContentChunk_text_tsv_idx is dropped.
--     -> text_tsv is `Unsupported("tsvector")` with a `GENERATED ALWAYS AS
--        (...)` expression (WARP-286, reshaped by WARP-242 so sensitive chunks
--        index as NULL), indexed with GIN. Prisma has no datamodel syntax for
--        either, so `migrate diff` proposes removing both on every run,
--        forever. Applying them would drop the lexical-search index and the
--        crypto-shred guarantee that rides on it.
--
--  B. FileContentChunk_embedding_hnsw_idx is dropped.
--     -> WARP-2193 gave the vector arm an HNSW index (`USING hnsw (embedding
--        vector_cosine_ops)`, migration 20260826120000). `embedding` is
--        `Unsupported("vector(384)")` and Prisma has no datamodel syntax for
--        an index on one, let alone for the hnsw access method. Applying it
--        drops the only ANN index on the corpus and returns every semantic
--        search to a sequential scan. That is not hypothetical — it is what
--        happened between 20260425220000 (which dropped the predecessor
--        IVFFlat index as generated collateral) and WARP-2193, unnoticed for
--        four months.
--
-- CLOSED BY WARP-2634 (2026-09-02) — kept here so the history is readable
-- ----------------------------------------------------------------------
-- These four were carried as OPEN DRIFT from WARP-1542 until WARP-2634. Each
-- one meant that replaying every migration into an empty database produced a
-- schema the generated client disagreed with, i.e. a fresh box (or `migrate
-- reset`) differed from a box that had been migrated in place.
--
--  1. ToolRunStatus was missing `pending` and `running`; ToolRun.status
--     defaulted to 'ok' in SQL and `pending` in the datamodel.
--     -> CLOSED, migration side. 20260903020000 adds both enum members
--        (BEFORE 'ok', matching the datamodel's declaration order) and
--        20260903020100 sets the column default. Two files because Postgres
--        will not accept a new enum value and a DEFAULT that USES it in one
--        transaction. Additive: tool-spec-runner.service.ts:410 is the only
--        writer and always passes `status` explicitly, so no runtime behaviour
--        moved — but the client had been accepting `status: "running"` for a
--        value no box's enum contained.
--
--  2. Department_parentId_fkey was ON DELETE RESTRICT in SQL, ON DELETE SET
--     NULL in the datamodel.
--     -> CLOSED, schema side: `onDelete: Restrict` is now declared explicitly.
--        RESTRICT is what 20260711000000_warp_1255_departments created and
--        what every migrated box has always done; SET NULL was only Prisma's
--        implicit default for an optional relation leaking into the datamodel.
--        Declaring the truth changes no behaviour — nothing row-deletes a
--        Department (`DELETE /api/departments/:id` archives). Whether RESTRICT
--        or SET NULL is the right PRODUCT behaviour is still an open question
--        and still not a CI decision; it now just has to be answered by
--        changing both sides deliberately instead of by noticing the gap.
--
--  3. Department_parentId_idx existed in SQL, absent from the datamodel.
--     -> CLOSED, schema side: `@@index([parentId])` declared. The index has
--        always existed; Postgres does not auto-index FK columns and the
--        datamodel was simply not describing one that was doing real work.
--
--  4. AssistantPersona.updatedAt / BusinessProfile.updatedAt / TlsCert
--     .updatedAt carried DEFAULT CURRENT_TIMESTAMP in SQL, none in the
--     datamodel.
--     -> CLOSED, migration side: 20260903020100 drops all three defaults.
--        `@updatedAt` is application-managed and Prisma emits no DB default
--        for it, so the datamodel was right and the hand-written migrations
--        had added something extra. Declaring `@default(now())` instead would
--        have moved the lie rather than removed it. Safe: all three tables are
--        written only through Prisma, which always supplies the column, and
--        the two singleton seeds pass CURRENT_TIMESTAMP explicitly.
--
--   4. ADR-048 (WARP-2729) — four PARTIAL unique indexes on `FilingDecision`
--      and `IngestProposal`.
--
--      Prisma's datamodel has no syntax for a `WHERE` predicate on a unique
--      index, so `migrate diff` reports a DROP for each of them on every run,
--      exactly as it does for the HNSW index above. They cannot be replaced by
--      a plain `@@unique`, because a compound unique over a NULLABLE column
--      never collides in Postgres (NULL <> NULL) — which is the trap WARP-2549's
--      landing code hit, and why it uses updateMany-then-create with a P2002
--      retry instead of `upsert`.
--
--      What each one protects:
--        * FilingDecision_ignore_source_key  — one "ignore this sender" rule
--          per key, so the Rules tab cannot accumulate duplicates.
--        * FilingDecision_always_here_key    — one "always file here" rule per
--          (key, customer).
--        * FilingDecision_not_same_key       — one "not the same" rule per
--          (key, customer), so a rejected pair is remembered once.
--        * IngestProposal_pending_dedupe_key — at most one PENDING proposal per
--          (kind, dedupeKey). Decided rows are exempt on purpose: history
--          accumulates, but a second document about the same customer must
--          offer to LINK to the pending one rather than mint a duplicate.
--
-- UPDATING THIS FILE
-- ------------------
-- Do not hand-edit below the sentinel. Run:
--   scripts/check-schema-drift.sh --update
-- then read the resulting diff and record WHY it moved in the list above.
-- =============================================================================
-- ===== GENERATED BASELINE BELOW: regenerate with check-schema-drift.sh --update =====
-- DropIndex
DROP INDEX "FileContentChunk_embedding_hnsw_idx";

-- DropIndex
DROP INDEX "FileContentChunk_text_tsv_idx";

-- AlterTable
ALTER TABLE "FileContentChunk" ALTER COLUMN "text_tsv" DROP DEFAULT;

-- DropIndex
DROP INDEX "FilingDecision_ignore_source_key";

-- DropIndex
DROP INDEX "FilingDecision_always_here_key";

-- DropIndex
DROP INDEX "FilingDecision_not_same_key";

-- DropIndex
DROP INDEX "IngestProposal_pending_dedupe_key";
