/**
 * matter-controller sidecar configuration (WARP-850).
 *
 * Env naming: `DROPLET_MATTER_*` ONLY for our own knobs — matter.js
 * scans process.env for `MATTER_*` at startup and folds each one into
 * its VariableService (see the long warning in
 * apps/orchestrator/src/config.ts and architecture-guard rule 11).
 * `MATTER_STORAGE_PATH` is the single allow-listed survivor
 * (scripts/test-security.sh MATTER_ENV_ALLOWLIST): it folds to the var
 * `storage.path`, which is exactly the matter.js knob that points the
 * controller's persisted fabric at the `matter-data` volume. It moved
 * here from the orchestrator unchanged so commissioned fabrics survive
 * the WARP-850 extraction (requirement #2).
 */

import * as path from "node:path";
import { z } from "zod";

const defaultMatterStorage =
  process.env.NODE_ENV === "production"
    ? "/data/matter-storage"
    : path.resolve(".data/matter-storage");

const envSchema = z.object({
  PORT: z.coerce.number().default(8083),
  NODE_ENV: z
    .enum(["development", "production", "test"])
    .default("development"),

  // Fabric storage — see header comment. Mounted from the `matter-data`
  // named volume in docker/docker-compose.yml.
  MATTER_STORAGE_PATH: z.string().default(defaultMatterStorage),

  // Admin fabric label shown in Matter device fabric tables.
  DROPLET_MATTER_CONTROLLER_NAME: z.string().default("Droplet"),

  // Shared bearer the orchestrator presents in the X-Droplet-Auth
  // header (device-bridge precedent). Generated by scripts/setup.sh
  // into .env. Empty default = the auth wall fails closed and every
  // data route 401s until the operator runs setup.
  DROPLET_MATTER_SERVICE_TOKEN: z.string().default(""),

  // Which HCI adapter to commission over. hci0 on the shipping
  // single-box (Intel AX210).
  DROPLET_MATTER_BLE_HCI_ID: z.coerce.number().default(0),

  // WARP-895: Wi-Fi network handed to a BLE-first Matter device during
  // commissioning so it can move off BLE onto the operational LAN
  // (matter.js AddOrUpdateWiFiNetwork). Empty SSID ⇒ on-network-only
  // commissioning (the pre-WARP-895 behaviour). `DROPLET_MATTER_*` prefix
  // ONLY — a bare `MATTER_*` name is auto-imported by matter.js's
  // VariableService and collides with root-node behavior ids.
  DROPLET_MATTER_WIFI_SSID: z.string().default(""),
  // WARP-1363: SSID source order mirrors the PSK — the file first (the
  // live AP SSID persisted by droplet-openwrt-attach at
  // /etc/droplet/ap-ssid on every attach/rename), then the env var above.
  // The env value is written once at setup and goes stale on an AP rename
  // (claim / wizard Wi-Fi save) — the commissionee then scans for a
  // network that no longer broadcasts and fails with NetworkNotFound.
  //
  // WARP-1509: this schema default is deliberately "" (not the real path)
  // — docker-compose's `${DROPLET_MATTER_WIFI_SSID_FILE:-}` interpolation
  // hands the container an EXPLICIT empty string whenever .env doesn't set
  // it, and zod's `.default()` only fires for `undefined`, never for an
  // already-present empty string. The actual /etc/droplet/ap-ssid default
  // is applied below, after parsing, so it also covers that
  // explicit-empty-string shape (the one a box updated via `git pull` +
  // rebuild — no fresh `setup.sh --single-box` — actually hits: proven
  // live on .87).
  DROPLET_MATTER_WIFI_SSID_FILE: z.string().default(""),
  // PSK source order: the file first (the per-box AP PSK is generated by
  // droplet-openwrt-attach on first boot and persisted 0600 at
  // /etc/droplet/ap-psk — WARP-819 — and needs a bind mount), then the env
  // var below (operator-set / dev / test). WARP-1513: same schema-default
  // caveat as the SSID file above — the real path is applied post-parse.
  DROPLET_MATTER_WIFI_PSK_FILE: z.string().default(""),
  DROPLET_MATTER_WIFI_PSK: z.string().default(""),
  // ISO-3166 alpha-2 regulatory domain for commissioning. "XX" =
  // unspecified (matter.js default); set the box's country for
  // regulatory-correct channel/power behaviour.
  DROPLET_MATTER_REGULATORY_COUNTRY: z.string().default("XX"),
});

const parsedConfig = envSchema.parse(process.env);

// WARP-1509: default DROPLET_MATTER_WIFI_SSID_FILE to the real path IN
// CODE, not just in the env schema (see the comment on the field above) —
// the compose mount (`/etc/droplet:/etc/droplet:ro`, docker/docker-compose.yml)
// already exposes /etc/droplet/ap-ssid read-only, so the sidecar needs no
// operator/setup-script action to try it. An explicit non-blank
// DROPLET_MATTER_WIFI_SSID_FILE still overrides this default.
const DEFAULT_WIFI_SSID_FILE = "/etc/droplet/ap-ssid";
// WARP-1513: the PSK file path has the identical never-defaulted gap —
// same explicit-empty-string compose shape, same post-parse fix.
const DEFAULT_WIFI_PSK_FILE = "/etc/droplet/ap-psk";

export const config = {
  ...parsedConfig,
  DROPLET_MATTER_WIFI_SSID_FILE:
    parsedConfig.DROPLET_MATTER_WIFI_SSID_FILE.trim() || DEFAULT_WIFI_SSID_FILE,
  DROPLET_MATTER_WIFI_PSK_FILE:
    parsedConfig.DROPLET_MATTER_WIFI_PSK_FILE.trim() || DEFAULT_WIFI_PSK_FILE,
};
