/**
 * HTTP API for the matter-controller sidecar (WARP-850).
 *
 * Consumed ONLY by the orchestrator (apps/orchestrator/src/services/
 * matter.service.ts). The route surface mirrors the operations the
 * orchestrator's /api/matter/* routes need, 1:1:
 *
 *   GET    /health                    liveness (unauthenticated)
 *   GET    /capabilities             { bleCommissioning, reason }
 *   GET    /devices                  grouped commissioned devices
 *   GET    /devices/:nodeId          single device or 404
 *   POST   /devices/:nodeId/command  { command, data } → { status }
 *   POST   /devices/:nodeId/reconnect force a reconnect → { status }
 *   DELETE /devices/:nodeId          decommission
 *   POST   /commission               { pairing_code } → { nodeId }
 *   GET    /discover?timeout=ms      { devices, count }
 *   GET    /events                   SSE: state_changed / connection_changed
 *
 * Auth: shared token in the `X-Droplet-Auth` header, following the
 * device-bridge precedent (services/oled-display/device-bridge.py).
 * Compared with timingSafeEqual; FAIL-CLOSED when the configured token
 * is empty (an unconfigured box rejects everything except /health).
 *
 * Error contract (requirement #4): every non-2xx response carries
 * `{ error, errorClass, errorMessage }` where errorClass/errorMessage
 * are the raw matter.js error constructor name + message. The
 * orchestrator reconstructs the error from those fields so its
 * translateCommissionError() message-pattern mapping (WARP-851's 22
 * tests) behaves exactly as it did in-process. NO translation happens
 * on this side.
 */

import { timingSafeEqual } from "node:crypto";
import express, {
  type Express,
  type NextFunction,
  type Request,
  type Response,
} from "express";
import pino from "pino";
import {
  resolveWifiNetwork,
  resolveWifiSsid,
  type MatterControllerCore,
  type WifiProvisioningOptions,
} from "./controller.js";
import type { BleRegistrationResult } from "./ble.js";
import type { SidecarErrorBody } from "./types.js";

const logger = pino({ name: "matter-controller-http" });

export interface AppDeps {
  core: MatterControllerCore;
  /** DROPLET_MATTER_SERVICE_TOKEN — generated by setup.sh into .env. */
  authToken: string;
  /** Computed ONCE at process start by registerBleAtProcessStart. */
  capabilities: BleRegistrationResult;
  /**
   * WARP-1035: the SAME Wi-Fi knobs handed to the core (WARP-895).
   * /capabilities re-runs resolveWifiNetwork on them per request, so
   * `wifiProvisioning` always mirrors what the next commission would do
   * — including a per-box AP PSK that landed at /etc/droplet/ap-psk
   * AFTER this process started (first-boot ordering, no restart).
   */
  wifiOptions: WifiProvisioningOptions;
}

/** Matter node IDs are uint64 — 18446744073709551615 is the ceiling. */
const NODE_ID_MAX = 18446744073709551615n;

/**
 * Mirror of routes/matter.ts isValidNodeId — digits only, BigInt-safe,
 * and inside the uint64 range (20 digits can exceed the ceiling, which
 * would blow up in NodeId() as a 500 instead of this validator's 400).
 */
function isValidNodeId(id: string): boolean {
  return /^\d{1,20}$/.test(id) && BigInt(id) <= NODE_ID_MAX;
}

function errorBody(err: unknown): SidecarErrorBody {
  const message = err instanceof Error ? err.message : String(err);
  const errorClass =
    err instanceof Error ? err.constructor.name : "Error";
  return { error: message, errorClass, errorMessage: message };
}

function constantTimeMatch(expected: string, got: string): boolean {
  const a = Buffer.from(expected);
  const b = Buffer.from(got);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

export function createApp(deps: AppDeps): Express {
  const { core, authToken, capabilities, wifiOptions } = deps;
  const app = express();
  app.use(express.json());

  // --- Liveness (unauthenticated — docker healthcheck + orchestrator probe target is /health with auth; keep body free of secrets) ---
  app.get("/health", (_req, res) => {
    res.json({ ok: true, initialized: core.isInitialized() });
  });

  // --- Auth wall for everything else ---
  app.use((req: Request, res: Response, next: NextFunction) => {
    // Fail closed: an empty configured token can never authenticate.
    // Same posture as device-bridge.py's BRIDGE_AUTH_TOKEN handling.
    if (!authToken) {
      logger.warn(
        { path: req.path },
        "DROPLET_MATTER_SERVICE_TOKEN is empty — rejecting (fail-closed)",
      );
      return res.status(401).json({
        error: "service token not configured",
        errorClass: "AuthError",
        errorMessage: "service token not configured",
      } satisfies SidecarErrorBody);
    }
    const got = req.header("X-Droplet-Auth") ?? "";
    if (!constantTimeMatch(authToken, got)) {
      return res.status(401).json({
        error: "unauthorized",
        errorClass: "AuthError",
        errorMessage: "unauthorized",
      } satisfies SidecarErrorBody);
    }
    next();
  });

  // --- Capabilities (answers before/without controller init — the
  // dashboard wizard needs the BLE answer while the controller may
  // still be booting; same contract as WARP-851's orchestrator route).
  // WARP-1035: additive fields only — never rename bleCommissioning;
  // its shape is pinned by WARP-851 tests here, in the orchestrator
  // service, and in the dashboard api client. ---
  app.get("/capabilities", async (_req, res) => {
    // Request-time resolution (file > env) — same helper the commission
    // path uses, so this answer can never drift from real behaviour.
    // WARP-1363: apSsid resolves file-first too, so a renamed AP is
    // reported (and provisioned) correctly with no sidecar restart.
    const wifiNetwork = await resolveWifiNetwork(wifiOptions);
    res.json({
      bleCommissioning: capabilities.bleCommissioning,
      reason: capabilities.reason,
      wifiProvisioning: wifiNetwork !== undefined,
      apSsid: (await resolveWifiSsid(wifiOptions)) || null,
    });
  });

  /** 503 guard shared by every controller-backed route. */
  function requireInitialized(res: Response): boolean {
    if (!core.isInitialized()) {
      res.status(503).json({
        error: "Matter controller not initialized",
        errorClass: "ControllerNotInitializedError",
        errorMessage: "Matter controller not initialized",
      } satisfies SidecarErrorBody);
      return false;
    }
    return true;
  }

  function validNodeIdOr400(req: Request, res: Response): boolean {
    if (!isValidNodeId(req.params.nodeId)) {
      res.status(400).json({
        error: "Invalid node ID format",
        errorClass: "ValidationError",
        errorMessage: "Invalid node ID format",
      } satisfies SidecarErrorBody);
      return false;
    }
    return true;
  }

  app.get("/devices", async (_req, res) => {
    if (!requireInitialized(res)) return;
    try {
      res.json(await core.listDevices());
    } catch (err) {
      res.status(500).json(errorBody(err));
    }
  });

  app.get("/discover", async (req, res) => {
    if (!requireInitialized(res)) return;
    try {
      const raw = req.query.timeout
        ? parseInt(req.query.timeout as string, 10)
        : 15_000;
      // Same clamp as the orchestrator route: 5s ≤ timeout ≤ 60s.
      const timeout = Math.min(Math.max(raw || 15_000, 5_000), 60_000);
      const devices = await core.discover(timeout);
      res.json({ devices, count: devices.length });
    } catch (err) {
      res.status(500).json(errorBody(err));
    }
  });

  app.post("/commission", async (req, res) => {
    if (!requireInitialized(res)) return;
    const { pairing_code: pairingCode } = req.body ?? {};
    if (!pairingCode || typeof pairingCode !== "string") {
      return res.status(400).json({
        error: "Missing 'pairing_code' in request body",
        errorClass: "ValidationError",
        errorMessage: "Missing 'pairing_code' in request body",
      } satisfies SidecarErrorBody);
    }
    try {
      res.json(await core.commission(pairingCode));
    } catch (err) {
      // Raw pass-through — translateCommissionError lives in the
      // orchestrator and operates on errorMessage/errorClass.
      res.status(500).json(errorBody(err));
    }
  });

  app.get("/devices/:nodeId", async (req, res) => {
    if (!requireInitialized(res)) return;
    if (!validNodeIdOr400(req, res)) return;
    try {
      const device = await core.getDevice(req.params.nodeId);
      if (!device) {
        return res.status(404).json({
          error: "Device not found",
          errorClass: "NotFoundError",
          errorMessage: "Device not found",
        } satisfies SidecarErrorBody);
      }
      res.json(device);
    } catch (err) {
      res.status(500).json(errorBody(err));
    }
  });

  app.post("/devices/:nodeId/command", async (req, res) => {
    if (!requireInitialized(res)) return;
    if (!validNodeIdOr400(req, res)) return;
    const { command, data } = req.body ?? {};
    if (!command || typeof command !== "string") {
      return res.status(400).json({
        error: "Missing 'command' in request body",
        errorClass: "ValidationError",
        errorMessage: "Missing 'command' in request body",
      } satisfies SidecarErrorBody);
    }
    try {
      res.json(await core.sendCommand(req.params.nodeId, command, data));
    } catch (err) {
      res.status(500).json(errorBody(err));
    }
  });

  // WARP-1469: nudge a still-paired but offline device to reconnect now
  // instead of waiting for matter.js's ~10-min WaitingForDeviceDiscovery
  // re-probe. Non-blocking on the controller side — success/failure of the
  // actual reconnection arrives later over the /events SSE stream.
  app.post("/devices/:nodeId/reconnect", async (req, res) => {
    if (!requireInitialized(res)) return;
    if (!validNodeIdOr400(req, res)) return;
    try {
      const found = await core.reconnect(req.params.nodeId);
      if (!found) {
        // Same contract as GET/DELETE /devices/:nodeId — an
        // uncommissioned node is a 404, not an internal error.
        return res.status(404).json({
          error: "Device not found",
          errorClass: "NotFoundError",
          errorMessage: "Device not found",
        } satisfies SidecarErrorBody);
      }
      res.json({ status: "reconnecting", nodeId: req.params.nodeId });
    } catch (err) {
      res.status(500).json(errorBody(err));
    }
  });

  app.delete("/devices/:nodeId", async (req, res) => {
    if (!requireInitialized(res)) return;
    if (!validNodeIdOr400(req, res)) return;
    try {
      const removed = await core.decommission(req.params.nodeId);
      if (!removed) {
        // Same contract as GET /devices/:nodeId — an uncommissioned
        // node is a 404 condition, not an internal error.
        return res.status(404).json({
          error: "Device not found",
          errorClass: "NotFoundError",
          errorMessage: "Device not found",
        } satisfies SidecarErrorBody);
      }
      res.json({ status: "decommissioned", nodeId: req.params.nodeId });
    } catch (err) {
      res.status(500).json(errorBody(err));
    }
  });

  // --- SSE event fan-out. The orchestrator's matter.service.ts keeps
  // one long-lived consumer of this stream and re-emits into its local
  // EventEmitter, so the orchestrator's own /api/matter/devices/events
  // SSE route (dashboard-facing) is unchanged by the extraction. ---
  app.get("/events", (req, res) => {
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    });

    res.write(`data: ${JSON.stringify({ type: "connected" })}\n\n`);

    const heartbeat = setInterval(() => {
      res.write(`: heartbeat\n\n`);
    }, 30_000);
    // Don't let the heartbeat timer hold the process open in tests /
    // shutdown — the socket close handler clears it anyway.
    heartbeat.unref?.();

    const onState = (event: unknown) => {
      try {
        res.write(
          `data: ${JSON.stringify({ type: "state_changed", ...(event as object) })}\n\n`,
        );
      } catch {
        // Client may have disconnected
      }
    };
    const onConnection = (event: unknown) => {
      try {
        res.write(
          `data: ${JSON.stringify({ type: "connection_changed", ...(event as object) })}\n\n`,
        );
      } catch {
        // Client may have disconnected
      }
    };

    core.events.on("state_changed", onState);
    core.events.on("connection_changed", onConnection);

    req.on("close", () => {
      clearInterval(heartbeat);
      core.events.off("state_changed", onState);
      core.events.off("connection_changed", onConnection);
    });
  });

  return app;
}
