"""Encrypted API key storage using device-unique key.

Each device gets a unique DEVICE_SECRET (generated by setup.sh) and a unique
random salt (created on first use, stored in the keys volume). Together with
PBKDF2-HMAC-SHA256 (480,000 iterations per OWASP 2023), this ensures that
compromising one device reveals nothing about any other device's keys.
"""

from __future__ import annotations

import os
import base64
import logging
import re
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

logger = logging.getLogger(__name__)

KEYS_DIR = Path(os.getenv("KEYS_DIR", "/data/keys"))

# The literal fallback used when DEVICE_SECRET is unset. Every device that
# boots without setup.sh's per-device secret would otherwise derive its Fernet
# key from this single public string — i.e. encrypt its cloud BYOK keys under a
# key whose entropy is zero and known to anyone with the source. We keep the
# constant named so we can detect when it's active and refuse to ship with it.
_DEV_DEFAULT_SECRET = "dev-secret-change-in-production"
DEVICE_SECRET = os.getenv("DEVICE_SECRET", _DEV_DEFAULT_SECRET)


def _is_production() -> bool:
    """Whether we're running in a non-dev deployment.

    Mirrors the FIPS boot self-test gating in main.py (DROPLET_FIPS_REQUIRED):
    an explicit production signal opts into fail-closed behaviour, while dev/CI
    (no signal) stays permissive so the local default keeps working. We treat
    either ``DROPLET_ENV in {production, prod}`` or ``DROPLET_FIPS_REQUIRED``
    being truthy as "this is a shipping box".
    """
    env = (os.getenv("DROPLET_ENV") or "").strip().lower()
    if env in ("production", "prod"):
        return True
    fips = (os.getenv("DROPLET_FIPS_REQUIRED") or "").strip().lower()
    return fips in ("true", "1", "yes")


def _assert_device_secret_safe() -> None:
    """Refuse to use the public dev default for real key material.

    Fail-closed in production (raise at import, before the app serves a
    request — same posture as the FIPS self-test). In dev/CI, log an ERROR so
    the weak default is at least visible. A device that encrypts BYOK keys
    under the dev default and later receives a real DEVICE_SECRET silently
    loses every stored key (InvalidToken → None), so surfacing this early is
    the cheapest way to avoid a baffling "key not configured" later.
    """
    if DEVICE_SECRET and DEVICE_SECRET != _DEV_DEFAULT_SECRET:
        return  # a real per-device secret is in use — nothing to warn about
    if _is_production():
        raise RuntimeError(
            "DEVICE_SECRET is unset or equal to the public dev default in a "
            "production deployment. BYOK keys would be encrypted under a known "
            "key. Set a per-device DEVICE_SECRET (setup.sh generates one) "
            "before booting. Refusing to start."
        )
    # CodeQL py/clear-text-logging-sensitive-data (rule 19): the dev default
    # is a public constant, but a log line that says "DEVICE_SECRET" must never
    # be followed by a secret-shaped value — name the constant, not its contents.
    logger.error(
        "DEVICE_SECRET is unset or equal to the public dev default "
        "(keystore._DEV_DEFAULT_SECRET). BYOK API keys will be encrypted under "
        "a known, zero-entropy key — acceptable only for dev/test. Set a "
        "per-device DEVICE_SECRET for any real deployment."
    )


_assert_device_secret_safe()

_SALT_FILE = KEYS_DIR / ".salt"
_KDF_ITERATIONS = 480_000  # OWASP 2023 recommendation for PBKDF2-HMAC-SHA256

# WARP-561: per-user BYOK namespacing. Keys are stored under
# `{user_id}/{provider}.enc` so one household member's cloud key is never
# readable by another. `user_id is None` is the SHARED/device namespace
# (`_shared/{provider}.enc`) — used by server-side callers that have no
# per-request identity (model listing, gRPC EmbedText, router reload). The
# segment is sanitised so a hostile id can never escape KEYS_DIR via
# traversal or absolute paths.
_SHARED_NAMESPACE = "_shared"


def _user_namespace(user_id: str | None) -> str:
    """Map a caller identity to a filesystem-safe key namespace.

    None / blank → the shared device namespace. Otherwise the id is reduced
    to a conservative `[A-Za-z0-9._-]` token (collapsing anything else to
    `_`) so it can never contain a path separator, `..`, or a drive/root
    prefix. This is the only place a user id touches the path.
    """
    if not user_id or not user_id.strip():
        return _SHARED_NAMESPACE
    safe = "".join(c if (c.isalnum() or c in "._-") else "_" for c in user_id.strip())
    # A token of only dots ("." / "..") would still be a traversal token.
    if not safe or set(safe) <= {"."}:
        return _SHARED_NAMESPACE
    return safe


# CodeQL py/path-injection: `provider` arrives straight from the URL
# (`/ai/keys/{provider}`) and from `ChatRequest.provider`; only `user_id` was
# sanitised, so `../x` or an absolute segment could have read, written or
# unlinked an `.enc` outside the namespace. A bad provider is REJECTED rather
# than collapsed the way `_user_namespace` does — silently remapping the name
# would store a key the caller can never find again under the name they used.
_PROVIDER_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def _is_valid_provider(provider: object) -> bool:
    """Whether `provider` is a plain token that can name a key file."""
    return isinstance(provider, str) and _PROVIDER_RE.match(provider) is not None


def _key_path(provider: str, user_id: str | None) -> Path:
    """Return the on-disk path for a provider key in a user's namespace.

    Raises ValueError for a provider name that is not a plain token.
    """
    if not _is_valid_provider(provider):
        raise ValueError(f"invalid provider name: {provider!r}")
    base = os.path.abspath(KEYS_DIR)
    candidate = os.path.normpath(
        os.path.join(base, _user_namespace(user_id), f"{provider}.enc")
    )
    # Belt-and-braces containment check on the normalised path — the
    # documented py/path-injection barrier. Both segments are already
    # token-only, so this only fires if a future caller regresses that.
    if not candidate.startswith(base + os.sep):
        raise ValueError(f"invalid key path for provider {provider!r}")
    return Path(candidate)


def _get_or_create_salt() -> bytes:
    """Return the per-device salt, creating it on first use.

    The salt is stored in the Docker volume (aikeys) so it persists across
    container restarts but is unique to each physical device.
    """
    if _SALT_FILE.exists():
        return _SALT_FILE.read_bytes()
    salt = os.urandom(16)
    KEYS_DIR.mkdir(parents=True, exist_ok=True)
    _SALT_FILE.write_bytes(salt)
    try:
        os.chmod(_SALT_FILE, 0o600)
    except OSError:
        pass  # May fail in some container runtimes; non-critical
    logger.info("Generated new device-unique salt")
    return salt


def _get_fernet() -> Fernet:
    """Derive a Fernet key from the device secret using PBKDF2."""
    salt = _get_or_create_salt()
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=_KDF_ITERATIONS,
    )
    key = base64.urlsafe_b64encode(kdf.derive(DEVICE_SECRET.encode()))
    return Fernet(key)


async def store_key(provider: str, api_key: str, user_id: str | None = None) -> None:
    """Encrypt and store an API key for a provider in the caller's namespace."""
    key_path = _key_path(provider, user_id)
    key_path.parent.mkdir(parents=True, exist_ok=True)
    fernet = _get_fernet()
    encrypted = fernet.encrypt(api_key.encode())
    key_path.write_bytes(encrypted)
    logger.info("Stored API key for provider: %s (namespace: %s)", provider, key_path.parent.name)


async def get_key(provider: str, user_id: str | None = None) -> str | None:
    """Retrieve and decrypt an API key for a provider in the caller's namespace."""
    if not _is_valid_provider(provider):
        return None  # a name that can't be a key file has no key
    key_path = _key_path(provider, user_id)
    if not key_path.exists():
        return None

    try:
        fernet = _get_fernet()
        encrypted = key_path.read_bytes()
        return fernet.decrypt(encrypted).decode()
    except InvalidToken:
        logger.error("Failed to decrypt key for %s — possible secret mismatch", provider)
        return None


async def delete_key(provider: str, user_id: str | None = None) -> bool:
    """Remove a stored API key from the caller's namespace."""
    if not _is_valid_provider(provider):
        return False  # nothing can be stored under a non-token name
    key_path = _key_path(provider, user_id)
    if key_path.exists():
        key_path.unlink()
        logger.info("Deleted API key for provider: %s (namespace: %s)", provider, key_path.parent.name)
        return True
    return False


async def list_providers_with_keys(user_id: str | None = None) -> list[str]:
    """Return provider names that have stored keys in the caller's namespace."""
    ns_dir = KEYS_DIR / _user_namespace(user_id)
    if not ns_dir.exists():
        return []
    return [p.stem for p in ns_dir.glob("*.enc")]
