"""Encrypted API key storage using device-unique key.

Each device gets a unique DEVICE_SECRET (generated by setup.sh) and a unique
random salt (created on first use, stored in the keys volume). Together with
PBKDF2-HMAC-SHA256 (480,000 iterations per OWASP 2023), this ensures that
compromising one device reveals nothing about any other device's keys.
"""

from __future__ import annotations

import os
import base64
import logging
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

logger = logging.getLogger(__name__)

KEYS_DIR = Path(os.getenv("KEYS_DIR", "/data/keys"))

# The literal fallback used when DEVICE_SECRET is unset. Every device that
# boots without setup.sh's per-device secret would otherwise derive its Fernet
# key from this single public string — i.e. encrypt its cloud BYOK keys under a
# key whose entropy is zero and known to anyone with the source. We keep the
# constant named so we can detect when it's active and refuse to ship with it.
_DEV_DEFAULT_SECRET = "dev-secret-change-in-production"
DEVICE_SECRET = os.getenv("DEVICE_SECRET", _DEV_DEFAULT_SECRET)


def _is_production() -> bool:
    """Whether we're running in a non-dev deployment.

    Mirrors the FIPS boot self-test gating in main.py (DROPLET_FIPS_REQUIRED):
    an explicit production signal opts into fail-closed behaviour, while dev/CI
    (no signal) stays permissive so the local default keeps working. We treat
    either ``DROPLET_ENV in {production, prod}`` or ``DROPLET_FIPS_REQUIRED``
    being truthy as "this is a shipping box".
    """
    env = (os.getenv("DROPLET_ENV") or "").strip().lower()
    if env in ("production", "prod"):
        return True
    fips = (os.getenv("DROPLET_FIPS_REQUIRED") or "").strip().lower()
    return fips in ("true", "1", "yes")


def _assert_device_secret_safe() -> None:
    """Refuse to use the public dev default for real key material.

    Fail-closed in production (raise at import, before the app serves a
    request — same posture as the FIPS self-test). In dev/CI, log an ERROR so
    the weak default is at least visible. A device that encrypts BYOK keys
    under the dev default and later receives a real DEVICE_SECRET silently
    loses every stored key (InvalidToken → None), so surfacing this early is
    the cheapest way to avoid a baffling "key not configured" later.
    """
    if DEVICE_SECRET and DEVICE_SECRET != _DEV_DEFAULT_SECRET:
        return  # a real per-device secret is in use — nothing to warn about
    if _is_production():
        raise RuntimeError(
            "DEVICE_SECRET is unset or equal to the public dev default in a "
            "production deployment. BYOK keys would be encrypted under a known "
            "key. Set a per-device DEVICE_SECRET (setup.sh generates one) "
            "before booting. Refusing to start."
        )
    logger.error(
        "DEVICE_SECRET is unset or equal to the public dev default "
        "(%r). BYOK API keys will be encrypted under a known, zero-entropy "
        "key — acceptable only for dev/test. Set a per-device DEVICE_SECRET "
        "for any real deployment.",
        _DEV_DEFAULT_SECRET,
    )


_assert_device_secret_safe()

_SALT_FILE = KEYS_DIR / ".salt"
_KDF_ITERATIONS = 480_000  # OWASP 2023 recommendation for PBKDF2-HMAC-SHA256


def _get_or_create_salt() -> bytes:
    """Return the per-device salt, creating it on first use.

    The salt is stored in the Docker volume (aikeys) so it persists across
    container restarts but is unique to each physical device.
    """
    if _SALT_FILE.exists():
        return _SALT_FILE.read_bytes()
    salt = os.urandom(16)
    KEYS_DIR.mkdir(parents=True, exist_ok=True)
    _SALT_FILE.write_bytes(salt)
    try:
        os.chmod(_SALT_FILE, 0o600)
    except OSError:
        pass  # May fail in some container runtimes; non-critical
    logger.info("Generated new device-unique salt")
    return salt


def _get_fernet() -> Fernet:
    """Derive a Fernet key from the device secret using PBKDF2."""
    salt = _get_or_create_salt()
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=_KDF_ITERATIONS,
    )
    key = base64.urlsafe_b64encode(kdf.derive(DEVICE_SECRET.encode()))
    return Fernet(key)


async def store_key(provider: str, api_key: str) -> None:
    """Encrypt and store an API key for a provider."""
    KEYS_DIR.mkdir(parents=True, exist_ok=True)
    fernet = _get_fernet()
    encrypted = fernet.encrypt(api_key.encode())
    key_path = KEYS_DIR / f"{provider}.enc"
    key_path.write_bytes(encrypted)
    logger.info("Stored API key for provider: %s", provider)


async def get_key(provider: str) -> str | None:
    """Retrieve and decrypt an API key for a provider."""
    key_path = KEYS_DIR / f"{provider}.enc"
    if not key_path.exists():
        return None

    try:
        fernet = _get_fernet()
        encrypted = key_path.read_bytes()
        return fernet.decrypt(encrypted).decode()
    except InvalidToken:
        logger.error("Failed to decrypt key for %s — possible secret mismatch", provider)
        return None


async def delete_key(provider: str) -> bool:
    """Remove a stored API key."""
    key_path = KEYS_DIR / f"{provider}.enc"
    if key_path.exists():
        key_path.unlink()
        logger.info("Deleted API key for provider: %s", provider)
        return True
    return False


async def list_providers_with_keys() -> list[str]:
    """Return provider names that have stored keys."""
    if not KEYS_DIR.exists():
        return []
    return [p.stem for p in KEYS_DIR.glob("*.enc")]
