-- =============================================================================
-- WARP-1094 — Eaglesoft provisioning script (brief §8.1)
-- =============================================================================
--
-- Run ONCE during onboarding, by the office's SQL Anywhere DBA, against the
-- PattersonPM database. REVIEW BEFORE RUNNING. This creates the two dedicated,
-- least-privilege accounts Droplet uses; it NEVER references Eaglesoft's
-- historically hardcoded default credential (brief §4.3 — that account is
-- insecure, unauditable, and over-privileged).
--
--   droplet_ro  — SELECT-only, the default; used for ALL reads.
--   droplet_rw  — created but LEFT UNUSABLE (no grants) until a practice opts
--                 in to a specific write capability (invariant 1 & 2).
--
-- Passwords are generated by Droplet (strong, unique per box) and pasted by
-- the DBA from Droplet's onboarding screen — they never travel through Droplet
-- in cleartext logs and are stored only via a secret_ref pointer (brief §7.4).
-- Replace the two placeholders below with the generated values.
--
-- The exact SELECT grant list is finalized from the introspection pass (§9);
-- prefer granting on READ VIEWS (§10.1) when the DBA allows creating them.

-- 1) Read-only service account (the default; used for all reads) ------------
CREATE USER droplet_ro IDENTIFIED BY '<GENERATED_RO_PASSWORD>';

-- SELECT ONLY on the specific tables the product reads (least-necessary).
-- Reference objects as dba.<table> unless introspection says otherwise (§3).
GRANT SELECT ON dba.patient     TO droplet_ro;
GRANT SELECT ON dba.appointment TO droplet_ro;
GRANT SELECT ON dba.provider    TO droplet_ro;
GRANT SELECT ON dba.service     TO droplet_ro;
GRANT SELECT ON dba.serv_trans  TO droplet_ro;   -- read-only ledger service lines
GRANT SELECT ON dba.recall      TO droplet_ro;
GRANT SELECT ON dba.account     TO droplet_ro;   -- AR read only (high-risk; never writable)

-- 2) Write account — CREATED but LEFT UNUSABLE until a practice opts in ------
-- No grants at creation (invariant 1 & 2). Each write capability adds exactly
-- the INSERT/UPDATE it needs, column-scoped, e.g. the reschedule_appointment
-- command needs ONLY:
--
--   GRANT UPDATE (appt_time, provider_id, operatory_id, status) ON dba.appointment TO droplet_rw;
--
-- NEVER grant: DELETE, DDL, the dba role, or ANY grant on ledger / clinical /
-- claim tables (account, serv_trans, insurance claims, clinical notes/exam/
-- perio/tx-plan). Those stay read-only in v1 (invariant 5, brief §11.2).
CREATE USER droplet_rw IDENTIFIED BY '<GENERATED_RW_PASSWORD>';
-- (intentionally no grants here — capabilities are granted per opt-in)
