#!/usr/bin/env node
/**
 * Generate `catalog.json` for the client-app download surface.
 *
 * This is the generator half of the contract whose parser lives in
 * `apps/orchestrator/src/services/app-downloads/catalog.ts` — the two
 * change together, and the schema version below must match that module's
 * SUPPORTED_CATALOG_SCHEMA_VERSION.
 *
 * It walks the staging directory, hashes every file it finds, and writes
 * a catalog pinning each asset's size + sha256. The orchestrator re-hashes
 * against those pins on every download and refuses to serve on mismatch,
 * so running this is what makes an artifact servable at all.
 *
 * USAGE
 *   node scripts/app-downloads/gen-catalog.mjs [--dir data/app-downloads] [--check]
 *
 *   --dir <path>   staging root (default: data/app-downloads)
 *   --check        do not write; exit non-zero if the on-disk catalog
 *                  disagrees with what would be generated. This is the
 *                  CI/image-build guard against a stale catalog shipping
 *                  next to swapped binaries.
 *   --require-installer
 *                  exit non-zero unless at least one platform can actually
 *                  give a customer something. On its own `--check` passes
 *                  VACUOUSLY over an empty staging root — a catalog with
 *                  zero platforms matches itself perfectly — which is the
 *                  shape that let an empty /downloads page ship green.
 *                  Composable with or without --check.
 *
 * LAYOUT the staging root is expected to have:
 *
 *   data/app-downloads/
 *     platforms.json            ← hand-authored: version + store URLs
 *     catalog.json              ← GENERATED by this script
 *     windows/
 *       Droplet_0.2.0_x64-setup.exe
 *       Droplet_0.2.0_x64-setup.exe.sig     (Tauri minisign, optional)
 *       latest.json                          (Tauri updater, optional)
 *     android/  ios/  macos/  linux/         (same idea, all optional)
 *
 * `platforms.json` is the only hand-edited file. Everything derivable
 * from the bytes on disk — sizes, digests, which asset is the installer —
 * is derived, because a hand-maintained digest is a digest that will
 * eventually be wrong.
 */
import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

/** Must match SUPPORTED_CATALOG_SCHEMA_VERSION in the parser. */
const SCHEMA_VERSION = 1;

const PLATFORMS = ["windows", "macos", "linux", "android", "ios"];

/**
 * Extension → asset kind. Anything unrecognised is skipped with a
 * warning rather than guessed at: a mystery file in the staging dir is a
 * staging mistake, and silently declaring it an installer would put a
 * broken button on a customer's screen.
 */
const INSTALLER_EXTENSIONS = new Set([
  ".exe",
  ".msi",
  ".apk",
  ".dmg",
  ".pkg",
  ".appimage",
  ".deb",
  ".rpm",
  ".ipa",
]);

/** Content types worth being explicit about; the rest default to
 *  application/octet-stream on the serving side. */
const CONTENT_TYPES = {
  ".exe": "application/vnd.microsoft.portable-executable",
  ".msi": "application/x-msi",
  ".apk": "application/vnd.android.package-archive",
  ".dmg": "application/x-apple-diskimage",
  ".deb": "application/vnd.debian.binary-package",
  ".rpm": "application/x-rpm",
  ".json": "application/json",
  ".sig": "application/pgp-signature",
};

function parseArgs(argv) {
  const args = { dir: "data/app-downloads", check: false, requireInstaller: false };
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--check") args.check = true;
    else if (arg === "--require-installer") args.requireInstaller = true;
    else if (arg === "--dir") {
      i += 1;
      if (!argv[i]) fail("--dir needs a path");
      args.dir = argv[i];
    } else fail(`unknown argument: ${arg}`);
  }
  return args;
}

function fail(message) {
  process.stderr.write(`gen-catalog: ${message}\n`);
  process.exit(2);
}

function warn(message) {
  process.stderr.write(`gen-catalog: warning: ${message}\n`);
}

async function sha256File(filePath) {
  return new Promise((resolve, reject) => {
    const hash = createHash("sha256");
    const stream = createReadStream(filePath);
    stream.on("error", reject);
    stream.on("data", (chunk) => hash.update(chunk));
    stream.on("end", () => resolve(hash.digest("hex")));
  });
}

/**
 * Classify one staged file.
 *
 * `latest.json` is the Tauri updater manifest, NOT an installer — it must
 * be declared so the installed client can self-update against the box,
 * but it must never become a platform's `primary` or the download button
 * would hand a customer a 2 KB JSON file.
 */
function classify(name) {
  const lower = name.toLowerCase();
  const ext = path.extname(lower);

  if (lower === "latest.json") return { kind: "manifest" };
  if (ext === ".sig") {
    // "Droplet_0.2.0_x64-setup.exe.sig" signs "Droplet_0.2.0_x64-setup.exe"
    return { kind: "signature", signs: name.slice(0, -4) };
  }
  if (INSTALLER_EXTENSIONS.has(ext)) return { kind: "installer" };
  return null;
}

async function collectPlatform(root, platform) {
  const dir = path.join(root, platform);
  let names;
  try {
    names = await readdir(dir);
  } catch (err) {
    if (err.code === "ENOENT") return null; // platform not staged
    throw err;
  }

  const assets = [];
  for (const name of names.sort()) {
    const filePath = path.join(dir, name);
    const stats = await stat(filePath);
    if (!stats.isFile()) continue;

    const classified = classify(name);
    if (!classified) {
      warn(`${platform}/${name}: unrecognised file type, skipped`);
      continue;
    }

    const asset = {
      name,
      kind: classified.kind,
      size: stats.size,
      sha256: await sha256File(filePath),
    };
    const contentType = CONTENT_TYPES[path.extname(name.toLowerCase())];
    if (contentType) asset.contentType = contentType;
    if (classified.signs) {
      asset.signs = classified.signs;
      // The only signature scheme in play today is the Tauri updater's
      // minisign envelope. Recorded for display; the box never verifies
      // it (Ed25519 is FIPS-forbidden on-box without a registered
      // exception) — it is served so the CLIENT and the customer can.
      asset.signatureAlgorithm = "minisign-ed25519";
    }
    assets.push(asset);
  }

  // A signature whose installer isn't staged is dangling metadata the
  // parser will reject — drop it here with a warning instead of writing
  // a catalog that cannot load.
  const present = new Set(assets.map((a) => a.name));
  const kept = assets.filter((asset) => {
    if (asset.kind === "signature" && !present.has(asset.signs)) {
      warn(
        `${platform}/${asset.name}: signs "${asset.signs}", which is not staged — dropped`,
      );
      return false;
    }
    return true;
  });

  return kept;
}

/**
 * Pick the platform's primary installer.
 *
 * Where a platform ships more than one installer format, prefer the one
 * a human should actually run. On Windows that is the NSIS `-setup.exe`:
 * it overwrites a same-version install cleanly, which the MSI does not.
 */
function pickPrimary(platform, assets) {
  const installers = assets.filter((a) => a.kind === "installer");
  if (installers.length === 0) return undefined;
  if (installers.length === 1) return installers[0].name;

  if (platform === "windows") {
    const nsis = installers.find((a) =>
      a.name.toLowerCase().endsWith("-setup.exe"),
    );
    if (nsis) return nsis.name;
  }
  // Deterministic fallback so repeated runs don't churn the catalog.
  return installers.map((a) => a.name).sort()[0];
}

async function main() {
  const args = parseArgs(process.argv);
  const root = path.resolve(process.cwd(), args.dir);

  // Hand-authored side of the contract: versions + store URLs, which
  // cannot be derived from the bytes.
  let meta = {};
  try {
    meta = JSON.parse(await readFile(path.join(root, "platforms.json"), "utf8"));
  } catch (err) {
    if (err.code !== "ENOENT") fail(`cannot read platforms.json: ${err.message}`);
    warn("no platforms.json — every staged platform will need one for its version");
  }

  const platforms = [];
  for (const platform of PLATFORMS) {
    const assets = await collectPlatform(root, platform);
    const declared = meta[platform];

    // Nothing staged AND nothing declared → the platform simply isn't in
    // the catalog, and the page says "not staged" rather than inventing
    // a coming-soon promise.
    if (assets === null && !declared) continue;

    const entry = { platform, version: declared?.version ?? "0.0.0", assets: assets ?? [] };

    if (!declared?.version) {
      warn(`${platform}: no version in platforms.json, using 0.0.0`);
    }
    if (declared?.storeUrl) entry.storeUrl = declared.storeUrl;
    if (declared?.note) entry.note = declared.note;
    if (declared?.minOsVersion) entry.minOsVersion = declared.minOsVersion;
    if (declared?.releasedAt) entry.releasedAt = declared.releasedAt;

    const primary = pickPrimary(platform, entry.assets);
    if (primary) entry.primary = primary;

    platforms.push(entry);
  }

  const catalog = {
    schemaVersion: SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    platforms,
  };

  const catalogPath = path.join(root, "catalog.json");
  const serialized = `${JSON.stringify(catalog, null, 2)}\n`;

  // Deliberately BEFORE the --check comparison. `--check` only asks "does the
  // catalog match the bytes", and an empty staging root satisfies that
  // perfectly — nothing on disk, nothing declared, no disagreement. That
  // vacuous pass is what let boxes ship an empty page with a green gate, so
  // callers that mean "this release must be able to give a customer
  // something" pass --require-installer and get told the truth.
  if (args.requireInstaller) {
    const usable = platforms.filter((p) => p.primary || p.storeUrl);
    if (usable.length === 0) {
      fail(
        "--require-installer: no platform has an installer or a store URL — " +
          "this catalog cannot give a customer anything. Stage an artifact " +
          "(scripts/app-downloads/stage.sh) or declare a storeUrl in platforms.json.",
      );
    }
    process.stdout.write(
      `gen-catalog: ${usable.length} platform(s) can serve something — ${usable
        .map((p) => `${p.platform}:${p.primary ? "installer" : "store"}`)
        .join(", ")}\n`,
    );
  }

  if (args.check) {
    let existing;
    try {
      existing = await readFile(catalogPath, "utf8");
    } catch {
      fail(`--check: no catalog.json at ${catalogPath} — run without --check first`);
    }
    // `generatedAt` is a timestamp and would differ on every run, so the
    // comparison deliberately ignores it: what must not drift is the set
    // of assets and their digests.
    const strip = (text) => {
      const parsed = JSON.parse(text);
      delete parsed.generatedAt;
      return JSON.stringify(parsed);
    };
    if (strip(existing) !== strip(serialized)) {
      fail(
        "--check: catalog.json is stale — the staged artifacts do not match it. Re-run without --check.",
      );
    }
    process.stdout.write("gen-catalog: catalog.json is current\n");
    return;
  }

  await writeFile(catalogPath, serialized, "utf8");
  const assetCount = platforms.reduce((n, p) => n + p.assets.length, 0);
  process.stdout.write(
    `gen-catalog: wrote ${catalogPath} — ${platforms.length} platform(s), ${assetCount} asset(s)\n`,
  );
}

main().catch((err) => fail(err instanceof Error ? err.message : String(err)));
