/**
 * WARP-197 — end-to-end audio extraction (live integration).
 *
 * Boots the same Compose subset the WARP-203 brain-upload integration
 * test uses (db, cache, broker, ai-gateway, orchestrator, file-indexer),
 * uploads a real WAV file at `POST /api/files/brain/upload`, then polls
 * the database until the file-indexer has run faster-whisper end-to-end
 * and produced at least one `FileContentChunk` row tied to the
 * BrainMemoryItem.
 *
 * Skip-gated by `RUN_RAG_INTEGRATION=1` so unit-only runs stay fast.
 *
 * Why we don't assert specific transcript content:
 *   The fixture is generated by macOS `say`. On CI/Linux runners the
 *   fixture may be a Python-generated tone instead. What we care about
 *   here is that the pipeline RAN — bytes upload, MQTT broadcast,
 *   file-indexer transcribes, chunk rows materialize. Phrase-content
 *   assertions belong in QA's manual smoke once we have a
 *   speech-cloned fixture committed to the repo.
 *
 * Run locally:
 *   docker compose -f docker/docker-compose.yml up -d \
 *     db cache broker ai-gateway orchestrator file-indexer
 *   API_URL=http://localhost:3000 RUN_RAG_INTEGRATION=1 \
 *     npx vitest run tests/rag-audio.integration.test.ts
 */

import { describe, it, expect, beforeAll } from "vitest";
import { execSync } from "node:child_process";
import fs from "node:fs";
import { resolve } from "node:path";
import { COMPOSE } from "./helpers/rag-retrieval";

const REPO_ROOT = resolve(__dirname, "..");
const SHOULD_RUN = process.env.RUN_RAG_INTEGRATION === "1";
const API_URL = process.env.API_URL ?? "http://localhost:3000";
const FIXTURE = resolve(
  REPO_ROOT,
  "services/file-indexer/tests/fixtures/sample.wav",
);

function sh(cmd: string): string {
  return execSync(cmd, { encoding: "utf8" }).trim();
}

function shSilent(cmd: string): string {
  return execSync(cmd, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
}

function dbQuery(sql: string): string {
  // Multi-line SQL doesn't survive JSON.stringify → bash double-quote
  // (newlines become literal \n that psql parses as syntax). Flatten
  // any whitespace runs to single spaces. WARP-227.
  const flat = sql.replace(/\s+/g, " ").trim();
  return shSilent(
    `${COMPOSE} exec -T db psql -U droplet -d droplet -t -A -c ${JSON.stringify(flat)}`,
  );
}

async function pollChunks(
  brainItemId: string,
  timeoutMs = 180_000,
): Promise<number> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const out = dbQuery(
      `SELECT count(*) FROM "FileContentChunk"
       WHERE "brainItemId" = '${brainItemId}' AND "source" = 'brain'`,
    );
    const n = parseInt(out || "0", 10);
    if (Number.isFinite(n) && n > 0) return n;
    await new Promise((r) => setTimeout(r, 2_000));
  }
  return 0;
}

async function pollIndexedAt(
  brainItemId: string,
  timeoutMs = 180_000,
): Promise<string> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const out = dbQuery(
      `SELECT "indexedAt" FROM "BrainMemoryItem" WHERE "id" = '${brainItemId}'`,
    );
    if (out && out !== "") return out;
    await new Promise((r) => setTimeout(r, 2_000));
  }
  return "";
}

describe.skipIf(!SHOULD_RUN)(
  "RAG audio extraction — live integration (WARP-197)",
  () => {
    beforeAll(() => {
      sh(
        `${COMPOSE} up -d db cache broker ai-gateway orchestrator file-indexer`,
      );
      const deadline = Date.now() + 60_000;
      while (Date.now() < deadline) {
        try {
          dbQuery("SELECT 1");
          break;
        } catch {
          execSync("sleep 1");
        }
      }
    }, 180_000);

    it("transcribes an uploaded WAV and produces FileContentChunk rows", async () => {
      const wavBytes = fs.readFileSync(FIXTURE);
      const form = new FormData();
      form.append(
        "file",
        new Blob([wavBytes], { type: "audio/wav" }),
        "memo.wav",
      );

      const res = await fetch(`${API_URL}/api/files/brain/upload`, {
        method: "POST",
        body: form,
      });
      expect(res.status).toBe(202);
      const data = (await res.json()) as { itemId: string; status: string };
      expect(data.status).toBe("indexing");
      expect(data.itemId).toBeTruthy();

      // Cold faster-whisper model load + transcription on CPU can take
      // up to 3 min. We give Whisper a generous budget here because the
      // 470 MB small.en weights download on first run.
      const indexedAt = await pollIndexedAt(data.itemId, 180_000);
      expect(indexedAt).not.toBe("");

      const chunkCount = await pollChunks(data.itemId, 30_000);
      expect(chunkCount).toBeGreaterThan(0);
    }, 240_000);
  },
);
