listener 8883
cafile /mosquitto/config/tls/ca.pem
certfile /mosquitto/config/tls/cert.pem
keyfile /mosquitto/config/tls/key.pem
require_certificate true
use_identity_as_username true
acl_file /mosquitto/config/droplet.acl
allow_anonymous false
persistence false
