#!/usr/bin/env bash
# secrets.sh — Generate device-unique secrets and write .env file.
# Source this file; do not execute directly.

# Generate a random alphanumeric password of given length.
_gen_password() {
  local length="${1:-24}"
  openssl rand -base64 48 | tr -d '=/+\n' | head -c "$length"
}

# Generate a Fernet-compatible base64 key.
_gen_fernet_key() {
  openssl rand -base64 32
}

generate_env() {
  local env_file="$REPO_ROOT/.env"

  # --- Check for existing .env ---
  if [ -f "$env_file" ] && [ "${REGENERATE_ENV:-false}" != "true" ]; then
    log_success ".env already exists — skipping secret generation"
    log_info "  To regenerate: ./scripts/setup.sh --regenerate-env"
    log_divider
    return 0
  fi

  # --- Backup existing .env if regenerating ---
  if [ -f "$env_file" ]; then
    local backup="$env_file.bak.$(date +%s)"
    cp "$env_file" "$backup"
    log_info "Backed up existing .env to $backup"
  fi

  log_info "Generating device-unique secrets..."

  # --- Generate all secrets ---
  local pg_password redis_password mqtt_password nc_password device_secret device_secret_key jwt_secret
  pg_password=$(_gen_password 24)
  redis_password=$(_gen_password 24)
  mqtt_password=$(_gen_password 24)
  nc_password=$(_gen_password 24)
  device_secret=$(_gen_fernet_key)
  device_secret_key=$(openssl rand -base64 32)
  jwt_secret=$(openssl rand -hex 64)

  # --- Write .env directly (single source of truth — no template, no sed) ---
  cat > "$env_file" << EOF
# Droplet Edge Platform — generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# WARNING: Contains device-unique secrets. Do NOT commit this file.

# --- PostgreSQL ---
POSTGRES_USER=droplet
POSTGRES_PASSWORD=$pg_password
POSTGRES_DB=droplet
DATABASE_URL=postgresql://droplet:${pg_password}@db:5432/droplet

# --- Redis ---
REDIS_PASSWORD=$redis_password
REDIS_URL=redis://:${redis_password}@cache:6379
# Nextcloud expects this name for the Redis password
REDIS_HOST_PASSWORD=$redis_password

# --- MQTT ---
MQTT_USER=droplet
MQTT_PASSWORD=$mqtt_password
MQTT_BROKER=mqtt://droplet:${mqtt_password}@broker:1883
# Host-mode services (camera-discovery) connect via localhost
MQTT_BROKER_LOCAL=mqtt://droplet:${mqtt_password}@localhost:1883

# --- Nextcloud ---
NEXTCLOUD_ADMIN_USER=admin
NEXTCLOUD_ADMIN_PASSWORD=$nc_password
NEXTCLOUD_URL=http://nextcloud:80

# --- AI Gateway ---
AI_GATEWAY_URL=http://ai-gateway:8000
JETSON_OLLAMA_URL=http://inference-engine.local:11434

# --- Device secrets (unique per device — do not share) ---
DEVICE_SECRET=$device_secret
DEVICE_SECRET_KEY=$device_secret_key

# --- JWT ---
JWT_SECRET=$jwt_secret

# --- Frigate NVR ---
FRIGATE_MQTT_USER=droplet
FRIGATE_MQTT_PASSWORD=$mqtt_password

# --- Application ---
STORAGE_BACKEND=nextcloud
AUTH_ENABLED=true
FILES_ROOT=/data/files
MAX_UPLOAD_SIZE_MB=100
EOF

  chmod 600 "$env_file"

  log_success "Generated unique secrets:"
  log_info "  POSTGRES_PASSWORD : ${pg_password:0:4}****"
  log_info "  REDIS_PASSWORD    : ${redis_password:0:4}****"
  log_info "  MQTT_PASSWORD     : ${mqtt_password:0:4}****"
  log_info "  NEXTCLOUD_ADMIN   : ${nc_password:0:4}****"
  log_info "  DEVICE_SECRET     : ${device_secret:0:8}****"
  log_info "  DEVICE_SECRET_KEY : ${device_secret_key:0:8}****"
  log_info "  JWT_SECRET        : ${jwt_secret:0:8}****"
  log_success "Secrets written to $env_file (chmod 600)"

  # --- Generate Mosquitto password file ---
  _generate_mosquitto_passwd "$mqtt_password"

  # --- Write authenticated mosquitto.conf ---
  _write_mosquitto_conf

  # --- Generate TLS certificate for HTTPS ---
  _generate_tls_cert

  log_divider
}

_generate_mosquitto_passwd() {
  local mqtt_password="$1"
  local mqtt_user="${MQTT_USER:-droplet}"
  local passwd_dir="$REPO_ROOT/docker/mosquitto_passwd_dir"
  local passwd_file="$passwd_dir/mosquitto_passwd"

  log_info "Generating MQTT password file..."

  # Ensure the target directory exists (this is what docker-compose.yml mounts).
  # The parent directory is owned by the current user, so we can unlink any
  # stale file inside it without sudo even if the file itself is root-owned.
  mkdir -p "$passwd_dir"
  rm -f "$passwd_file" 2>/dev/null || true

  # Write directly to the final mount location. Pass --user so the container
  # runs as the host user and the generated file is already correctly owned —
  # no follow-up `sudo chown` needed. This is required for unattended factory
  # reset on the device, where nothing should prompt for a sudo password.
  if run_docker run --rm \
    --user "$(id -u):$(id -g)" \
    -v "$passwd_dir:/tmp/mqtt" \
    eclipse-mosquitto:2 \
    sh -c "mosquitto_passwd -b -c /tmp/mqtt/mosquitto_passwd '$mqtt_user' '$mqtt_password'"; then
    chmod 600 "$passwd_file"
    log_success "MQTT password file generated"
  else
    # Fallback: create a plaintext file (no Docker needed)
    log_warn "Could not generate hashed MQTT password — using plaintext fallback"
    printf "%s:%s\n" "$mqtt_user" "$mqtt_password" > "$passwd_file"
    chmod 600 "$passwd_file"
  fi

  # Clean up stale intermediate file from old code path. The parent directory
  # (docker/) is user-owned, so plain rm can unlink even a root-owned file.
  rm -f "$REPO_ROOT/docker/mosquitto_passwd" 2>/dev/null || true
}

_write_mosquitto_conf() {
  local conf_file="$REPO_ROOT/docker/mosquitto.conf"

  # Clean up stale file or directory from a previous failed run. Docker creates
  # a directory if the bind-mount target doesn't exist as a file yet, so we
  # need rm -rf to handle both cases.
  rm -rf "$conf_file" 2>/dev/null || true

  cat > "$conf_file" << 'MQTTCONF'
listener 1883
password_file /mosquitto/config/passwd_dir/mosquitto_passwd
allow_anonymous false
persistence false
MQTTCONF

  log_success "Mosquitto configured with authentication"
}

_generate_tls_cert() {
  local cert_dir="$REPO_ROOT/docker/certs"
  local cert_file="$cert_dir/droplet.crt"
  local key_file="$cert_dir/droplet.key"

  # Skip if cert already exists and is still valid
  if [ -f "$cert_file" ] && [ -f "$key_file" ]; then
    if openssl x509 -checkend 86400 -noout -in "$cert_file" >/dev/null 2>&1; then
      log_success "TLS certificate already exists and is valid — skipping"
      return 0
    fi
    log_warn "TLS certificate expired or invalid — regenerating"
  fi

  log_info "Generating self-signed TLS certificate (valid 10 years)..."
  mkdir -p "$cert_dir"

  # Collect Subject Alternative Names: localhost + all local IPv4 addresses
  local san="DNS:localhost"
  # Add the hostname
  local hn
  hn=$(hostname 2>/dev/null || echo "droplet")
  san="$san,DNS:$hn,DNS:${hn}.local"

  # Add all non-loopback IPv4 addresses
  local ip
  for ip in $(ip -4 addr show scope global 2>/dev/null \
              | grep -oP 'inet \K[\d.]+' 2>/dev/null || \
              ifconfig 2>/dev/null \
              | grep -oE 'inet (addr:)?[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' \
              | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' \
              | grep -v '^127\.'); do
    san="$san,IP:$ip"
  done
  # Always include loopback
  san="$san,IP:127.0.0.1"

  openssl req -x509 -nodes -newkey rsa:2048 \
    -days 3650 \
    -keyout "$key_file" \
    -out "$cert_file" \
    -subj "/CN=Droplet Edge Device" \
    -addext "subjectAltName=$san" \
    2>/dev/null

  chmod 600 "$key_file"
  chmod 644 "$cert_file"

  log_success "TLS certificate generated:"
  log_info "  Cert: $cert_file"
  log_info "  Key:  $key_file"
  log_info "  SANs: $san"
}
