#!/usr/bin/env bash
# secrets.sh — Generate device-unique secrets and write .env file.
# Source this file; do not execute directly.

# Generate a random alphanumeric password of given length.
_gen_password() {
  local length="${1:-24}"
  openssl rand -base64 48 | tr -d '=/+\n' | head -c "$length"
}

# Generate a Fernet-compatible base64 key.
_gen_fernet_key() {
  openssl rand -base64 32
}

generate_env() {
  local env_file="$REPO_ROOT/.env"

  # --- Check for existing .env ---
  if [ -f "$env_file" ] && [ "${REGENERATE_ENV:-false}" != "true" ]; then
    log_success ".env already exists — skipping secret generation"
    log_info "  To regenerate: ./scripts/setup.sh --regenerate-env"
    log_divider
    return 0
  fi

  # --- Backup existing .env if regenerating ---
  if [ -f "$env_file" ]; then
    local backup="$env_file.bak.$(date +%s)"
    cp "$env_file" "$backup"
    log_info "Backed up existing .env to $backup"
  fi

  log_info "Generating device-unique secrets..."

  # --- Generate all secrets ---
  local pg_password redis_password mqtt_password nc_password device_secret device_secret_key jwt_secret routing_service_token
  pg_password=$(_gen_password 24)
  redis_password=$(_gen_password 24)
  mqtt_password=$(_gen_password 24)
  nc_password=$(_gen_password 24)
  device_secret=$(_gen_fernet_key)
  device_secret_key=$(openssl rand -base64 32)
  jwt_secret=$(openssl rand -hex 64)
  # Shared bearer for orchestrator and camera-discovery → routing service (WARP-36).
  routing_service_token=$(openssl rand -hex 32)

  # --- Write .env directly (single source of truth — no template, no sed) ---
  cat > "$env_file" << EOF
# Droplet Edge Platform — generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# WARNING: Contains device-unique secrets. Do NOT commit this file.

# --- PostgreSQL ---
POSTGRES_USER=droplet
POSTGRES_PASSWORD=$pg_password
POSTGRES_DB=droplet
DATABASE_URL=postgresql://droplet:${pg_password}@db:5432/droplet

# --- Redis ---
REDIS_PASSWORD=$redis_password
REDIS_URL=redis://:${redis_password}@cache:6379
# Nextcloud expects this name for the Redis password
REDIS_HOST_PASSWORD=$redis_password

# --- MQTT ---
MQTT_USER=droplet
MQTT_PASSWORD=$mqtt_password
MQTT_BROKER=mqtt://droplet:${mqtt_password}@broker:1883
# Host-mode services (camera-discovery) connect via localhost
MQTT_BROKER_LOCAL=mqtt://droplet:${mqtt_password}@localhost:1883

# --- Nextcloud ---
NEXTCLOUD_ADMIN_USER=admin
NEXTCLOUD_ADMIN_PASSWORD=$nc_password
NEXTCLOUD_URL=http://nextcloud:80

# --- AI Gateway ---
AI_GATEWAY_URL=http://ai-gateway:8000
JETSON_OLLAMA_URL=http://inference-engine.local:11434

# --- Device secrets (unique per device — do not share) ---
DEVICE_SECRET=$device_secret
DEVICE_SECRET_KEY=$device_secret_key

# --- JWT ---
JWT_SECRET=$jwt_secret

# --- Routing service bearer (orchestrator, camera-discovery → routing) ---
ROUTING_SERVICE_TOKEN=$routing_service_token

# --- Frigate NVR ---
FRIGATE_MQTT_USER=droplet
FRIGATE_MQTT_PASSWORD=$mqtt_password

# --- Application ---
STORAGE_BACKEND=nextcloud
AUTH_ENABLED=true
FILES_ROOT=/data/files
MAX_UPLOAD_SIZE_MB=100

# --- Compose profiles ---
# Linux: include "linux" so Frigate (which needs /dev/dri/renderD128 and
# /dev/bus/usb) is part of the default \`docker compose up\`.
# macOS: leave empty — Frigate is skipped, dashboard remains reachable via
# the gateway. Add "full" by hand to opt into HA/file-indexer/switch/camera-
# discovery on either OS.
COMPOSE_PROFILES=$([ "$(uname)" = "Linux" ] && printf 'linux' || printf '')
EOF

  chmod 600 "$env_file"

  log_success "Generated unique secrets:"
  log_info "  POSTGRES_PASSWORD : ${pg_password:0:4}****"
  log_info "  REDIS_PASSWORD    : ${redis_password:0:4}****"
  log_info "  MQTT_PASSWORD     : ${mqtt_password:0:4}****"
  log_info "  NEXTCLOUD_ADMIN   : ${nc_password:0:4}****"
  log_info "  DEVICE_SECRET     : ${device_secret:0:8}****"
  log_info "  DEVICE_SECRET_KEY : ${device_secret_key:0:8}****"
  log_info "  JWT_SECRET        : ${jwt_secret:0:8}****"
  log_info "  ROUTING_TOKEN     : ${routing_service_token:0:8}****"
  log_success "Secrets written to $env_file (chmod 600)"

  # NOTE: Artifact materialization (mosquitto password/conf, TLS cert, Docker
  # secret files) and key migration are intentionally NOT called from here.
  # They run unconditionally from setup.sh Phase 4 via materialize_artifacts()
  # and migrate_env() so existing installs whose .env predates a new artifact
  # (e.g. WARP-37 docker/secrets/openwrt_password) self-heal on the next setup.

  log_divider
}

# Backfill missing keys in an existing .env file. Older installs predate
# WARP-36 (ROUTING_SERVICE_TOKEN) and WARP-44 (ROUTING_MODE); without this,
# new keys silently default to empty/insecure values at compose time —
# notably ROUTING_SERVICE_TOKEN="" disables routing-service auth entirely
# (services/routing/main.py:113).
#
# Idempotent: only appends when a key is missing, never rewrites an existing
# value. Backs up .env once on first append.
migrate_env() {
  local env_file="$REPO_ROOT/.env"
  [ -f "$env_file" ] || return 0

  local backed_up=false
  local appended_count=0
  local appended_keys=""

  _migrate_ensure_key() {
    local key="$1" value="$2"
    if ! grep -qE "^${key}=" "$env_file" 2>/dev/null; then
      if [ "$backed_up" = "false" ]; then
        local backup="$env_file.bak.$(date +%s)"
        cp "$env_file" "$backup"
        log_info "Backed up existing .env to $backup before migration"
        backed_up=true
      fi
      printf '%s=%s\n' "$key" "$value" >> "$env_file"
      appended_count=$((appended_count + 1))
      appended_keys="$appended_keys $key"
    fi
  }

  # Default ROUTING_MODE to `mock` on macOS (no local OpenWrt), `real` on
  # Linux. Only set when missing — never overwrite a user's choice.
  local routing_mode_default="real"
  [ "$(uname)" = "Darwin" ] && routing_mode_default="mock"

  # COMPOSE_PROFILES: "linux" on Linux turns on the Frigate service (gated
  # by `profiles: ["linux"]` in docker-compose.yml because it needs Linux-
  # only device nodes). macOS gets an empty default so frigate is skipped.
  local compose_profiles_default=""
  [ "$(uname)" = "Linux" ] && compose_profiles_default="linux"

  _migrate_ensure_key ROUTING_SERVICE_TOKEN "$(openssl rand -hex 32)"
  _migrate_ensure_key ROUTING_MODE "$routing_mode_default"
  _migrate_ensure_key COMPOSE_PROFILES "$compose_profiles_default"

  if [ "$appended_count" -gt 0 ]; then
    log_success "Migrated .env: appended$appended_keys"
  fi
}

# Materialize all setup-time artifact files that Docker Compose bind-mounts
# (Docker secret file, MQTT password file + conf, TLS cert). Each underlying
# generator is individually idempotent, so this is safe to run on every
# setup invocation.
#
# This intentionally lives outside generate_env() so it runs even when .env
# already exists — the common upgrade-an-existing-install path.
materialize_artifacts() {
  log_info "Materializing setup artifacts (idempotent)..."

  # Source .env so MQTT_PASSWORD / OPENWRT_PASSWORD / MQTT_USER are in scope
  # for the helpers below. Reachable via setup.sh --sync-secrets where nothing
  # else has loaded .env yet.
  if [ -f "$REPO_ROOT/.env" ]; then
    set -a
    # shellcheck disable=SC1091
    . "$REPO_ROOT/.env"
    set +a
  fi

  _generate_mosquitto_passwd "${MQTT_PASSWORD:-}"
  _write_mosquitto_conf
  _generate_tls_cert
  sync_openwrt_password_secret
}

# Write $OPENWRT_PASSWORD (from env or .env) into docker/secrets/openwrt_password
# so Docker Compose can mount it as a read-only secret at /run/secrets/openwrt_password.
# Safe to call independently after editing .env — the file is overwritten atomically.
sync_openwrt_password_secret() {
  local secret_dir="$REPO_ROOT/docker/secrets"
  local secret_file="$secret_dir/openwrt_password"
  local password="${OPENWRT_PASSWORD:-}"

  # Fall back to reading .env if the value isn't already in the shell environment.
  # `|| true` keeps a missing OPENWRT_PASSWORD line from tripping `set -euo pipefail`
  # (grep exits 1 on no match, which with pipefail would kill setup.sh mid-flight).
  # The function already handles an empty password below.
  if [ -z "$password" ] && [ -f "$REPO_ROOT/.env" ]; then
    password=$(grep -E '^OPENWRT_PASSWORD=' "$REPO_ROOT/.env" | head -n 1 | cut -d= -f2- || true)
  fi

  mkdir -p "$secret_dir"
  chmod 700 "$secret_dir"

  if [ -z "$password" ]; then
    # Write an empty placeholder so Docker Compose can still start (routing
    # service degrades to "router not connected" at startup without crashing).
    : > "$secret_file"
    chmod 600 "$secret_file"
    log_warn "OPENWRT_PASSWORD is empty — wrote empty $secret_file"
    log_info "  Set OPENWRT_PASSWORD in .env, then re-run ./scripts/setup.sh --sync-secrets"
    return 0
  fi

  # Write atomically: stage to .tmp then rename, so a crashed write never leaves
  # a half-populated secret file that the routing container would then read.
  local tmp="$secret_file.tmp"
  printf '%s' "$password" > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$secret_file"
  log_success "Wrote $secret_file (chmod 600)"
}

_generate_mosquitto_passwd() {
  local mqtt_password="$1"
  local mqtt_user="${MQTT_USER:-droplet}"
  local passwd_dir="$REPO_ROOT/docker/mosquitto_passwd_dir"
  local passwd_file="$passwd_dir/mosquitto_passwd"

  log_info "Generating MQTT password file..."

  # Ensure the target directory exists (this is what docker-compose.yml mounts).
  # The parent directory is owned by the current user, so we can unlink any
  # stale file inside it without sudo even if the file itself is root-owned.
  mkdir -p "$passwd_dir"
  rm -f "$passwd_file" 2>/dev/null || true

  # Write directly to the final mount location. Pass --user so the container
  # runs as the host user and the generated file is already correctly owned —
  # no follow-up `sudo chown` needed. This is required for unattended factory
  # reset on the device, where nothing should prompt for a sudo password.
  if run_docker run --rm \
    --user "$(id -u):$(id -g)" \
    -v "$passwd_dir:/tmp/mqtt" \
    eclipse-mosquitto:2 \
    sh -c "mosquitto_passwd -b -c /tmp/mqtt/mosquitto_passwd '$mqtt_user' '$mqtt_password'"; then
    chmod 600 "$passwd_file"
    log_success "MQTT password file generated"
  else
    # Fallback: create a plaintext file (no Docker needed)
    log_warn "Could not generate hashed MQTT password — using plaintext fallback"
    printf "%s:%s\n" "$mqtt_user" "$mqtt_password" > "$passwd_file"
    chmod 600 "$passwd_file"
  fi

  # Clean up stale intermediate file from old code path. The parent directory
  # (docker/) is user-owned, so plain rm can unlink even a root-owned file.
  rm -f "$REPO_ROOT/docker/mosquitto_passwd" 2>/dev/null || true
}

_write_mosquitto_conf() {
  local conf_file="$REPO_ROOT/docker/mosquitto.conf"

  # Clean up stale file or directory from a previous failed run. Docker creates
  # a directory if the bind-mount target doesn't exist as a file yet, so we
  # need rm -rf to handle both cases.
  rm -rf "$conf_file" 2>/dev/null || true

  cat > "$conf_file" << 'MQTTCONF'
listener 1883
password_file /mosquitto/config/passwd_dir/mosquitto_passwd
allow_anonymous false
persistence false
MQTTCONF

  log_success "Mosquitto configured with authentication"
}

_generate_tls_cert() {
  local cert_dir="$REPO_ROOT/docker/certs"
  local cert_file="$cert_dir/droplet.crt"
  local key_file="$cert_dir/droplet.key"

  # Skip if cert already exists and is still valid
  if [ -f "$cert_file" ] && [ -f "$key_file" ]; then
    if openssl x509 -checkend 86400 -noout -in "$cert_file" >/dev/null 2>&1; then
      log_success "TLS certificate already exists and is valid — skipping"
      return 0
    fi
    log_warn "TLS certificate expired or invalid — regenerating"
  fi

  log_info "Generating self-signed TLS certificate (valid 10 years)..."
  mkdir -p "$cert_dir"

  # Collect Subject Alternative Names: localhost + all local IPv4 addresses
  local san="DNS:localhost"
  # Add the hostname
  local hn
  hn=$(hostname 2>/dev/null || echo "droplet")
  san="$san,DNS:$hn,DNS:${hn}.local"

  # Add all non-loopback IPv4 addresses
  local ip
  for ip in $(ip -4 addr show scope global 2>/dev/null \
              | grep -oP 'inet \K[\d.]+' 2>/dev/null || \
              ifconfig 2>/dev/null \
              | grep -oE 'inet (addr:)?[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' \
              | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' \
              | grep -v '^127\.'); do
    san="$san,IP:$ip"
  done
  # Always include loopback
  san="$san,IP:127.0.0.1"

  openssl req -x509 -nodes -newkey rsa:2048 \
    -days 3650 \
    -keyout "$key_file" \
    -out "$cert_file" \
    -subj "/CN=Droplet Edge Device" \
    -addext "subjectAltName=$san" \
    2>/dev/null

  chmod 600 "$key_file"
  chmod 644 "$cert_file"

  log_success "TLS certificate generated:"
  log_info "  Cert: $cert_file"
  log_info "  Key:  $key_file"
  log_info "  SANs: $san"
}
