/**
 * Matter controller client — HTTP client for the matter-controller
 * host-network sidecar (WARP-850).
 *
 * History: this module used to embed matter.js (CommissioningController)
 * directly in the orchestrator process. The orchestrator container sits
 * on the compose bridge network, which has no BLE (no HCI access) and
 * no LAN mDNS — so BLE-only devices could never be commissioned and
 * mDNS discovery saw nothing (WARP-850/WARP-851). The controller now
 * runs in services/matter-controller with `network_mode: host`
 * (raw HCI + native multicast on the home LAN and the in-container
 * OpenWrt AP's br-lan host bridge); this file kept its module path and
 * export surface so every consumer — routes/matter.ts, the scenes
 * router's injected sendCommand (app.ts), health.ts, index.ts — is
 * unchanged.
 *
 * Contract notes:
 *  - Errors: the sidecar passes raw matter.js failures through as
 *    `{ errorClass, errorMessage }`; we reconstruct a local Error with
 *    the untouched message (name = errorClass) so routes/matter.ts's
 *    translateCommissionError() message-pattern mapping — pinned by the
 *    WARP-851 tests — behaves exactly as it did in-process.
 *  - WARP-456 activity rows: the signed ActivityRow wrappers for
 *    commission / decommission / command outcomes stay HERE (the
 *    sidecar has no Prisma and must not own the audit chain).
 *  - Events: one long-lived SSE consumer of the sidecar's /events
 *    stream re-emits into the local EventEmitter, so the orchestrator's
 *    dashboard-facing /api/matter/devices/events SSE route is
 *    unchanged. The bridge auto-reconnects, which also makes
 *    isMatterInitialized() self-healing when the sidecar restarts.
 *  - Capabilities: getMatterCapabilities() now proxies the sidecar's
 *    real BLE state (true when the BLE transport registered at sidecar
 *    process start) and degrades to false when the sidecar is
 *    unreachable. Route contract is unchanged: { bleCommissioning }.
 */

import { EventEmitter } from "node:events";
import type { PrismaClient } from "@prisma/client";
import { config } from "../config.js";
import { internalBaseUrl, internalFetch } from "../lib/internal-tls.js";
import type {
  MatterCommissionedDevice,
  MatterDiscoveredDevice,
  MatterGrouped,
} from "../types/smart-home.js";
import { recordActivity } from "./activity.singleton.js";
import type { ActivityActor } from "./activity.service.js";
import { createLogger } from "../lib/logger.js";

const logger = createLogger("matter");

// --- Timeouts (ms) ---
// Health/capabilities are cheap local-host hops; commissioning rides
// PASE + (optionally) BLE + network provisioning and legitimately runs
// long; discovery's budget follows the caller-supplied scan window.
const HEALTH_TIMEOUT_MS = 3_000;
const CAPABILITIES_TIMEOUT_MS = 3_000;
const DEFAULT_TIMEOUT_MS = 30_000;
const COMMISSION_TIMEOUT_MS = 120_000;
const DISCOVERY_MARGIN_MS = 10_000;
const BRIDGE_RECONNECT_MS = 3_000;
// How often to re-probe /health while the SSE stream is open — the
// stream staying alive says nothing about the controller (see
// runEventBridge). 15 s bounds the staleness window without meaningful
// load (one local GET).
const HEALTH_REPROBE_MS = 15_000;

// --- Module state ---
let sidecarReachable = false;
let sidecarInitialized = false;
let bridgeAbort: AbortController | null = null;
const stateEvents = new EventEmitter();
// WARP-1447: Prisma handle for DeviceAlias cleanup on decommission.
// Injected at boot (index.ts) following the setPrismaForReindex pattern —
// this module predates DB access and its call sites don't carry prisma.
// Null (e.g. in tests that never wire it) → cleanup is skipped.
let aliasPrisma: PrismaClient | null = null;

export function setPrismaForMatter(client: PrismaClient | null): void {
  aliasPrisma = client;
}

function baseUrl(): string {
  // Strip a trailing slash so path joins stay canonical.
  // WARP-236: https:// + client cert when internal mTLS is on (identity when off).
  return internalBaseUrl(config.DROPLET_MATTER_SERVICE_URL).replace(/\/+$/, "");
}

function authHeaders(): Record<string, string> {
  return {
    // Shared token header following the device-bridge precedent
    // (services/oled-display/device-bridge.py). Generated by setup.sh
    // into .env as DROPLET_MATTER_SERVICE_TOKEN; the sidecar fails
    // closed when its copy is empty.
    "X-Droplet-Auth": config.DROPLET_MATTER_SERVICE_TOKEN,
    "Content-Type": "application/json",
  };
}

/**
 * Rebuild a local Error from the sidecar's structured error body so the
 * raw matter.js class name + message survive the HTTP hop (WARP-850
 * requirement #4 — translateCommissionError depends on the message).
 */
interface SidecarErrorBody {
  error?: string;
  errorClass?: string;
  errorMessage?: string;
}

async function toSidecarError(res: Response): Promise<Error> {
  let body: SidecarErrorBody | null = null;
  try {
    body = (await res.json()) as SidecarErrorBody;
  } catch {
    // Non-JSON body — fall through to the status-bearing message.
  }
  const message =
    body?.errorMessage ??
    body?.error ??
    `matter-controller returned HTTP ${res.status}`;
  const err = new Error(message);
  if (body?.errorClass) err.name = body.errorClass;
  return err;
}

async function sidecarJson<T>(
  path: string,
  init: RequestInit = {},
  timeoutMs = DEFAULT_TIMEOUT_MS,
): Promise<T> {
  const res = await internalFetch(`${baseUrl()}${path}`, {
    ...init,
    headers: { ...authHeaders(), ...(init.headers ?? {}) },
    signal: AbortSignal.timeout(timeoutMs),
  });
  if (!res.ok) throw await toSidecarError(res);
  return (await res.json()) as T;
}

/**
 * Audit-row writes must never change a Matter operation's outcome: a
 * Prisma hiccup after a successful commission would otherwise surface
 * as a false 500 (the device IS commissioned — a retry then hits
 * "already commissioned" and the device looks orphaned), and one inside
 * sendMatterCommand's finally block would REPLACE the real matter.js
 * error with a Prisma error that translateCommissionError can't map.
 * The operation result is the truth; a lost audit row is a warn line.
 */
async function auditQuietly(
  entry: Parameters<typeof recordActivity>[0],
): Promise<void> {
  try {
    await recordActivity(entry);
  } catch (err) {
    logger.warn("Matter audit row write failed (non-fatal): %s", err);
  }
}

// --- Initialization / lifecycle ---

export async function initMatterService(): Promise<void> {
  ensureEventBridge();

  const res = await internalFetch(`${baseUrl()}/health`, {
    headers: authHeaders(),
    signal: AbortSignal.timeout(HEALTH_TIMEOUT_MS),
  });
  if (!res.ok) {
    throw new Error(`matter-controller health probe returned HTTP ${res.status}`);
  }
  const health = (await res.json()) as { ok?: boolean; initialized?: boolean };
  sidecarReachable = true;
  sidecarInitialized = health.initialized === true;
  if (!sidecarInitialized) {
    throw new Error(
      "matter-controller sidecar is reachable but its controller is not initialized",
    );
  }
  logger.info("Connected to matter-controller sidecar at %s", baseUrl());
}

export function isMatterInitialized(): boolean {
  return sidecarReachable && sidecarInitialized;
}

export async function shutdownMatterService(): Promise<void> {
  bridgeAbort?.abort();
  bridgeAbort = null;
  sidecarReachable = false;
  sidecarInitialized = false;
  logger.info("Matter sidecar client stopped");
}

// --- Capabilities ---

export interface MatterCapabilities {
  /**
   * Whether BLE commissioning is available on this box. True when the
   * matter-controller sidecar registered its BLE transport
   * (@matter/nodejs-ble on the host's HCI adapter) at process start;
   * false when the box is IP-only OR the sidecar is unreachable.
   */
  bleCommissioning: boolean;
  /**
   * WARP-1035: whether the sidecar can hand a BLE-first device the
   * Droplet AP's Wi-Fi credentials during commissioning (WARP-895).
   * Computed by the sidecar at request time from the same
   * resolveWifiNetwork() the commission path uses — false means a
   * BLE-paired device has no network to join, so commissioning is
   * effectively on-network-only. False too when the sidecar is
   * unreachable (same honest degrade as bleCommissioning).
   */
  wifiProvisioning: boolean;
  /**
   * WARP-1035: the Droplet AP's SSID (DROPLET_MATTER_WIFI_SSID) so the
   * dashboard can name the network new devices join. Null when unset
   * or the sidecar is unreachable.
   */
  apSsid: string | null;
}

/**
 * WARP-851 capability surface, now proxying the sidecar's real state
 * (WARP-850 requirement #5). Deliberately NOT gated on
 * isMatterInitialized(): the sidecar answers /capabilities before its
 * controller finishes booting, and the setup wizard needs the BLE
 * answer early. Degrades to false — never throws — because "can't
 * reach the controller" and "no BLE" are the same honest answer for
 * the add-device wizard.
 */
export async function getMatterCapabilities(): Promise<MatterCapabilities> {
  try {
    const caps = await sidecarJson<{
      bleCommissioning?: boolean;
      wifiProvisioning?: boolean;
      apSsid?: string | null;
    }>("/capabilities", {}, CAPABILITIES_TIMEOUT_MS);
    return {
      bleCommissioning: caps.bleCommissioning === true,
      wifiProvisioning: caps.wifiProvisioning === true,
      apSsid:
        typeof caps.apSsid === "string" && caps.apSsid.trim() !== ""
          ? caps.apSsid
          : null,
    };
  } catch (err) {
    logger.debug(
      "matter-controller capabilities probe failed: %s",
      (err as Error).message,
    );
    return { bleCommissioning: false, wifiProvisioning: false, apSsid: null };
  }
}

// --- Discovery ---

export async function discoverDevices(
  timeoutMs = 15_000,
): Promise<MatterDiscoveredDevice[]> {
  const data = await sidecarJson<{ devices: MatterDiscoveredDevice[] }>(
    `/discover?timeout=${encodeURIComponent(timeoutMs)}`,
    {},
    timeoutMs + DISCOVERY_MARGIN_MS,
  );
  return data.devices;
}

// --- Commissioning ---

export async function commissionDevice(
  pairingCode: string,
  // WARP-1010: required, no default — every caller must declare who is
  // acting (routes derive it from the request; the agent loop is `ai`).
  actor: ActivityActor,
): Promise<{ nodeId: string }> {
  const result = await sidecarJson<{ nodeId: string }>(
    "/commission",
    {
      method: "POST",
      body: JSON.stringify({ pairing_code: pairingCode }),
    },
    COMMISSION_TIMEOUT_MS,
  );

  // WARP-456: audit row for the commission write. Commissioning is the
  // highest-impact Matter operation — the appliance now owns the
  // device's network credentials and can drive it. Stays orchestrator-
  // side so the signed ActivityRow chain lives in one process.
  await auditQuietly({
    kind: "smart_home",
    severity: "ok",
    sourceIcon: "plug",
    what: "Commissioned Matter device",
    actor,
    sub: `nodeId ${result.nodeId}`,
    refs: { nodeId: result.nodeId },
  });

  return result;
}

// --- Decommissioning ---

/**
 * @returns false when the sidecar reports the node isn't commissioned
 * (its 404) — the route layer maps that to its own 404, mirroring
 * getDevice, instead of reconstructing it from a thrown error.
 */
export async function decommissionDevice(
  nodeIdStr: string,
  actor: ActivityActor,
): Promise<boolean> {
  const res = await internalFetch(`${baseUrl()}/devices/${encodeURIComponent(nodeIdStr)}`,
    {
      method: "DELETE",
      headers: authHeaders(),
      signal: AbortSignal.timeout(DEFAULT_TIMEOUT_MS),
    },
  );
  if (res.status === 404) return false;
  if (!res.ok) throw await toSidecarError(res);
  logger.info("Device decommissioned: %s", nodeIdStr);

  // WARP-1447: drop the device's DeviceAlias row. The alias is keyed by
  // nodeId, and a decommissioned node's id is dead — re-commissioning
  // the same physical device mints a NEW nodeId, so keeping the row only
  // orphans it. deleteMany tolerates absence (no alias was ever set),
  // and — like the audit row below — a cleanup failure must never
  // change the decommission outcome: the fabric write already happened.
  if (aliasPrisma) {
    try {
      await aliasPrisma.deviceAlias.deleteMany({ where: { nodeId: nodeIdStr } });
    } catch (err) {
      logger.warn(
        "DeviceAlias cleanup failed for decommissioned node %s (non-fatal): %s",
        nodeIdStr,
        err,
      );
    }
  }

  // WARP-456: audit row for the destructive write.
  await auditQuietly({
    kind: "smart_home",
    severity: "warn",
    sourceIcon: "unplug",
    what: "Decommissioned Matter device",
    actor,
    sub: `nodeId ${nodeIdStr}`,
    refs: { nodeId: nodeIdStr },
  });
  return true;
}

// --- Device listing ---

export async function getCommissionedDevices(): Promise<MatterGrouped> {
  return sidecarJson<MatterGrouped>("/devices");
}

export async function getDevice(
  nodeIdStr: string,
): Promise<MatterCommissionedDevice | null> {
  const res = await internalFetch(`${baseUrl()}/devices/${encodeURIComponent(nodeIdStr)}`,
    {
      headers: authHeaders(),
      signal: AbortSignal.timeout(DEFAULT_TIMEOUT_MS),
    },
  );
  // 404 is a real condition the route layer maps to its own 404 — not
  // an error to reconstruct.
  if (res.status === 404) return null;
  if (!res.ok) throw await toSidecarError(res);
  return (await res.json()) as MatterCommissionedDevice;
}

// --- Commands ---

export async function sendMatterCommand(
  nodeIdStr: string,
  command: string,
  // WARP-1010: actor precedes the optional payload so it can stay
  // required — a compile error forces every caller to declare it.
  actor: ActivityActor,
  data?: Record<string, unknown>,
): Promise<{ status: string; result?: unknown }> {
  // WARP-456: wrap the dispatcher so every Matter write — success or
  // failure — lands as one signed ActivityRow. The HTTP hop to the
  // sidecar does the real work; the wrapper only reacts to the outcome.
  let threw: unknown = null;
  try {
    return await sidecarJson<{ status: string; result?: unknown }>(
      `/devices/${encodeURIComponent(nodeIdStr)}/command`,
      {
        method: "POST",
        body: JSON.stringify({ command, data }),
      },
    );
  } catch (err) {
    threw = err;
    throw err;
  } finally {
    // auditQuietly, NOT recordActivity: a throw inside a finally block
    // replaces the in-flight matter.js error with the audit failure.
    await auditQuietly({
      kind: "smart_home",
      severity: threw ? "err" : "ok",
      sourceIcon: "home",
      what: threw ? `Matter ${command} failed` : `Matter ${command}`,
      actor,
      sub: `nodeId ${nodeIdStr}`,
      refs: {
        nodeId: nodeIdStr,
        command,
      },
    });
  }
}

// --- State subscriptions (SSE bridge) ---

export function subscribeStateChanges(
  callback: (event: any) => void,
): () => void {
  stateEvents.on("state_changed", callback);
  return () => stateEvents.off("state_changed", callback);
}

export function subscribeConnectionChanges(
  callback: (event: any) => void,
): () => void {
  stateEvents.on("connection_changed", callback);
  return () => stateEvents.off("connection_changed", callback);
}

/**
 * Long-lived consumer of the sidecar's /events SSE stream. Started by
 * initMatterService(), stopped by shutdownMatterService(). Reconnects
 * with a fixed backoff; every (re)connect refreshes the health flags so
 * isMatterInitialized() self-heals after a sidecar restart without an
 * orchestrator restart.
 */
function ensureEventBridge(): void {
  if (bridgeAbort) return;
  const abort = new AbortController();
  bridgeAbort = abort;
  void runEventBridge(abort.signal).catch((err) => {
    logger.warn("matter event bridge stopped unexpectedly: %s", err);
  });
}

async function runEventBridge(signal: AbortSignal): Promise<void> {
  while (!signal.aborted) {
    try {
      const res = await internalFetch(`${baseUrl()}/events`, {
        headers: authHeaders(),
        signal,
      });
      if (res.ok && res.body) {
        await refreshHealthFlags();
        // The connect-time snapshot of sidecarInitialized goes stale
        // while the stream lives: the sidecar's HTTP server + SSE
        // heartbeats keep running when its controller fails
        // non-fatally (routes 503), so the TCP stream never closes and
        // the flag would stay true indefinitely. Re-probe /health on
        // an interval for as long as the stream is open so
        // isMatterInitialized() tracks the controller, not the socket.
        const reprobe = setInterval(() => {
          void refreshHealthFlags();
        }, HEALTH_REPROBE_MS);
        reprobe.unref?.();
        try {
          await consumeSseStream(res.body, signal);
        } finally {
          clearInterval(reprobe);
        }
      } else {
        await res.body?.cancel().catch(() => undefined);
      }
    } catch {
      // Connection refused / reset / aborted — handled by the loop.
    }
    sidecarReachable = false;
    if (signal.aborted) return;
    await sleep(BRIDGE_RECONNECT_MS, signal);
  }
}

async function refreshHealthFlags(): Promise<void> {
  try {
    const res = await internalFetch(`${baseUrl()}/health`, {
      headers: authHeaders(),
      signal: AbortSignal.timeout(HEALTH_TIMEOUT_MS),
    });
    if (res.ok) {
      const health = (await res.json()) as { initialized?: boolean };
      sidecarReachable = true;
      sidecarInitialized = health.initialized === true;
      return;
    }
  } catch {
    // fall through
  }
  sidecarReachable = false;
}

async function consumeSseStream(
  body: ReadableStream<Uint8Array>,
  signal: AbortSignal,
): Promise<void> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  try {
    while (!signal.aborted) {
      const { done, value } = await reader.read();
      if (done) return;
      buffer += decoder.decode(value, { stream: true });
      let frameEnd: number;
      while ((frameEnd = buffer.indexOf("\n\n")) >= 0) {
        const frame = buffer.slice(0, frameEnd);
        buffer = buffer.slice(frameEnd + 2);
        for (const line of frame.split("\n")) {
          if (line.startsWith("data: ")) handleSseEvent(line.slice(6));
        }
      }
    }
  } finally {
    reader.releaseLock();
  }
}

function handleSseEvent(payload: string): void {
  let event: { type?: string } & Record<string, unknown>;
  try {
    event = JSON.parse(payload);
  } catch {
    return;
  }
  const { type, ...rest } = event;
  // Re-emit without the wire `type` discriminator — local subscribers
  // (the dashboard-facing SSE route) historically received the bare
  // event and add their own `type` when serializing.
  if (type === "state_changed") stateEvents.emit("state_changed", rest);
  else if (type === "connection_changed")
    stateEvents.emit("connection_changed", rest);
}

function sleep(ms: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve) => {
    const timer = setTimeout(done, ms);
    timer.unref?.();
    signal.addEventListener("abort", done, { once: true });
    function done() {
      clearTimeout(timer);
      signal.removeEventListener("abort", done);
      resolve();
    }
  });
}
