/**
 * WARP-1121 — client side of the onboarding-interview protocol (§9.3 of the
 * architecture brief + §4/§5/§9 of the design brief).
 *
 * Pure functions only — everything here is unit-tested without React.
 *
 * The topic-marker protocol is the ENTIRE progress mechanism: every interview
 * question arrives prefixed `[topic n/7]`; the client strips it before render
 * and uses it to advance the dots, pick the canned chip set, and drive the
 * aria-live counter. No marker parsed → hold, never guess.
 */

export const TOPIC_COUNT = 7;

/** Design brief §9 — verbatim chrome copy. */
export const INTERVIEW_COPY = {
  introSpokenLine: "Let's get to know your business.",
  introBody:
    "I'll ask a few questions about what you do and how you work — it helps me give answers that fit. You can stop anytime, and you review everything before it's saved.",
  introMeta: "7 topics · about 5 min · stays on this box",
  introStart: "Start",
  introSkip: "Skip for now",
  introSubHint: "You can run this later from Settings.",
  progressEyebrow: "GETTING TO KNOW YOUR BUSINESS",
  pause: "Pause",
  skipTheRest: "Skip the rest",
  wrapUpTurn: "That's enough — sum up what you have so far.",
  resumeBanner: "You were telling me about your business — pick up where we left off?",
  resume: "Resume",
  sessionTitle: "Getting to know your business",
  reviewTitle: "What I learned",
  reviewSubtitle: "Generated by Droplet · review before saving",
  factsHeader: "Remember these",
  summaryDisclosure: "How I'd sum it up",
  safetyChip: "Write · confirm to apply",
  apply: "Apply",
  notYet: "Not yet",
  savedLine: "Saved · you can edit any of this in Settings",
  viewWhatIKnow: "View what I know",
  parseFailure: "I couldn't put that into a summary — want me to try again?",
  tryAgain: "Try again",
  applyError: "That didn't save — your answers are still here. Try again.",
  nothingToSave: "Nothing selected to save yet.",
  finishedElsewhere:
    "Another admin finished this setup — here's what Droplet knows now.",
  nonOwnerHint: "The owner can teach Droplet about the business in Settings.",
  warmingFootnote: "Droplet is starting up — give it a moment.",
  nudgeLine: "It's been a while — has anything changed about how you work?",
  nudgeAction: "Update Droplet",
} as const;

/** Profile row labels, in §9's order, mapped 1:1 to backend fields (§11). */
export const PROFILE_ROWS: ReadonlyArray<{
  field: "whatWeDo" | "customers" | "teamShape" | "toolsUsed" | "typicalDay" | "goals";
  label: string;
}> = [
  { field: "whatWeDo", label: "What you do" },
  { field: "customers", label: "Customers" },
  { field: "teamShape", label: "Team" },
  { field: "toolsUsed", label: "Tools" },
  { field: "typicalDay", label: "A typical day" },
  { field: "goals", label: "Goals" },
];

/** Canned suggestion-chip sets keyed by topic number (§9 verbatim). Topics
 *  without a set show no chips — free-text answers only. NEVER model-generated. */
export const TOPIC_CHIPS: Readonly<Record<number, readonly string[]>> = {
  2: ["Mostly consumers", "Mostly businesses", "Both"],
  3: ["Just me", "2–10 people", "10–50", "50+"],
  7: ["Keep it short", "Give me detail", "Numbers first"],
};

const TOPIC_MARKER_RE = /\[topic\s+(\d)\s*\/\s*7\]/i;

/** Parse the topic marker out of an assistant turn. Null when no marker
 *  parses (the dots HOLD — never guess) or the index is out of range. */
export function parseTopicMarker(text: string): number | null {
  const m = TOPIC_MARKER_RE.exec(text);
  if (!m) return null;
  const n = Number(m[1]);
  return n >= 1 && n <= TOPIC_COUNT ? n : null;
}

/** Strip every topic marker before render — the user never sees `[topic 3/7]`. */
export function stripTopicMarkers(text: string): string {
  return text.replace(new RegExp(TOPIC_MARKER_RE.source, "gi"), "").replace(/^[ \t]+/, "");
}

// ---------------------------------------------------------------------------
// Proposal fence handling (§9.3 streaming contract: raw JSON never paints).
// ---------------------------------------------------------------------------

const FENCE_OPEN_RE = /```(?:json)?\s*$|```(?:json)?\s*\{/im;

/** Streaming watcher: once the accumulated assistant text contains the start
 *  of a fenced block, the client suppresses further delta rendering and shows
 *  the thinking indicator until `done`. */
export function containsProposalFenceStart(accumulated: string): boolean {
  return /```json/i.test(accumulated) || FENCE_OPEN_RE.test(accumulated);
}

export interface ProposalFact {
  category: "Business" | "Tone" | "Workflow" | "Schedule" | "Scope" | "Other";
  fact: string;
  audience: "family" | "admin";
}

export interface Proposal {
  profile: Partial<{
    whatWeDo: string;
    customers: string;
    teamShape: string;
    toolsUsed: string;
    typicalDay: string;
    goals: string;
  }>;
  summary: string;
  facts: ProposalFact[];
}

const KNOWN_CATEGORIES = new Set([
  "Business",
  "Tone",
  "Workflow",
  "Schedule",
  "Scope",
  "Other",
]);

/**
 * Parse the completed assistant turn into a Proposal. Tolerant of the model's
 * shape drift (missing sections, unknown audience → clamped to family, unknown
 * category → Business, over-long lists truncated to the backend's 20-fact
 * bound) but STRICT about JSON: unparseable → null → the parse-failure card.
 */
export function parseProposal(text: string): Proposal | null {
  const fenced = /```(?:json)?\s*([\s\S]*?)```/i.exec(text);
  const raw = fenced ? fenced[1] : text;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw.trim());
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object") return null;
  const obj = parsed as Record<string, unknown>;

  const profileIn =
    obj.profile && typeof obj.profile === "object"
      ? (obj.profile as Record<string, unknown>)
      : {};
  const profile: Proposal["profile"] = {};
  for (const { field } of PROFILE_ROWS) {
    const v = profileIn[field];
    if (typeof v === "string" && v.trim()) profile[field] = v.trim();
  }

  const summary = typeof obj.summary === "string" ? obj.summary.trim() : "";

  const factsIn = Array.isArray(obj.facts) ? obj.facts : [];
  const facts: ProposalFact[] = [];
  for (const f of factsIn.slice(0, 20)) {
    if (!f || typeof f !== "object") continue;
    const fact = (f as { fact?: unknown }).fact;
    if (typeof fact !== "string" || !fact.trim()) continue;
    const cat = (f as { category?: unknown }).category;
    const audience = (f as { audience?: unknown }).audience;
    facts.push({
      category: (typeof cat === "string" && KNOWN_CATEGORIES.has(cat)
        ? cat
        : "Business") as ProposalFact["category"],
      fact: fact.trim().slice(0, 280),
      audience: audience === "admin" ? "admin" : "family",
    });
  }

  if (Object.keys(profile).length === 0 && !summary && facts.length === 0) {
    // A parsed-but-empty proposal is a failure, not a zero-commit.
    return null;
  }
  return { profile, summary, facts };
}
