#!/usr/bin/env bash
# =============================================================================
# Droplet Edge Platform — Redis TLS-only + per-service ACLs (WARP-234)
# =============================================================================
#
# Dockerized integration test. Boots a throwaway redis:7-alpine with the SAME
# launch shape the compose `cache` service uses (cert staging + --port 0 +
# --tls-port 6380 + --aclfile) against a sandbox internal-CA `cache` leaf and
# a sandbox users.acl generated by the REAL _generate_redis_acl, and proves:
#   1. the plaintext port refuses connections (nothing listens on 6379),
#   2. TLS PING succeeds for the default user — and ONLY ping (harness
#      identity; any data command is NOPERM),
#   3. a wrong password fails closed (WRONGPASS),
#   4. orchestrator: keyspace-wide read/write/scripting, but @dangerous
#      (FLUSHALL/KEYS/CONFIG) stays denied,
#   5. mcp-server: get/setex inside rerank:* only — other keys and other
#      commands are denied,
#   6. ai-gateway: session/ratelimit patterns + EVAL work; rerank:* denied,
#   7. nextcloud: keyspace read/write + the KEYS carve-out; FLUSHALL denied.
#
# Requires local Docker for 1-7 (SKIPs cleanly without a daemon). A static
# TLS 1.3 pin check runs unconditionally.
#
# ci: developer-only — boots a redis container per ACL identity. The ACL
# GENERATION invariants (hashes only, PING-only default, per-service
# least-privilege shapes) are the half that can be proven without a daemon,
# and tests/redis-acl.test.sh now runs them at PR time on setup-tests.yml
# (WARP-2647). What stays uncovered is live ENFORCEMENT — that the server
# actually refuses the denied commands.
# =============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_REAL="$(cd "$SCRIPT_DIR/../.." && pwd)"
IMG=redis:7-alpine
NAME=droplet-redistls-test

# --- Colors ---
if [ -t 1 ]; then
  _GREEN='\033[0;32m'; _RED='\033[0;31m'; _YELLOW='\033[0;33m'; _BOLD='\033[1m'; _RESET='\033[0m'
else
  _GREEN=''; _RED=''; _YELLOW=''; _BOLD=''; _RESET=''
fi

TOTAL=0; PASSED=0; FAILED=0; SKIPPED=0
FAILED_NAMES=()
_pass() { PASSED=$((PASSED + 1)); printf "  ${_GREEN}PASS${_RESET}  %s\n" "$1"; }
_fail() { FAILED=$((FAILED + 1)); FAILED_NAMES+=("$1"); printf "  ${_RED}FAIL${_RESET}  %s\n" "$1"; }
_skip() { SKIPPED=$((SKIPPED + 1)); printf "  ${_YELLOW}SKIP${_RESET}  %s\n" "$1"; }

_run_test() {
  local name="$1"; shift
  TOTAL=$((TOTAL + 1))
  printf "\n${_BOLD}→ %s${_RESET}\n" "$name"
  if "$@"; then _pass "$name"; else _fail "$name"; fi
}

_docker_up() { docker info >/dev/null 2>&1; }
cleanup() { docker rm -f "$NAME" >/dev/null 2>&1 || true; }
trap cleanup EXIT

PW_DEFAULT="redistls-default-pw"
PW_ORCH="redistls-orch-pw"
PW_AIGW="redistls-aigw-pw"
PW_MCP="redistls-mcp-pw"
PW_NC="redistls-nc-pw"

# rcli <user> <pw> <args...> — capture-then-echo (pipefail-safe): runs
# redis-cli over TLS inside the container and prints stdout+stderr.
rcli() {
  local user="$1" pw="$2"; shift 2
  local out
  out="$(docker exec "$NAME" redis-cli --tls --cacert /tmp/redis-ca.crt \
    -p 6380 --user "$user" --pass "$pw" --no-auth-warning "$@" 2>&1)" || true
  printf '%s' "$out"
}

start_cache() {
  local sandbox="$1"
  # Real issuance + real ACL generator — no parallel fixtures to drift.
  log_info() { :; }; log_warn() { :; }; log_success() { :; }
  REPO_ROOT="$sandbox"
  # shellcheck source=/dev/null
  source "$REPO_ROOT_REAL/scripts/lib/internal-ca.sh"
  internal_ca_ensure
  internal_ca_issue cache
  # shellcheck source=/dev/null
  source "$REPO_ROOT_REAL/scripts/lib/secrets.sh"
  REDIS_PASSWORD="$PW_DEFAULT" REDIS_HOST_PASSWORD="$PW_NC" \
    REDIS_PASSWORD_ORCHESTRATOR="$PW_ORCH" REDIS_PASSWORD_AI_GATEWAY="$PW_AIGW" \
    REDIS_PASSWORD_MCP="$PW_MCP" _generate_redis_acl || return 1
  docker run -d --name "$NAME" \
    -v "$sandbox/data/secrets/service-tls/cache:/certs-src:ro" \
    -v "$sandbox/data/secrets/redis/users.acl:/etc/redis/users.acl:ro" \
    "$IMG" \
    sh -c 'install -o redis -g redis -m 600 /certs-src/key.pem /tmp/redis.key
           install -o redis -g redis -m 644 /certs-src/cert.pem /tmp/redis.crt
           install -o redis -g redis -m 644 /certs-src/ca.pem /tmp/redis-ca.crt
           exec docker-entrypoint.sh redis-server \
             --port 0 \
             --tls-port 6380 \
             --tls-cert-file /tmp/redis.crt \
             --tls-key-file /tmp/redis.key \
             --tls-ca-cert-file /tmp/redis-ca.crt \
             --tls-auth-clients no \
             --tls-protocols "TLSv1.3" \
             --aclfile /etc/redis/users.acl' >/dev/null || return 1
  local i; for i in $(seq 1 30); do
    [ "$(rcli default "$PW_DEFAULT" PING)" = "PONG" ] && return 0
    sleep 1
  done
  return 1
}

test_plaintext_port_refused() {
  local out
  out="$(docker exec "$NAME" redis-cli -p 6379 -a "$PW_DEFAULT" --no-auth-warning PING 2>&1)" || true
  grep -q "Connection refused" <<<"$out"
}

test_default_is_ping_only() {
  [ "$(rcli default "$PW_DEFAULT" PING)" = "PONG" ] || return 1
  rcli default "$PW_DEFAULT" GET x | grep -q "NOPERM" || return 1
  rcli default "$PW_DEFAULT" SET x 1 | grep -q "NOPERM"
}

test_wrong_password_fails_closed() {
  rcli orchestrator "not-the-password" PING | grep -q "WRONGPASS"
}

test_orchestrator_broad_but_not_dangerous() {
  [ "$(rcli orchestrator "$PW_ORCH" SET anykey v1)" = "OK" ] || return 1
  [ "$(rcli orchestrator "$PW_ORCH" GET anykey)" = "v1" ] || return 1
  # session eval path (@scripting)
  [ "$(rcli orchestrator "$PW_ORCH" EVAL "return redis.call('GET', KEYS[1])" 1 anykey)" = "v1" ] || return 1
  # ioredis ready check
  rcli orchestrator "$PW_ORCH" INFO server | grep -q "redis_version" || return 1
  rcli orchestrator "$PW_ORCH" FLUSHALL | grep -q "NOPERM" || return 1
  rcli orchestrator "$PW_ORCH" KEYS '*' | grep -q "NOPERM" || return 1
  rcli orchestrator "$PW_ORCH" CONFIG GET maxmemory | grep -q "NOPERM"
}

test_mcp_scoped_to_rerank_cache() {
  [ "$(rcli mcp-server "$PW_MCP" SETEX rerank:abc 60 cached)" = "OK" ] || return 1
  [ "$(rcli mcp-server "$PW_MCP" GET rerank:abc)" = "cached" ] || return 1
  rcli mcp-server "$PW_MCP" GET anykey | grep -q "NOPERM" || return 1
  rcli mcp-server "$PW_MCP" DEL rerank:abc | grep -q "NOPERM" || return 1
  rcli mcp-server "$PW_MCP" SET rerank:abc x | grep -q "NOPERM"
}

test_ai_gateway_sessions_and_ratelimit_only() {
  [ "$(rcli ai-gateway "$PW_AIGW" ZADD sessions:index 1 s1)" = "1" ] || return 1
  [ "$(rcli ai-gateway "$PW_AIGW" HSET session:s1 title t)" = "1" ] || return 1
  # the rate-limit Lua shape (ZADD/EXPIRE on ratelimit:*)
  rcli ai-gateway "$PW_AIGW" EVAL "redis.call('ZADD', KEYS[1], 1, 'm'); return redis.call('ZCARD', KEYS[1])" 1 ratelimit:ip \
    | grep -qx 1 || return 1
  rcli ai-gateway "$PW_AIGW" GET rerank:abc | grep -q "NOPERM" || return 1
  rcli ai-gateway "$PW_AIGW" SET anykey v | grep -q "NOPERM"
}

test_nextcloud_keys_carveout_no_flush() {
  [ "$(rcli nextcloud "$PW_NC" SET ncinstance:k v)" = "OK" ] || return 1
  rcli nextcloud "$PW_NC" KEYS 'ncinstance:*' | grep -q "ncinstance:k" || return 1
  rcli nextcloud "$PW_NC" FLUSHALL | grep -q "NOPERM"
}

# Static — no docker. The TLS 1.3 pin must not silently regress.
test_compose_pins_tls13() {
  grep -q -- '--tls-protocols "TLSv1.3"' "$REPO_ROOT_REAL/docker/docker-compose.yml"
}

# =============================================================================
# Driver
# =============================================================================
printf "\n  ${_BOLD}Redis TLS-only + per-service ACL integration suite${_RESET}\n"
printf "  Real repo: %s\n" "$REPO_ROOT_REAL"
printf "  ──────────────────────────────────\n"

if _docker_up; then
  SANDBOX="$(mktemp -d)"
  # shellcheck disable=SC2064
  trap "cleanup; rm -rf '$SANDBOX'" EXIT
  printf "\n${_BOLD}→ boot cache container (TLS/ACL launch shape)${_RESET}\n"
  TOTAL=$((TOTAL + 1))
  if start_cache "$SANDBOX"; then
    _pass "cache container booted (TLS PING as default)"
    _run_test "plaintext port 6379 refuses connections" test_plaintext_port_refused
    _run_test "default user is PING-only (harness identity)" test_default_is_ping_only
    _run_test "wrong password fails closed (WRONGPASS)" test_wrong_password_fails_closed
    _run_test "orchestrator: keyspace-wide + scripting, @dangerous denied" test_orchestrator_broad_but_not_dangerous
    _run_test "mcp-server: get/setex on rerank:* only" test_mcp_scoped_to_rerank_cache
    _run_test "ai-gateway: session/ratelimit patterns + Lua; rerank denied" test_ai_gateway_sessions_and_ratelimit_only
    _run_test "nextcloud: read/write + KEYS carve-out; FLUSHALL denied" test_nextcloud_keys_carveout_no_flush
  else
    _fail "cache container failed to boot"
  fi
else
  printf "\n  ${_YELLOW}Docker daemon unreachable — skipping the 8 dockerized TLS/ACL tests${_RESET}\n"
  printf "  ${_YELLOW}(run on a box with Docker; see the PR's deferred stack-verification section)${_RESET}\n"
  for t in "cache container boots" "plaintext port 6379 refuses connections" \
           "default user is PING-only (harness identity)" "wrong password fails closed (WRONGPASS)" \
           "orchestrator: keyspace-wide + scripting, @dangerous denied" \
           "mcp-server: get/setex on rerank:* only" \
           "ai-gateway: session/ratelimit patterns + Lua; rerank denied" \
           "nextcloud: read/write + KEYS carve-out; FLUSHALL denied"; do
    _skip "$t"
  done
fi

_run_test "compose pins the cache listener to TLSv1.3 (static)" test_compose_pins_tls13

printf "\n  ──────────────────────────────────\n"
printf "  Results: %d/%d passed" "$PASSED" "$TOTAL"
[ "$SKIPPED" -gt 0 ] && printf "  ${_YELLOW}(%d skipped — no docker)${_RESET}" "$SKIPPED"
if [ "$FAILED" -gt 0 ]; then
  printf "  ${_RED}(%d failed)${_RESET}\n" "$FAILED"
  printf "  Failed: %s\n" "${FAILED_NAMES[*]}"
  exit 1
fi
printf "  ${_GREEN}(all runnable passed)${_RESET}\n"
exit 0
