#!/usr/bin/env bash
# =============================================================================
# WARP-570 — Full-device backup (minimum-viable DR)
# =============================================================================
#
# Snapshots ALL core customer-data surfaces into a single timestamped tarball:
#
#   - main orchestrator Postgres   (compose service `db`)         pg_dump
#   - nextcloud-data               volume (files)                 tar
#   - aikeys                       volume (AI provider keys)       tar
#   - matter-data                  volume (Matter fabric+storage)  tar
#   - brain-memory-data            volume (assistant memory)      tar
#   - nvrdata                      volume (NVR recordings)        tar
#   - ops-audit                    volume (WARP-337 audit trail)  tar
#
# The volume names above are the REAL top-level volumes in
# docker/docker-compose.yml — kept in lock-step with the destructive wipe list
# in scripts/factory-reset.sh so the "safety backup before reset" actually
# captures everything the reset destroys. The Postgres volume (pgdata) is NOT
# tarred — it is captured transactionally via pg_dump above. Pure caches /
# rebuildable state (frigate-config, rag-eval-data, model caches, openwrt-*,
# ollama-data) are intentionally NOT backed up. A static test asserts every
# name here exists as a real volume.
#
# This is the device-wide DR artifact. Restic (WARP-254) is the long-term home;
# this is the boring, shell-based MVP that must exist before launch.
#
# Usage:
#   ./scripts/host/device-backup.sh [OUTPUT_DIR]
#
# OUTPUT_DIR defaults to /var/lib/droplet/backups. One tarball per run:
#
#   <OUTPUT_DIR>/device-backup-<YYYYMMDDTHHMMSSZ>-<rand>.tar.gz   (mode 600)
#
# Layout inside:
#   postgres/main.sql.gz          pg_dump of the orchestrator DB | gzip
#   volumes/<name>/data.tar       tar of each named volume's contents
#   manifest.json                 { taken_at, captured[], sizes, image pins }
#
# Rotation: only the newest BACKUP_KEEP (default 7) device-backup-*.tar.gz in
# OUTPUT_DIR are kept; older ones are pruned at the end of a successful run.
#
# Scheduling: a host systemd timer (scripts/host/systemd/droplet-backup.timer)
# runs this daily. See that unit + scripts/README.md. The orchestrator's
# cron-runtime is deliberately NOT used — it runs inside a container and cannot
# pg_dump the sibling DB containers nor write to a host backup path.
#
# Secrets safety (binding): the archive contains DB dumps + the aikeys volume,
# so it is chmod 600 immediately and OUTPUT_DIR is created 700. The repo `.env`
# is NOT copied into the tarball — data-bearing secrets live in volumes and are
# captured there; `.env` is regenerated by setup.sh on reinstall.
#
# Env overrides (defaults match the production compose stack — the test harness
# points these at a disposable project):
#   PROJECT       compose project name for volume prefixes (derived from the
#                 compose `name:` field, default droplet)
#   COMPOSE_FILE  path to the compose file
#   DB_SERVICE    main Postgres service (db)
#   DB_USER       main DB user (falls back to in-container $POSTGRES_USER)
#   DB_NAME       main DB name (falls back to in-container $POSTGRES_DB)
#   BACKUP_KEEP   rotations to retain (7)
#
# Idempotent — concurrent invocations write to distinct files (the filename
# carries a per-run random suffix as well as the timestamp, so two runs in the
# same second cannot overwrite each other).
# Restore via the companion `device-restore.sh`.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

OUTPUT_DIR="${1:-/var/lib/droplet/backups}"
TS="$(date -u +%Y%m%dT%H%M%SZ)"

# Per-run random suffix for the ARCHIVE FILENAME only (TS stays the pure
# timestamp the manifest records as `taken_at`). A second-resolution timestamp
# is NOT unique: two runs that start in the same second resolve to the same
# path and the second one silently OVERWRITES the first — the operator ends up
# with one backup where they believe they have two, and rotation counts one
# fewer restore point than it reports. Real collisions: the rotation drill
# fires four backups back to back, and at boot the systemd timer can coincide
# with an operator-triggered or pre-factory-reset safety backup.
# `|| true` keeps `set -o pipefail` from killing the script on a host without
# /dev/urandom; the PID/RANDOM fallback below covers that case.
RUN_ID="$(od -An -N2 -tx1 /dev/urandom 2>/dev/null | tr -d ' \n' || true)"
[ -n "$RUN_ID" ] || RUN_ID="$(printf '%04x' "$(( (RANDOM ^ $$) & 0xffff ))")"

COMPOSE_FILE="${COMPOSE_FILE:-$REPO_ROOT/docker/docker-compose.yml}"

# Live compose project name. DERIVE it from the compose file's `name:` field
# (pinned `name: droplet`, WARP-187) — never hard-code the RETIRED pre-WARP-605
# `droplet-pi-platform`. Docker prefixes volumes `<project>_<vol>`, so a stale
# default silently targets nonexistent `droplet-pi-platform_*` volumes and backs
# up NOTHING — the same stale-project bug just fixed in factory-reset.sh. An
# explicit PROJECT= override still wins (the test harness points it at a
# disposable project). `|| true` leaves the "compose file not found" check below
# in charge of a missing file rather than dying here under `set -e`/pipefail.
if [ -z "${PROJECT:-}" ]; then
  PROJECT="$(grep -E '^name:[[:space:]]' "$COMPOSE_FILE" 2>/dev/null | head -1 | awk '{gsub(/["\x27]/,"",$2); print $2}' || true)"
fi
PROJECT="${PROJECT:-droplet}"
DB_SERVICE="${DB_SERVICE:-db}"
BACKUP_KEEP="${BACKUP_KEEP:-7}"

# Data volumes to archive. These are the REAL top-level volume names from
# docker/docker-compose.yml (the docker volume is "<PROJECT>_<name>"). They are
# kept in lock-step with scripts/factory-reset.sh's wipe list — anything the
# reset destroys and that holds customer/operator data must be captured here.
# Postgres volumes are excluded (captured via pg_dump); caches are excluded.
DATA_VOLUMES=(
  nextcloud-data
  aikeys
  matter-data
  brain-memory-data
  nvrdata
  ops-audit
)

# Volumes that factory-reset's `down -v` ALSO wipes but that we deliberately do
# NOT back up — recorded verbatim in the manifest as `excluded` so an operator
# can see exactly what a restore will NOT bring back. These are pure caches /
# rebuildable state (regenerated on reinstall), not customer data. Keep in sync
# with factory-reset.sh's wipe list minus DATA_VOLUMES minus the pg_dump'd DBs.
EXCLUDED_VOLUMES=(
  migration-snapshots # WARP-573 pre-migration DB snapshots — regenerated on fresh boot
  frigate-config     # NVR config — regenerated from .env on setup
  rag-eval-data      # RAGAS eval output — not customer data
  whisper-models     # STT model cache (~470MB) — re-downloaded
  piper-voices       # TTS voice cache — re-downloaded
  ollama-data        # local model blobs — re-pulled
  dmr-models         # DMR OCI model store (WARP-1772) — re-pulled, like ollama-data
  openwrt-config     # single-box router config — re-provisioned
  openwrt-overlay    # single-box router overlay — re-provisioned
  switch-state       # managed-switch state — re-provisioned by setup
)

# --- Source logging library if present (matches setup.sh convention) ------
if [ -f "$REPO_ROOT/scripts/lib/logging.sh" ]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/scripts/lib/logging.sh"
else
  log_info()    { printf "  [device-backup] %s\n" "$*"; }
  log_success() { printf "  [device-backup] OK: %s\n" "$*"; }
  log_warn()    { printf "  [device-backup] WARN: %s\n" "$*" >&2; }
  log_error()   { printf "  [device-backup] ERROR: %s\n" "$*" >&2; }
fi

# --- Pre-flight ----------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log_error "docker not on PATH; device-backup requires the compose stack"
  exit 2
fi
if [ ! -f "$COMPOSE_FILE" ]; then
  log_error "compose file not found at $COMPOSE_FILE"
  exit 2
fi

# OUTPUT_DIR holds secrets — keep it owner-only.
mkdir -p "$OUTPUT_DIR"
chmod 700 "$OUTPUT_DIR" 2>/dev/null || true

WORK_DIR="$(mktemp -d -t device-backup-XXXXXXXX)"
trap 'rm -rf "$WORK_DIR"' EXIT

ARCHIVE="$OUTPUT_DIR/device-backup-$TS-$RUN_ID.tar.gz"

dc() { docker compose -p "$PROJECT" -f "$COMPOSE_FILE" "$@"; }

CAPTURED=()

# --- Phase 1: Postgres dumps ---------------------------------------------
mkdir -p "$WORK_DIR/postgres"

dump_pg() {
  # $1 = compose service, $2 = output file, $3 = user override (may be empty),
  # $4 = dbname override (may be empty)
  local svc="$1" out="$2" user="$3" db="$4"
  # Prefer explicit overrides, else read the container's own env vars so we
  # never hard-code credentials. We pass the overrides as container env (-e)
  # and let the in-container shell fall back to the container's own
  # $POSTGRES_USER/$POSTGRES_DB when they're empty — this
  # avoids the fragile nested `${user:-${POSTGRES_USER}}` host-side expansion
  # (a stray `}` leaked into the role name otherwise).
  log_info "Dumping Postgres service '$svc'..."
  if dc exec -T -e "DROPLET_DUMP_USER=$user" -e "DROPLET_DUMP_DB=$db" "$svc" \
       sh -c 'pg_dump --username="${DROPLET_DUMP_USER:-$POSTGRES_USER}" --dbname="${DROPLET_DUMP_DB:-$POSTGRES_DB}" --format=plain --no-owner --no-privileges' \
       | gzip --best > "$out"; then
    log_success "'$svc' dumped ($(wc -c < "$out") bytes gzipped)"
    return 0
  fi
  return 1
}

if ! dump_pg "$DB_SERVICE" "$WORK_DIR/postgres/main.sql.gz" "${DB_USER:-}" "${DB_NAME:-}"; then
  log_error "main Postgres ('$DB_SERVICE') dump failed — aborting (refusing a partial backup)"
  exit 1
fi
CAPTURED+=("postgres:main")

# --- Phase 2: Data volumes -----------------------------------------------
for vol in "${DATA_VOLUMES[@]}"; do
  full="${PROJECT}_${vol}"
  dest="$WORK_DIR/volumes/$vol"
  mkdir -p "$dest"
  # GUARD: `docker run -v <name>:/data` AUTO-CREATES the named volume if it does
  # not exist, which would silently tar an empty volume and mask a typo'd name
  # (the WARP-570 review blocker). Only snapshot volumes that genuinely exist;
  # a truly-absent volume is recorded as EMPTY, never auto-created.
  if ! docker volume inspect "$full" >/dev/null 2>&1; then
    log_warn "volume '$full' absent — skipping (recording EMPTY marker)"
    printf 'volume-absent-at-backup-time\n' > "$dest/EMPTY"
    continue
  fi
  log_info "Snapshotting volume '$full'..."
  # Throwaway sibling container mounts the named volume read-only and tars it,
  # so we don't need the data service running or libs on the host.
  if docker run --rm \
       -v "$full:/data:ro" \
       -v "$dest:/out" \
       alpine:3.20 \
       sh -c 'tar -cf /out/data.tar -C /data . 2>/dev/null'; then
    log_success "volume '$vol' archived ($(wc -c < "$dest/data.tar") bytes)"
    CAPTURED+=("volume:$vol")
  else
    log_error "volume '$full' exists but tar failed — aborting (refusing a partial backup)"
    exit 1
  fi
done

# --- Phase 3: Integrity verification + manifest --------------------------
# Verify every captured artifact is well-formed BEFORE we declare the backup
# good. device-restore.sh re-checks these sha256s before its first DROP
# DATABASE, so a truncated/corrupt artifact can never destroy the live copy.
log_info "Verifying artifact integrity..."

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';
  elif command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}';
  else echo "unavailable"; fi
}

checksums_json=""
add_checksum() {
  # $1 = manifest key (relative path inside the tarball), $2 = file on disk
  local sum; sum="$(sha256_of "$2")"
  checksums_json="$checksums_json\"$1\": \"$sum\","
}

# gzip -t catches a truncated/corrupt dump; abort rather than ship a backup
# that would fail mid-restore after the live DB has already been dropped.
for dump in "$WORK_DIR/postgres/main.sql.gz"; do
  [ -f "$dump" ] || continue
  if ! gzip -t "$dump" 2>/dev/null; then
    log_error "integrity check failed: $(basename "$dump") is not a valid gzip — aborting"
    exit 1
  fi
  add_checksum "postgres/$(basename "$dump")" "$dump"
done
log_success "Postgres dump passes gzip integrity check"

# Record a sha256 for each volume artifact too (verified on restore).
for vol in "${DATA_VOLUMES[@]}"; do
  art="$WORK_DIR/volumes/$vol/data.tar"
  [ -f "$art" ] && add_checksum "volumes/$vol/data.tar" "$art"
done
checksums_json="{${checksums_json%,}}"

log_info "Writing manifest..."
captured_json=""
for c in "${CAPTURED[@]}"; do
  captured_json="$captured_json\"$c\","
done
captured_json="[${captured_json%,}]"

excluded_json=""
for e in "${EXCLUDED_VOLUMES[@]}"; do
  excluded_json="$excluded_json\"$e\","
done
excluded_json="[${excluded_json%,}]"

cat > "$WORK_DIR/manifest.json" <<MANIFEST
{
  "taken_at": "$TS",
  "warp_ticket": "WARP-570",
  "project": "$PROJECT",
  "host": "$(hostname 2>/dev/null || echo unknown)",
  "captured": $captured_json,
  "excluded": $excluded_json,
  "checksums": $checksums_json
}
MANIFEST

# --- Phase 4: Pack -------------------------------------------------------
log_info "Packing archive..."
if ! tar -czf "$ARCHIVE" -C "$WORK_DIR" .; then
  log_error "archive packing failed"
  rm -f "$ARCHIVE"
  exit 1
fi
chmod 600 "$ARCHIVE"

log_success "Backup written: $ARCHIVE"
log_info "  Size: $(wc -c < "$ARCHIVE") bytes"
log_info "  Mode: $(stat -c '%a' "$ARCHIVE" 2>/dev/null || stat -f '%Lp' "$ARCHIVE" 2>/dev/null || echo unknown)"
log_info "  Captured: ${CAPTURED[*]}"

# --- Phase 5: Rotation ---------------------------------------------------
# Keep only the newest BACKUP_KEEP device-backup-*.tar.gz. Newline-safe: our
# own filenames never contain newlines (timestamped), so a simple list is fine.
# Avoid `mapfile` (bash 4+) so this also runs under macOS's bash 3.2 during the
# dev drill; read the newest-first listing line by line instead.
log_info "Pruning to newest $BACKUP_KEEP backups..."
ALL=()
while IFS= read -r line; do
  [ -n "$line" ] && ALL+=("$line")
done < <(ls -1t "$OUTPUT_DIR"/device-backup-*.tar.gz 2>/dev/null || true)
if [ "${#ALL[@]}" -gt "$BACKUP_KEEP" ]; then
  for old in "${ALL[@]:$BACKUP_KEEP}"; do
    rm -f "$old" && log_info "  pruned $(basename "$old")"
  done
fi

log_success "Restore with: ./scripts/host/device-restore.sh $ARCHIVE"
