#!/usr/bin/env bash
# =============================================================================
# WARP-570 — Full-device backup (minimum-viable DR)
# =============================================================================
#
# Snapshots ALL core customer-data surfaces into a single timestamped tarball:
#
#   - main orchestrator Postgres   (compose service `db`)         pg_dump
#   - Plane PM Postgres            (compose service `postgres-pm`) pg_dump
#   - nextcloud-data               volume (files)                 tar
#   - aikeys-data                  volume (AI provider keys)       tar
#   - matter-data                  volume (Matter fabric)         tar
#   - matter-storage-data          volume (Matter storage)        tar
#   - brain-memory-data            volume (assistant memory)      tar
#   - pm-attachments-data          volume (Plane attachments)     tar
#
# Generalizes the per-service `pm-backup.sh` pattern into one device-wide
# artifact. Restic (WARP-254) is the long-term home; this is the boring,
# shell-based MVP that must exist before launch.
#
# Usage:
#   ./scripts/host/device-backup.sh [OUTPUT_DIR]
#
# OUTPUT_DIR defaults to /var/lib/droplet/backups. One tarball per run:
#
#   <OUTPUT_DIR>/device-backup-<YYYYMMDDTHHMMSSZ>.tar.gz   (mode 600)
#
# Layout inside:
#   postgres/main.sql.gz          pg_dump of the orchestrator DB | gzip
#   postgres/pm.sql.gz            pg_dump of the Plane DB | gzip
#   volumes/<name>/data.tar       tar of each named volume's contents
#   manifest.json                 { taken_at, captured[], sizes, image pins }
#
# Rotation: only the newest BACKUP_KEEP (default 7) device-backup-*.tar.gz in
# OUTPUT_DIR are kept; older ones are pruned at the end of a successful run.
#
# Scheduling: a host systemd timer (scripts/host/systemd/droplet-backup.timer)
# runs this daily. See that unit + scripts/README.md. The orchestrator's
# cron-runtime is deliberately NOT used — it runs inside a container and cannot
# pg_dump the sibling DB containers nor write to a host backup path.
#
# Secrets safety (binding): the archive contains DB dumps + the aikeys volume,
# so it is chmod 600 immediately and OUTPUT_DIR is created 700. The repo `.env`
# is NOT copied into the tarball — data-bearing secrets live in volumes and are
# captured there; `.env` is regenerated by setup.sh on reinstall.
#
# Env overrides (defaults match the production compose stack — the test harness
# points these at a disposable project):
#   PROJECT       compose project name for volume prefixes (droplet-pi-platform)
#   COMPOSE_FILE  path to the compose file
#   DB_SERVICE    main Postgres service (db)
#   DB_USER       main DB user (falls back to in-container $POSTGRES_USER)
#   DB_NAME       main DB name (falls back to in-container $POSTGRES_DB)
#   PM_SERVICE    Plane Postgres service (postgres-pm)
#   BACKUP_KEEP   rotations to retain (7)
#
# Idempotent — concurrent invocations write to distinct timestamped files.
# Restore via the companion `device-restore.sh`.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

OUTPUT_DIR="${1:-/var/lib/droplet/backups}"
TS="$(date -u +%Y%m%dT%H%M%SZ)"

PROJECT="${PROJECT:-droplet-pi-platform}"
COMPOSE_FILE="${COMPOSE_FILE:-$REPO_ROOT/docker/docker-compose.yml}"
DB_SERVICE="${DB_SERVICE:-db}"
PM_SERVICE="${PM_SERVICE:-postgres-pm}"
BACKUP_KEEP="${BACKUP_KEEP:-7}"

# Data volumes to archive (logical name -> docker volume is "<PROJECT>_<name>").
DATA_VOLUMES=(
  nextcloud-data
  aikeys-data
  matter-data
  matter-storage-data
  brain-memory-data
  pm-attachments-data
)

# --- Source logging library if present (matches setup.sh convention) ------
if [ -f "$REPO_ROOT/scripts/lib/logging.sh" ]; then
  # shellcheck disable=SC1091
  source "$REPO_ROOT/scripts/lib/logging.sh"
else
  log_info()    { printf "  [device-backup] %s\n" "$*"; }
  log_success() { printf "  [device-backup] OK: %s\n" "$*"; }
  log_warn()    { printf "  [device-backup] WARN: %s\n" "$*" >&2; }
  log_error()   { printf "  [device-backup] ERROR: %s\n" "$*" >&2; }
fi

# --- Pre-flight ----------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  log_error "docker not on PATH; device-backup requires the compose stack"
  exit 2
fi
if [ ! -f "$COMPOSE_FILE" ]; then
  log_error "compose file not found at $COMPOSE_FILE"
  exit 2
fi

# OUTPUT_DIR holds secrets — keep it owner-only.
mkdir -p "$OUTPUT_DIR"
chmod 700 "$OUTPUT_DIR" 2>/dev/null || true

WORK_DIR="$(mktemp -d -t device-backup-XXXXXXXX)"
trap 'rm -rf "$WORK_DIR"' EXIT

ARCHIVE="$OUTPUT_DIR/device-backup-$TS.tar.gz"

dc() { docker compose -p "$PROJECT" -f "$COMPOSE_FILE" "$@"; }

CAPTURED=()

# --- Phase 1: Postgres dumps ---------------------------------------------
mkdir -p "$WORK_DIR/postgres"

dump_pg() {
  # $1 = compose service, $2 = output file, $3 = user override (may be empty),
  # $4 = dbname override (may be empty)
  local svc="$1" out="$2" user="$3" db="$4"
  local userexpr dbexpr
  # Prefer explicit overrides, else read the container's own env vars so we
  # never hard-code credentials (mirrors pm-backup.sh).
  userexpr="${user:-\${POSTGRES_USER}}"
  dbexpr="${db:-\${POSTGRES_DB}}"
  log_info "Dumping Postgres service '$svc'..."
  if dc exec -T "$svc" \
       sh -c "pg_dump --username=\"$userexpr\" --dbname=\"$dbexpr\" --format=plain --no-owner --no-privileges" \
       | gzip --best > "$out"; then
    log_success "'$svc' dumped ($(wc -c < "$out") bytes gzipped)"
    return 0
  fi
  return 1
}

if ! dump_pg "$DB_SERVICE" "$WORK_DIR/postgres/main.sql.gz" "${DB_USER:-}" "${DB_NAME:-}"; then
  log_error "main Postgres ('$DB_SERVICE') dump failed — aborting (refusing a partial backup)"
  exit 1
fi
CAPTURED+=("postgres:main")

if dump_pg "$PM_SERVICE" "$WORK_DIR/postgres/pm.sql.gz" "" ""; then
  CAPTURED+=("postgres:pm")
else
  log_warn "Plane Postgres ('$PM_SERVICE') not present — skipping (PM stack not provisioned?)"
  printf 'pm-postgres-absent-at-backup-time\n' > "$WORK_DIR/postgres/pm.ABSENT"
fi

# --- Phase 2: Data volumes -----------------------------------------------
for vol in "${DATA_VOLUMES[@]}"; do
  full="${PROJECT}_${vol}"
  dest="$WORK_DIR/volumes/$vol"
  mkdir -p "$dest"
  log_info "Snapshotting volume '$full'..."
  # Throwaway sibling container mounts the named volume read-only and tars it,
  # so we don't need the data service running or libs on the host.
  if docker run --rm \
       -v "$full:/data:ro" \
       -v "$dest:/out" \
       alpine:3.20 \
       sh -c 'tar -cf /out/data.tar -C /data . 2>/dev/null'; then
    log_success "volume '$vol' archived ($(wc -c < "$dest/data.tar") bytes)"
    CAPTURED+=("volume:$vol")
  else
    log_warn "volume '$full' absent or empty — skipping"
    printf 'volume-absent-at-backup-time\n' > "$dest/EMPTY"
  fi
done

# --- Phase 3: Manifest ---------------------------------------------------
log_info "Writing manifest..."
captured_json=""
for c in "${CAPTURED[@]}"; do
  captured_json="$captured_json\"$c\","
done
captured_json="[${captured_json%,}]"

cat > "$WORK_DIR/manifest.json" <<MANIFEST
{
  "taken_at": "$TS",
  "warp_ticket": "WARP-570",
  "project": "$PROJECT",
  "host": "$(hostname 2>/dev/null || echo unknown)",
  "captured": $captured_json
}
MANIFEST

# --- Phase 4: Pack -------------------------------------------------------
log_info "Packing archive..."
if ! tar -czf "$ARCHIVE" -C "$WORK_DIR" .; then
  log_error "archive packing failed"
  rm -f "$ARCHIVE"
  exit 1
fi
chmod 600 "$ARCHIVE"

log_success "Backup written: $ARCHIVE"
log_info "  Size: $(wc -c < "$ARCHIVE") bytes"
log_info "  Mode: $(stat -c '%a' "$ARCHIVE" 2>/dev/null || stat -f '%Lp' "$ARCHIVE" 2>/dev/null || echo unknown)"
log_info "  Captured: ${CAPTURED[*]}"

# --- Phase 5: Rotation ---------------------------------------------------
# Keep only the newest BACKUP_KEEP device-backup-*.tar.gz. Newline-safe: our
# own filenames never contain newlines (timestamped), so a simple list is fine.
log_info "Pruning to newest $BACKUP_KEEP backups..."
mapfile -t ALL < <(ls -1t "$OUTPUT_DIR"/device-backup-*.tar.gz 2>/dev/null || true)
if [ "${#ALL[@]}" -gt "$BACKUP_KEEP" ]; then
  for old in "${ALL[@]:$BACKUP_KEEP}"; do
    rm -f "$old" && log_info "  pruned $(basename "$old")"
  done
fi

log_success "Restore with: ./scripts/host/device-restore.sh $ARCHIVE"
