d /run/droplet 0777 root root -
d /run/droplet-storage-ops 0750 root droplet -
z /run/droplet-storage-ops 0750 root droplet -
f /run/droplet-storage-ops/recordings-topology.lock 0660 root droplet - -
z /run/droplet-storage-ops/recordings-topology.lock 0660 root droplet - -
