import { z } from "zod";

// WARP-580 — production JWT-secret strength guard. A production boot must
// reject a secret that is too short OR is one of the shipped dev placeholders
// (a copy-paste from .env.example is the realistic foot-gun). setup.sh mints a
// 64-byte hex value, so a real deployment clears 32 chars with room to spare.
const JWT_SECRET_MIN_LENGTH = 32;
const KNOWN_DEV_JWT_SECRETS: readonly string[] = [
  "dev-jwt-secret-do-not-use-in-production",
  "changeme",
  "secret",
  "your-secret-here",
];

/** PURE — true when `s` is unfit for production use. Exported for tests. */
export function isWeakJwtSecret(s: string): boolean {
  return s.length < JWT_SECRET_MIN_LENGTH || KNOWN_DEV_JWT_SECRETS.includes(s);
}

/**
 * WARP-580 — resolve the EFFECTIVE auth posture (fail-closed).
 *
 * Auth is on unless an operator EXPLICITLY opts out in a non-production
 * environment. We read the LITERAL env string here rather than zod's coerced
 * boolean: `z.coerce.boolean()` runs JS `Boolean(...)`, so the string "false"
 * (non-empty) coerces to TRUE — it cannot represent an explicit opt-out. The
 * opt-out is therefore an explicit falsey token ("false"/"0"/"no"/"off",
 * case-insensitive); anything else (including an absent var) stays ON. In
 * production we force-ON regardless of the var, so the middleware's
 * owner-injection-when-disabled branch can never fire on a shipped box even if
 * `.env` carries a stale `AUTH_ENABLED=false`.
 */
const FALSEY_ENV_TOKENS: ReadonlySet<string> = new Set(["false", "0", "no", "off"]);
export function resolveAuthEnabled(
  rawAuthEnv: string | undefined,
  nodeEnv: string,
): boolean {
  // Production: fail-closed — auth is always on.
  if (nodeEnv === "production") return true;
  // Non-production: honour an EXPLICIT falsey opt-out only. An unset var stays ON.
  if (rawAuthEnv !== undefined && FALSEY_ENV_TOKENS.has(rawAuthEnv.trim().toLowerCase())) {
    return false;
  }
  return true;
}

const envSchema = z.object({
  DATABASE_URL: z.string().default("postgresql://droplet:droplet@localhost:5432/droplet"),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  MQTT_BROKER: z.string().default("mqtt://localhost:1883"),
  AI_GATEWAY_URL: z.string().default("http://localhost:8000"),
  PORT: z.coerce.number().default(3000),
  NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  MAX_UPLOAD_SIZE_MB: z.coerce.number().default(100),

  // --- CORS (WARP-562) ---
  // Comma-separated allowlist of browser Origins permitted to make
  // credentialed cross-origin requests against the orchestrator API. We keep
  // `credentials: true` (cookie-based `droplet_session` auth), so the allowlist
  // MUST be exact-match — never `origin: true`, which reflects any Origin and
  // hands `Access-Control-Allow-Origin: <attacker>` +
  // `Access-Control-Allow-Credentials: true` to any site the owner visits.
  //
  // Parsed into `config.corsAllowedOrigins` below. When unset it defaults to
  // the appliance's LAN dashboard origin (https://droplet-ai.local — already
  // covered by the TLS cert SANs, see DROPLET_PM_WEB_URL and
  // scripts/lib/secrets.sh) plus http://localhost:3000 in non-production for
  // the Next.js dev server. A `*` value is rejected at startup (see the
  // wildcard guard after parse), mirroring services/ai-gateway/main.py.
  CORS_ALLOWED_ORIGINS: z.string().default(""),

  // --- Nextcloud (single file storage backend) ---
  NEXTCLOUD_URL: z.string().default("http://localhost:8080"),
  // WARP-580 — auth is FAIL-CLOSED. The default is `true`; the only way to run
  // with auth off is an EXPLICIT `AUTH_ENABLED=false` AND a non-production
  // NODE_ENV (see resolveAuthEnabled below). A bare/missing var, or `=false`
  // in production, both resolve to auth ENABLED. The middleware's
  // owner-injection-when-disabled path (middleware/auth.ts) therefore can
  // never fire in production. Parsed here as the raw operator INTENT; the
  // effective value is `config.AUTH_ENABLED` after resolveAuthEnabled.
  AUTH_ENABLED: z.coerce.boolean().default(true),

  // --- Device pairing ---
  // 32-byte base64 key used to encrypt per-device Nextcloud app passwords
  // at rest. Generated by scripts/setup.sh alongside other secrets. Empty
  // default lets tests run without setting the env var; production fails
  // closed via encryption.service.ts when the key is missing.
  DEVICE_SECRET_KEY: z.string().default(""),

  // --- Matter (host-network sidecar client, WARP-850) ---
  //
  // DO NOT ADD NEW `MATTER_*` ENV VARS — ANYWHERE IN THE STACK.
  //
  // matter.js scans the entire process.env for `MATTER_*` at startup
  // (NodeJsEnvironment.js → vars.addUnixEnvStyle(process.env)) and folds
  // each one into its internal VariableService under a dot-namespaced
  // key (`MATTER_CONTROLLER_NAME` → var `controller.name`), which can
  // collide with root-node behavior schemas and crash controller init
  // with UnsupportedCastError. matter.js no longer runs in THIS process
  // — it moved to services/matter-controller (WARP-850) — but the rule
  // still applies there, and scripts/test-security.sh enforces it
  // repo-wide. `MATTER_STORAGE_PATH` is the single allow-listed
  // survivor and now lives in the sidecar's env (it deliberately folds
  // to matter.js's `storage.path`, pointing the fabric storage at the
  // matter-data volume).
  //
  // The orchestrator is now an HTTP client of the sidecar
  // (services/matter.service.ts). Same host-gateway rationale as
  // ROUTING_SERVICE_URL: the sidecar runs with `network_mode: host`
  // (raw HCI for BLE + native LAN mDNS), so the bridged orchestrator
  // reaches it via host.docker.internal on the host-service port
  // ladder (routing 8080, switch 8081, display 8082 → matter 8083).
  DROPLET_MATTER_SERVICE_URL: z
    .string()
    .default("http://host.docker.internal:8083"),
  // Shared bearer presented in the X-Droplet-Auth header (device-bridge
  // precedent). Generated by scripts/setup.sh into .env; the sidecar
  // fails closed (401s everything) when its copy is empty. Rotate both
  // sides in lockstep — orchestrator + matter-controller read the same
  // .env key via compose.
  DROPLET_MATTER_SERVICE_TOKEN: z.string().default(""),

  // --- WARP-505/506/507/511 — embedded Plane PM stack (ADR-010, spec WARP-498) ---
  // All vars use DROPLET_PM_* prefix per architecture-guard rule 11.
  // Defaults work on a brand-new install OR fail loud (rule 14).
  DROPLET_PM_API_URL: z.string().url().default("http://pm-api:8000"),
  // Plane's dedicated TLS origin (spec WARP-498 OQ2 amendment): the vanilla
  // frontend is built with basePath:"" so it must own an origin root — the
  // gateway serves it on :8443, not under /pm/.
  DROPLET_PM_WEB_URL: z.string().url().default("https://droplet-ai.local:8443"),
  // WARP-867: NOT a Plane API key — Plane CE only authenticates its own
  // server-generated service tokens, which pm-bootstrap.service mints at
  // runtime and serves via GET /api/pm/service-token. This secret is the
  // seed for the bootstrap admin identity (the Plane admin password is
  // HMAC-derived from it — see planeAdminPassword()).
  DROPLET_PM_ADMIN_TOKEN: z.string().default(""),
  // WARP-860 — identity of the auto-bootstrapped Plane instance admin.
  // Plane CE has no OIDC and no headless setup, so pm-bootstrap.service.ts
  // completes the god-mode instance setup programmatically with this email
  // and a password derived from DROPLET_PM_ADMIN_TOKEN. The owner signs in
  // to the embedded Plane with these credentials (surfaced once in the
  // setup wizard's PM step).
  DROPLET_PM_ADMIN_EMAIL: z.string().email().default("admin@droplet.local"),
  // HMAC signing key for Plane → orchestrator webhooks (WARP-511).
  // Empty default = webhook receiver fail-CLOSED (every payload 401s) per
  // engineering-handbook 04-coding-standards/security-rules.md §1.
  DROPLET_PM_WEBHOOK_SECRET: z.string().default(""),
  // WARP-505 OIDC IdP (spec WARP-498 OQ6). The orchestrator runs a minimal
  // OIDC provider that Plane points at as its relying-party IdP. ID tokens
  // are signed RS256 (HMAC won't work — Plane verifies via JWKS). setup.sh
  // generates a 2048-bit RSA keypair on first run and pins both halves
  // below. Empty defaults make the OIDC endpoints 500 with a clear error
  // (signIdToken throws) until setup.sh has populated .env.
  DROPLET_PM_OIDC_PRIVATE_KEY_PEM: z.string().default(""),
  DROPLET_PM_OIDC_KID: z.string().default(""),
  DROPLET_PM_OIDC_CLIENT_ID: z.string().default("plane"),
  DROPLET_PM_OIDC_CLIENT_SECRET: z.string().default(""),

  // --- JWT ---
  // In production this must be set — setup.sh generates a 64-byte random hex value.
  // The default is intentionally weak so tests work without env setup.
  //
  // WARP-580 — production secret-strength guard. In production the secret must
  // be at least JWT_SECRET_MIN_LENGTH chars AND must not match any known dev
  // placeholder. Outside production the weak default is allowed so tests + dev
  // laptops run without env setup. The refine runs at parse time (config load),
  // so a misconfigured production boot dies loud before serving a request.
  JWT_SECRET: z
    .string()
    .default("dev-jwt-secret-do-not-use-in-production")
    .refine(
      (s) => process.env.NODE_ENV !== "production" || !isWeakJwtSecret(s),
      `JWT_SECRET must be a strong random value in production (at least ${JWT_SECRET_MIN_LENGTH} characters and not a dev placeholder)`,
    ),

  // --- OAuth2 ---
  AUTH_MODE: z.enum(["oauth2", "legacy"]).default("legacy"),
  OAUTH2_CLIENT_ID: z.string().default(""),
  OAUTH2_CLIENT_SECRET: z.string().default(""),

  // --- SSO (external-IdP OIDC: Google Workspace + Microsoft Entra) ---
  // ADR-013 (PR #378). The orchestrator acts as an OIDC RELYING PARTY (the
  // mirror of the DROPLET_PM_OIDC_* block above, where it is the IdP). One
  // group of four vars per provider; ALL FOUR must be set for that provider's
  // SSO button to go live (getOidcProviderConfig fails closed otherwise —
  // half-configured providers render disabled). Empty defaults keep tests +
  // un-configured appliances from minting half-built authorize URLs.
  //
  // The CLIENT_SECRET values are real provider secrets — they live ONLY in
  // `.env` (populated by the operator / setup.sh; never tracked) exactly like
  // OAUTH2_CLIENT_SECRET and DROPLET_PM_OIDC_CLIENT_SECRET. They are read here
  // and never re-emitted, never logged.
  //
  // ISSUER is the provider's discovery base; openid-client appends
  // /.well-known/openid-configuration and pulls the JWKS from it (ID-token
  // signature validation). No host is hardcoded in code — the issuer is the
  // single source.
  //   - Google:  https://accounts.google.com
  //   - Entra:   https://login.microsoftonline.com/<tenant>/v2.0
  //   - Okta:    https://<org>.okta.com/oauth2/<authServerId> (or the org
  //              root issuer when no custom authorization server is used)
  // REDIRECT_URI must exactly match the redirect registered at the IdP and the
  // /api/sso/oidc/callback route this orchestrator serves.
  DROPLET_SSO_GOOGLE_ISSUER: z.string().default(""),
  DROPLET_SSO_GOOGLE_CLIENT_ID: z.string().default(""),
  DROPLET_SSO_GOOGLE_CLIENT_SECRET: z.string().default(""),
  DROPLET_SSO_GOOGLE_REDIRECT_URI: z.string().default(""),
  DROPLET_SSO_ENTRA_ISSUER: z.string().default(""),
  DROPLET_SSO_ENTRA_CLIENT_ID: z.string().default(""),
  DROPLET_SSO_ENTRA_CLIENT_SECRET: z.string().default(""),
  DROPLET_SSO_ENTRA_REDIRECT_URI: z.string().default(""),
  // WARP — Okta SSO. Okta is a plain OIDC provider; the orchestrator reuses
  // the same authorize/callback RP path as Google/Entra (sso-oidc.service.ts
  // / routes/sso.ts). All four must be set for the Okta button to go live.
  DROPLET_SSO_OKTA_ISSUER: z.string().default(""),
  DROPLET_SSO_OKTA_CLIENT_ID: z.string().default(""),
  DROPLET_SSO_OKTA_CLIENT_SECRET: z.string().default(""),
  DROPLET_SSO_OKTA_REDIRECT_URI: z.string().default(""),

  // --- SCIM 2.0 directory provisioning (Okta pushes users/groups here) ---
  // WARP — Okta's SCIM client authenticates to /scim/v2/* with a DEDICATED
  // provisioning bearer token (NOT a user session, NOT one of the
  // SERVICE_TOKEN_* principals — those carry the `service` ROLE for inbound
  // LLM/tool calls; SCIM provisioning is a separate trust boundary with its
  // own secret and its own middleware). This is the SCIM bearer; it is
  // validated (constant-time) on EVERY SCIM request and NEVER logged.
  //
  // EMPTY DEFAULT = FAIL CLOSED: with no token configured, every /scim/v2/*
  // request 401s (scim-auth middleware refuses an unset secret), so an
  // appliance that hasn't been wired for directory sync never accepts an
  // unauthenticated — or empty-bearer — provisioning call. Same posture as
  // DROPLET_PM_WEBHOOK_SECRET. Lives ONLY in .env (operator / setup.sh
  // generates it); never tracked, never re-emitted.
  DROPLET_SCIM_BEARER_TOKEN: z.string().default(""),

  // --- gRPC ---
  AI_GATEWAY_GRPC_URL: z.string().default("localhost:50051"),

  // --- OpenWrt Routing ---
  // Default uses `host.docker.internal` so the bridged orchestrator can
  // reach the routing service, which runs with `network_mode: host` (bound
  // to the appliance host's :8080). `localhost` would be the orchestrator
  // container itself and never resolve to :8080. The orchestrator compose
  // service wires `host.docker.internal` via `extra_hosts: host-gateway`.
  ROUTING_SERVICE_URL: z.string().default("http://host.docker.internal:8080"),
  // Shared bearer token for routing service (generated by scripts/setup.sh).
  // Empty default lets tests and dev laptops run without setup; routing service
  // rejects empty tokens when its own value is set.
  ROUTING_SERVICE_TOKEN: z.string().default(""),
  // WARP-44: `real` (default) talks to the routing service normally.
  // `mock` is equivalent on the orchestrator side — routing itself is
  // configured to serve fixtures.
  // `disabled` short-circuits every openwrt.client call with
  // RouterError.disabled() so the dashboard renders a "Router supervision
  // disabled" banner instead of spamming retries at a non-existent service.
  ROUTING_MODE: z.enum(["real", "mock", "disabled"]).default("real"),

  // --- WireGuard / Remote Access ---
  // Hostname or IP that peer .conf files use as their `Endpoint`. Should be
  // reachable from outside the LAN — typically a DuckDNS subdomain (Phase 4)
  // or your home router's public IP. For inside-LAN testing you can set this
  // to the OpenWrt LAN IP (192.168.50.1). Empty default makes the orchestrator
  // refuse to mint peers with a clear error rather than handing out unusable
  // configs that point at "example.com" or similar.
  WIREGUARD_ENDPOINT_HOST: z.string().default(""),
  // VPN tunnel subnet. The server takes .1, peers get .2 through .254. Must
  // not collide with the LAN (192.168.50.0/24) or cameras (192.168.100.0/24).
  WIREGUARD_VPN_SUBNET: z.string().default("10.13.13.0/24"),
  WIREGUARD_LISTEN_PORT: z.coerce.number().default(51820),
  // CIDR + DNS server that the rendered peer .conf advertises to the client.
  // Defaults match the OpenWrt LAN. Override if the LAN is reconfigured.
  WIREGUARD_LAN_CIDR: z.string().default("192.168.50.0/24"),
  WIREGUARD_DNS: z.string().default("192.168.50.1"),

  // --- Public-CA per-device TLS (ADR-023) ---
  // DROPLET_PUBLIC_FQDN — the opaque per-device subdomain
  //   `d-<hmac>.devices.warp-lab.ai`. The box CANNOT compute the HQ-keyed HMAC,
  //   so it learns this from the HQ challenge response and persists it back to
  //   .env (scripts/lib/secrets.sh). Empty until first HQ contact — the
  //   tls-issuance cron is a no-op while empty and the bootstrap self-signed
  //   cert keeps the box serving TLS. When set it is the TOP-priority canonical
  //   origin (trusted-origin.ts) and the one address that works at home AND
  //   over the WireGuard tunnel.
  DROPLET_PUBLIC_FQDN: z.string().default(""),
  // DROPLET_PUBLIC_FQDN_IP — the IP the per-device FQDN resolves to via the
  //   split-horizon dnsmasq (ADR-023 C3). Defaults to the WireGuard gateway
  //   address 192.168.20.1, which is reachable on the single-box LAN AND over
  //   the tunnel, so the one FQDN works at home and remotely. The routing-leg
  //   registrar (createRoutingDnsRegistrar) POSTs {hostname, ip} to
  //   /dhcp/hostnames with this value; matches the host-leg default in
  //   scripts/lib/local-dns.sh::setup_public_fqdn_dns. Operators on a multi-box
  //   LAN whose box IP differs can override it.
  DROPLET_PUBLIC_FQDN_IP: z.string().default("192.168.20.1"),
  // HQ_ISSUANCE_URL — base URL of the fleet HQ issuance API
  //   (hq.warp-lab.com). Plain outbound HTTPS; does NOT require the fleet
  //   WireGuard tunnel. Empty disables live issuance (the cron skips), which is
  //   the correct posture for dev laptops + CI.
  HQ_ISSUANCE_URL: z.string().default(""),
  // DROPLET_DEVICE_ID — the device's HQ registry id. Mirrors the value the
  //   device-identity sidecar reads (docker-compose.yml). Defaults to the
  //   hostname-derived `droplet` placeholder (matches scripts/lib/secrets.sh).
  DROPLET_DEVICE_ID: z.string().default("droplet"),

  // --- Coverage extender APs (WARP-446) ---
  // Per ADR-005. `DROPLET_AP_*` prefix is mandatory (see the long
  // MATTER_* warning above for why — same risk).
  //
  // DISCOVERY_INTERVAL — mDNS scan cadence in seconds. The orchestrator's
  //   discovery poller (cron-runtime.service.ts) queries
  //   `_droplet-ap._tcp.local` and upserts each new MAC into ApDevice.
  //   10s tracks new-AP-plugged-in within the 30s AC #1 budget.
  // APPROVAL_TIMEOUT — safe_apply timeout passed to the routing service
  //   on POST /aps/:mac/approve. 60s matches the rest of the codebase's
  //   confirmation-token TTL convention (WARP-41).
  // DAWN_ENABLED — master switch to disable dawn on every AP. Default on.
  //   Off only as a debugging escape hatch when an operator suspects
  //   dawn is the cause of an issue.
  // DEFAULT_TXPOWER — dBm cap on extender radios. Keeps household-floor
  //   cells small enough for clean roaming.
  DROPLET_AP_DISCOVERY_INTERVAL: z.coerce.number().default(10),
  DROPLET_AP_APPROVAL_TIMEOUT: z.coerce.number().default(60),
  DROPLET_AP_DAWN_ENABLED: z.coerce.boolean().default(true),
  DROPLET_AP_DEFAULT_TXPOWER: z.coerce.number().default(20),

  // --- ADR-024 multi-backend coverage APs (Phase 2) ---
  // Master switches for the third-party AP discovery backends. Both
  // default OFF — a single-box with no extenders ships exactly as today
  // (only the mDNS / DROPLET_IMAGE source runs). When off, the EasyMesh /
  // UniFi discovery sources return [] and contribute nothing.
  //
  // EASYMESH_ENABLED — turns on the IEEE 1905.1 discovery + prplMesh
  //   Controller-only onboarding path (ADR-024 §2). Real socket logic
  //   lands in Phase 4; this phase the source is a scaffold.
  // UNIFI_ENABLED — turns on the UBNT UDP 10001 discovery + UniFi Network
  //   API adoption path (ADR-024 §3). Real adapter lands in Phase 3.
  //
  // EXPLICIT string→bool (same idiom as DROPLET_CLAIM_GATE_ENABLED below):
  // z.coerce.boolean() would treat the non-empty strings "0"/"false" as
  // true and silently enable a backend. Only "1"/"true" enable it; an
  // absent var or anything else leaves it OFF.
  DROPLET_AP_EASYMESH_ENABLED: z
    .string()
    .default("0")
    .transform((v) => v === "1" || v.trim().toLowerCase() === "true"),
  DROPLET_AP_UNIFI_ENABLED: z
    .string()
    .default("0")
    .transform((v) => v === "1" || v.trim().toLowerCase() === "true"),

  // ADR-024 Phase 4 (§2) — the box runs prplMesh in CONTROLLER-ONLY mode (its
  // mt76 radio can't be an EasyMesh RF agent; the certified third-party AP is
  // the Agent). This points the orchestrator's EASYMESH backend at the LOCAL
  // prplMesh controller's ubus / IPC data-model endpoint (e.g. its
  // ubus-over-HTTP address or socket path). The controller is a loopback/LAN
  // local service, so this is an ADDRESS — not a secret — declared the same
  // plain-string-empty-default way as DROPLET_AP_UNIFI_CONTROLLER_URL.
  //
  // Empty default: an unconfigured box's EasyMesh client throws NOT_CONFIGURED,
  // but the discovery source only calls it when DROPLET_AP_EASYMESH_ENABLED is
  // on (default off), so a default single-box never touches it.
  DROPLET_AP_EASYMESH_CONTROLLER_URL: z.string().default(""),

  // ADR-024 Phase 3 (§3 + §"Open decision" Option B) — the box is a pure API
  // CLIENT to a UniFi Network controller the household ALREADY runs (a UDM /
  // CloudKey / self-host). We do NOT bundle or redistribute the controller;
  // these two vars point Droplet at the customer-supplied one.
  //
  // CONTROLLER_URL — local controller base URL (e.g. https://127.0.0.1:8443).
  //   Empty default: an unconfigured box's UniFi client throws NOT_CONFIGURED,
  //   but the discovery source only calls it when DROPLET_AP_UNIFI_ENABLED is
  //   on, so a default single-box never touches it.
  // API_KEY — **SECRET**. The official local API's API key (the 2024 key-auth
  //   surface; the legacy :8443 login-cookie flow is NOT used). Sourced from
  //   the secret store / .env, NEVER a tracked default — declared the same way
  //   as every other secret here (DROPLET_PM_WEBHOOK_SECRET, ROUTING_SERVICE_
  //   TOKEN, …): a plain string defaulting to empty. Never logged.
  DROPLET_AP_UNIFI_CONTROLLER_URL: z.string().default(""),
  DROPLET_AP_UNIFI_API_KEY: z.string().default(""),

  // --- Front-panel claim gate (WARP-165) ---
  // Physical-presence gate for POST /auth/setup: when ON, the first-owner
  // request must carry the claim code shown on the device's front panel
  // (verified read-only against the persisted ClaimCode — WARP-632/ADR-017
  // primitives), proving the operator is physically at the box and not merely
  // on its LAN. Closes the first-boot window where ANY LAN client could create
  // the owner before a physical operator does.
  //
  // DEFAULT OFF — a half-shipped gate (panel/firmware not yet present, or a
  // dashboard build that doesn't send the field) must never lock a user out of
  // their own box; existing setups stay back-compatible. Flip on only once the
  // panel CLAIM screen and the dashboard /setup code field both ship.
  //
  // EXPLICIT string→bool, NOT z.coerce.boolean(): coerce runs Boolean(...), so
  // the non-empty strings "0"/"false" would BOTH coerce to true and could
  // silently ENABLE the gate (a lockout foot-gun). Only "1"/"true" enable it;
  // anything else (including an absent var) leaves it OFF.
  DROPLET_CLAIM_GATE_ENABLED: z
    .string()
    .default("0")
    .transform((v) => v === "1" || v.trim().toLowerCase() === "true"),

  // WARP-586: retention window (days) for the append-only audit/log tables
  // ActivityRow, CommandAuditLog, NotificationLog. The daily 03:00 cron
  // (index.ts) deletes rows older than this. 90 days balances "enough
  // history for the dashboard's activity feed + an incident look-back"
  // against unbounded table growth. Set 0 to disable the purge entirely —
  // the safe "keep forever" stance, NOT a sentinel: 0 parses here and
  // audit-retention-purge.service.ts treats <= 0 as "skip" (defense in
  // depth). A negative window is nonsensical input, so the schema rejects
  // it at startup (fail fast) rather than silently treating it as disable;
  // .int() rejects sub-day floats and .finite() rejects Infinity.
  DROPLET_AUDIT_RETENTION_DAYS: z.coerce.number().int().min(0).finite().default(90),

  // WARP-808: which deployment shape broadcasts the home Wi-Fi AP. This is the
  // SAME knob the device-bridge reads (services/oled-display/device-bridge.py)
  // and that single-box.sh's configure_single_box_env upserts into .env.
  //   uci      — multi-box: a router-host OpenWrt holds the AP in UCI. Home
  //              Wi-Fi SSID/PSK writes go through the routing service (UCI/SSH),
  //              exactly as before. This is the back-compat default.
  //   hostapd  — single-box: the host runs a raw hostapd AP (no UCI), so a UCI
  //              write hits a nonexistent section (ubus NOT_FOUND → 500).
  //              network.service routes the SSID/PSK write through the
  //              device-bridge's POST /openwrt/wifi/hostapd instead.
  //   auto     — reserved for the bridge's auto-detect; the orchestrator treats
  //              anything other than "hostapd" as the UCI path (a box that wants
  //              the hostapd write path sets DROPLET_AP_MODE=hostapd explicitly,
  //              which single-box.sh does).
  // Defaulting to `uci` keeps every multi-box install behaving exactly as before.
  DROPLET_AP_MODE: z.enum(["uci", "hostapd", "auto"]).default("uci"),

  // --- Document server (WARP-882 / WS-4 — in-browser editing + co-authoring) ---
  // The Droplet integrates an OnlyOffice Document Server (the ENGINE) via the
  // Nextcloud `onlyoffice` connector over a WOPI-style handshake. The engine is
  // a CONFIG choice, not a code dependency (docserver.client.ts stays
  // engine-agnostic), so swapping it needs only these vars.
  //
  // DOCS_INTERNAL_URL — internal (compose-network) base URL of the Document
  //   Server, e.g. http://docserver. EMPTY default = the engine is UNAVAILABLE:
  //   docServerHealthy() returns false and /files/docs/status reports
  //   "unavailable", so a box that hasn't enabled the `docs` compose profile
  //   degrades cleanly instead of dialing a non-existent host.
  DOCS_INTERNAL_URL: z.string().default(""),
  // DOCS_ENABLED — EXPLICIT master switch, deliberately NOT derived from
  //   DOCS_INTERNAL_URL emptiness (handbook "state is explicit, never inferred
  //   from absence"). Same string→bool idiom as DROPLET_CLAIM_GATE_ENABLED:
  //   z.coerce.boolean() would treat "0"/"false" as true. The 32 GB box runs
  //   docs DEFAULT-ON, so this defaults to "1"; a ≤8 GB box sets DOCS_ENABLED=0
  //   (and drops `docs` from COMPOSE_PROFILES) to reclaim the ~2 GB engine.
  //   Only "1"/"true" enable it; an absent var defaults ON via the "1" default.
  DOCS_ENABLED: z
    .string()
    .default("1")
    .transform((v) => v === "1" || v.trim().toLowerCase() === "true"),
  // DOCS_EDITOR_PUBLIC_PATH — public path the gateway fronts the Document
  //   Server on (nginx `location /docs/`). Used to build browser-facing URLs;
  //   the WebSocket co-authoring channel rides this path.
  DOCS_EDITOR_PUBLIC_PATH: z.string().default("/docs/"),
  // DOCS_ACCESS_TOKEN_TTL_SECONDS — lifetime of the per-session editor access
  //   token. The dashboard refreshes before expiry. 30 min balances "long
  //   enough for a real editing session" against "short enough that a leaked
  //   token expires".
  DOCS_ACCESS_TOKEN_TTL_SECONDS: z.coerce.number().int().positive().default(1800),
  // ONLYOFFICE_JWT_SECRET — shared HS256 secret the Document Server, the
  //   Nextcloud connector, AND this orchestrator all verify. Generated by
  //   scripts/setup.sh into .env; lives ONLY there (never tracked), never
  //   logged. Empty default keeps tests/dev laptops running; the connector +
  //   engine reject unsigned requests when their copy is set.
  ONLYOFFICE_JWT_SECRET: z.string().default(""),

  // --- File indexer (WARP-287 re-index + WARP-598 health probe) ---
  FILE_INDEXER_URL: z.string().default("http://file-indexer:8090"),

  // --- Frigate NVR ---
  FRIGATE_URL: z.string().default("http://localhost:5000"),
  CAMERA_DISCOVERY_URL: z.string().default("http://localhost:8085"),

  // --- Managed Switch ---
  // Same rationale as ROUTING_SERVICE_URL above: switch runs with
  // `network_mode: host`, so the bridged orchestrator must reach it via
  // the host gateway.
  SWITCH_SERVICE_URL: z.string().default("http://host.docker.internal:8081"),

  // --- OLED / TFT Display ---
  // Same rationale again: the display service runs with `network_mode: host`
  // on the appliance (uvicorn on :8082). `localhost` inside the orchestrator
  // container would never resolve to it, so default to the host gateway.
  DISPLAY_SERVICE_URL: z.string().default("http://host.docker.internal:8082"),

  // --- Device-bridge (host-side wifi/drives/QR API) ---
  // The device-bridge (services/oled-display/device-bridge.py) runs on the
  // host (systemd, port 9090) and serves the auto-mounted drive snapshot
  // (storage.ts) and the Wi-Fi/pairing QR (screen-qr.service.ts). Same
  // host-gateway rationale as the URLs above: the orchestrator is on the
  // bridge network, so `localhost`/`172.17.0.1` (docker0 — DOWN on the
  // single-box, whose gateway is 172.18.0.1) never reach the host bridge.
  // `host.docker.internal` resolves via the orchestrator's
  // `extra_hosts: host-gateway` mapping and IS reachable — but ONLY once the
  // bridge binds an interface the gateway can hit (BRIDGE_BIND=0.0.0.0 in
  // droplet-device-bridge.service; a 127.0.0.1 bind refuses the gateway
  // connection). This single key replaces the two divergent hardcoded
  // defaults storage.ts (BRIDGE_URL → 172.17.0.1) and screen-qr
  // (DEVICE_BRIDGE_URL) used to carry. `BRIDGE_URL` is honored as a
  // backward-compatible alias for any deployment that already set it.
  DEVICE_BRIDGE_URL: z.string().default("http://host.docker.internal:9090"),

  // --- Service-to-service auth (shared secret for routing/switch/discovery services) ---
  SERVICE_SECRET: z.string().default(""),

  // SERVICE_TOKEN_SWITCH — dedicated outbound bearer for switch.client.ts →
  // switch service, replacing the legacy shared SERVICE_SECRET on that path
  // (same per-service-token shape as SERVICE_TOKEN_DISPLAY / WARP-165: the
  // switch container's SERVICE_SECRET used to be wired to DEVICE_SECRET_KEY,
  // the FIPS-sealed master encryption key, which this keeps off the wire).
  // Compose wires both ends to ${SERVICE_TOKEN_SWITCH}; switch.client.ts
  // falls back to SERVICE_SECRET so installs that pinned the legacy shared
  // secret keep working until setup.sh re-mints.
  SERVICE_TOKEN_SWITCH: z.string().default(""),

  // SERVICE_TOKEN_AI_GATEWAY — WARP-560. Dedicated outbound bearer for
  // ai-gateway.client.ts → ai-gateway, which previously had NO inbound auth
  // (/ai/chat, /ai/sessions/*, /ai/keys/* were all reachable by anything that
  // could open the socket). The ai-gateway's ServiceAuthMiddleware now requires
  // this Bearer on every /ai/* route (except /ai/health). Compose wires both
  // ends to ${SERVICE_TOKEN_AI_GATEWAY}; ai-gateway.client.ts falls back to
  // SERVICE_SECRET so installs whose .env predates this token keep working
  // until setup.sh re-mints. Empty = unauthenticated (dev/CI default).
  SERVICE_TOKEN_AI_GATEWAY: z.string().default(""),

  // --- Service-principal bearer tokens (inbound) ---
  // Per shared_brain `agentic-workflows.md` + `LLM_AGENT.md`: services that
  // need LLM + MCP tool dispatch MUST call the orchestrator's `/api/llm/chat`
  // route, not ai-gateway directly. The orchestrator is the only thing that
  // owns the agent loop + tool routing.
  //
  // SERVICE_TOKEN_VOICE — recognised by authMiddleware for the
  // voice-io / voice-assistant service. When the incoming Bearer matches,
  // the request is treated as a `service` role principal (see jwt.service.ts
  // Role union). Empty default means "no service token configured" — voice
  // calls will 401 until an operator sets it (matches the safe default for
  // SERVICE_SECRET above).
  //
  // To rotate: change the value here AND in voice-io's compose env in
  // lockstep. Both must agree or voice → orchestrator handshake fails.
  SERVICE_TOKEN_VOICE: z.string().default(""),

  // SERVICE_TOKEN_MCP — WARP-339. Same shape as SERVICE_TOKEN_VOICE,
  // for mcp-server's outbound calls back to the orchestrator's REST
  // surface (matter, audit-log, safety-tier). The mcp-server runs as
  // a sibling container and its `createHttpClient("orchestrator")`
  // attaches this value as a Bearer on every request.
  //
  // The dual-token shape (one per service consumer) rather than a
  // shared "internal" token gives us per-service rotation and a
  // clean audit trail (matchServiceToken sets distinct AuthUser
  // principals — `_service:voice` vs `_service:mcp` — so request
  // logs attribute correctly even when both speak at the same time).
  //
  // To rotate: change the value here AND in mcp-server's compose
  // env (ORCHESTRATOR_TOKEN) in lockstep.
  SERVICE_TOKEN_MCP: z.string().default(""),

  // SERVICE_TOKEN_EMAIL — WARP-465. Bearer the email-indexer service
  // presents on POST /api/email/_ingest/* and PATCH
  // /api/email/_ingest/drafts/:id. authMiddleware's matchServiceToken
  // sets `_service:email`. To rotate: change here AND in the
  // email-indexer's compose env (ORCHESTRATOR_SERVICE_TOKEN).
  SERVICE_TOKEN_EMAIL: z.string().default(""),

  // ORCHESTRATOR_SAMPLER_TOKEN — WARP-468 / WARP-470. Bearer presented
  // by the routing service's egress_meter (off-LAN sample POST) and
  // scheduler (throughput sample POST). Both run with network_mode: host
  // so they reach the orchestrator on localhost:3000 rather than via
  // compose service DNS. authMiddleware's matchServiceToken sets
  // `_service:sampler` for either source. To rotate: change here AND in
  // services/routing's compose env (ORCHESTRATOR_SAMPLER_TOKEN).
  ORCHESTRATOR_SAMPLER_TOKEN: z.string().default(""),

  // AI_GATEWAY_SAMPLER_TOKEN — WARP-468. Bearer presented by ai-gateway's
  // off_lan_gating middleware on GET /api/network/off-lan and
  // /api/settings/off-lan to read the cloud_model_escape posture. The
  // gate fails closed (451) without a valid reading, so a missing or
  // mis-registered token blocks every cloud-model call. authMiddleware's
  // matchServiceToken sets `_service:ai-gateway`. To rotate: change here
  // AND in services/ai-gateway's compose env (AI_GATEWAY_SAMPLER_TOKEN).
  AI_GATEWAY_SAMPLER_TOKEN: z.string().default(""),

  // --- Web Push (VAPID) ---
  // Pin these in .env after the first orchestrator boot — the push
  // service will generate ephemeral keys and log them on first run if
  // absent, but every restart with absent vars rotates the keys and
  // breaks every existing browser subscription. Generated via
  // `npx web-push generate-vapid-keys` if you want them ahead of time.
  VAPID_PUBLIC_KEY: z.string().default(""),
  VAPID_PRIVATE_KEY: z.string().default(""),
  // Contact mailto for VAPID's `aud` claim. Some push services (FCM,
  // Mozilla autopush) reject pushes without a valid contact.
  VAPID_CONTACT_EMAIL: z.string().default(""),

  // --- WARP-279: Claude-activity meta-observability dashboard ---
  // GitHub adapter — optional PAT. Repo defaults to the public droplet repo
  // and is documented under GITHUB_REPO_OWNER / GITHUB_REPO_NAME in
  // .env.example. We deliberately don't list those here: they're only read
  // by the GitHub adapter and never re-emitted as part of `config`.
  GITHUB_TOKEN: z.string().default(""),

  // Jira adapter — basic auth (email + API token) against an Atlassian
  // Cloud instance. All three are required for Jira data to populate; with
  // any one missing, the dashboard's "WARP-228 chain progress" and
  // "in-flight tickets" panels degrade to empty (with a banner), the rest
  // of the dashboard works normally. The host is the bare cloud subdomain
  // (e.g. `warp-lab.atlassian.net`, no scheme).
  JIRA_HOST: z.string().default(""),
  JIRA_EMAIL: z.string().default(""),
  JIRA_API_TOKEN: z.string().default(""),
});

// Backward-compat: storage.ts historically read `BRIDGE_URL`; screen-qr read
// `DEVICE_BRIDGE_URL`. We standardize on `DEVICE_BRIDGE_URL` (config key
// above) but honor a legacy `BRIDGE_URL` when the canonical key is unset, so
// an existing deployment that set `BRIDGE_URL` in .env isn't silently
// repointed at the default.
// Treat an empty/whitespace value as unset so a templated `.env` with a bare
// `DEVICE_BRIDGE_URL=` (or `BRIDGE_URL=`) line falls through to the alias and
// then the schema default, rather than parsing as an empty URL.
const firstNonEmpty = (...vals: (string | undefined)[]): string | undefined =>
  vals.find((v) => v !== undefined && v.trim() !== "");
const envForParse: NodeJS.ProcessEnv = {
  ...process.env,
  DEVICE_BRIDGE_URL: firstNonEmpty(
    process.env.DEVICE_BRIDGE_URL,
    process.env.BRIDGE_URL,
  ),
};

const parsed = envSchema.parse(envForParse);

// --- WARP-562: resolve the CORS origin allowlist ---
// Comma-separated → trimmed, empties dropped. When the operator hasn't set
// CORS_ALLOWED_ORIGINS, fall back to the appliance's own LAN dashboard origin
// (covered by the TLS cert SANs) plus the dev dashboard origin outside prod.
function resolveCorsAllowedOrigins(
  raw: string,
  nodeEnv: string,
  publicFqdn: string,
): string[] {
  const explicit = raw
    .split(",")
    .map((o) => o.trim())
    .filter((o) => o.length > 0);

  const origins =
    explicit.length > 0
      ? explicit
      : [
          "https://droplet-ai.local",
          // Dev dashboard origin: the Next.js dev server runs on :3001
          // (`apps/web-dashboard/package.json` → `next dev -p 3001`). :3000 is
          // the orchestrator's own PORT, so it would grant nothing useful here.
          ...(nodeEnv !== "production" ? ["http://localhost:3001"] : []),
        ];

  // ADR-023 (C4): the publicly-trusted per-device FQDN is a first-class
  // browser origin — the dashboard is served on it at home AND over the
  // tunnel. Add it whether the operator set an explicit allowlist or fell
  // through to the defaults, deduped, so credentialed CORS never rejects the
  // canonical address. Empty until first HQ contact.
  const fqdn = publicFqdn.trim();
  if (fqdn) {
    const fqdnOrigin = `https://${fqdn}`;
    if (!origins.includes(fqdnOrigin)) origins.push(fqdnOrigin);
  }

  // Fail-fast on wildcard + credentials, mirroring ai-gateway's guard
  // (services/ai-gateway/main.py:125-129). `credentials: true` is always on
  // for the orchestrator, so a `*` allowlist is never acceptable: the browser
  // would receive `Access-Control-Allow-Origin: *` with credentials, or — with
  // the `cors` package — silently reflect every origin. Die loud instead.
  if (origins.includes("*")) {
    throw new Error(
      "CORS_ALLOWED_ORIGINS contains a wildcard ('*'), which is not allowed " +
        "with credentialed CORS. Set an explicit, comma-separated origin list " +
        "(e.g. https://droplet-ai.local).",
    );
  }

  return origins;
}

export const config = {
  ...parsed,
  // WARP-580 — `AUTH_ENABLED` on the exported config is the EFFECTIVE,
  // fail-closed posture (resolved from the literal env string). Production
  // always resolves to true; non-production honours an explicit opt-out only.
  AUTH_ENABLED: resolveAuthEnabled(process.env.AUTH_ENABLED, parsed.NODE_ENV),
  corsAllowedOrigins: resolveCorsAllowedOrigins(
    parsed.CORS_ALLOWED_ORIGINS,
    parsed.NODE_ENV,
    parsed.DROPLET_PUBLIC_FQDN,
  ),
};
export type Config = typeof config;
