import * as path from "node:path";
import { z } from "zod";

const defaultMatterStorage =
  process.env.NODE_ENV === "production"
    ? "/data/matter-storage"
    : path.resolve(".data/matter-storage");

const envSchema = z.object({
  DATABASE_URL: z.string().default("postgresql://droplet:droplet@localhost:5432/droplet"),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  MQTT_BROKER: z.string().default("mqtt://localhost:1883"),
  AI_GATEWAY_URL: z.string().default("http://localhost:8000"),
  PORT: z.coerce.number().default(3000),
  NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  MAX_UPLOAD_SIZE_MB: z.coerce.number().default(100),

  // --- Nextcloud (single file storage backend) ---
  NEXTCLOUD_URL: z.string().default("http://localhost:8080"),
  AUTH_ENABLED: z.coerce.boolean().default(false),

  // --- Device pairing ---
  // 32-byte base64 key used to encrypt per-device Nextcloud app passwords
  // at rest. Generated by scripts/setup.sh alongside other secrets. Empty
  // default lets tests run without setting the env var; production fails
  // closed via encryption.service.ts when the key is missing.
  DEVICE_SECRET_KEY: z.string().default(""),

  // --- Home Assistant (optional fallback for non-Matter integrations) ---
  HOMEASSISTANT_URL: z.string().default("http://localhost:8123"),
  HOMEASSISTANT_TOKEN: z.string().default(""),

  // --- Matter (native controller) ---
  MATTER_STORAGE_PATH: z.string().default(defaultMatterStorage),
  MATTER_CONTROLLER_NAME: z.string().default("Droplet"),

  // --- OAuth2 ---
  AUTH_MODE: z.enum(["oauth2", "legacy"]).default("legacy"),
  OAUTH2_CLIENT_ID: z.string().default(""),
  OAUTH2_CLIENT_SECRET: z.string().default(""),

  // --- gRPC ---
  AI_GATEWAY_GRPC_URL: z.string().default("localhost:50051"),

  // --- OpenWrt Routing ---
  ROUTING_SERVICE_URL: z.string().default("http://localhost:8080"),

  // --- Frigate NVR ---
  FRIGATE_URL: z.string().default("http://localhost:5000"),
  CAMERA_DISCOVERY_URL: z.string().default("http://localhost:8085"),
});

export const config = envSchema.parse(process.env);
export type Config = z.infer<typeof envSchema>;
