import * as path from "node:path";
import { z } from "zod";

const defaultMatterStorage =
  process.env.NODE_ENV === "production"
    ? "/data/matter-storage"
    : path.resolve(".data/matter-storage");

const envSchema = z.object({
  DATABASE_URL: z.string().default("postgresql://droplet:droplet@localhost:5432/droplet"),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  MQTT_BROKER: z.string().default("mqtt://localhost:1883"),
  AI_GATEWAY_URL: z.string().default("http://localhost:8000"),
  PORT: z.coerce.number().default(3000),
  NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  MAX_UPLOAD_SIZE_MB: z.coerce.number().default(100),

  // --- Nextcloud (single file storage backend) ---
  NEXTCLOUD_URL: z.string().default("http://localhost:8080"),
  AUTH_ENABLED: z.coerce.boolean().default(false),

  // --- Device pairing ---
  // 32-byte base64 key used to encrypt per-device Nextcloud app passwords
  // at rest. Generated by scripts/setup.sh alongside other secrets. Empty
  // default lets tests run without setting the env var; production fails
  // closed via encryption.service.ts when the key is missing.
  DEVICE_SECRET_KEY: z.string().default(""),

  // --- Matter (native controller) ---
  //
  // DO NOT ADD NEW `MATTER_*` ENV VARS HERE.
  //
  // matter.js scans the entire process.env for `MATTER_*` at startup
  // (NodeJsEnvironment.js → vars.addUnixEnvStyle(process.env)) and folds
  // each one into its internal VariableService under a dot-namespaced
  // key. For example, `MATTER_CONTROLLER_NAME=Droplet` becomes the var
  // `controller.name`. When matter.js later activates an endpoint's
  // behavior whose id matches that namespace — e.g. the root node's
  // internal `controller` behavior — it merges those vars into the
  // behavior's defaults and casts them against the behavior's schema.
  // Any key the schema doesn't declare (like `name`) throws
  //   UnsupportedCastError: Property "name" is unsupported
  // and the whole controller init fails.
  //
  // Use a non-`MATTER_` prefix for anything we want to configure
  // ourselves. `MATTER_STORAGE_PATH` below predates this rule and
  // currently does not collide (no root-node behavior has id
  // `storage`), so leaving it in place to avoid churning existing
  // .env files — but prefer `DROPLET_MATTER_*` for new additions.
  MATTER_STORAGE_PATH: z.string().default(defaultMatterStorage),
  DROPLET_MATTER_CONTROLLER_NAME: z.string().default("Droplet"),

  // --- JWT ---
  // In production this must be set — setup.sh generates a 64-byte random hex value.
  // The default is intentionally weak so tests work without env setup.
  JWT_SECRET: z
    .string()
    .default("dev-jwt-secret-do-not-use-in-production")
    .refine(
      (s) => process.env.NODE_ENV !== "production" || s !== "dev-jwt-secret-do-not-use-in-production",
      "JWT_SECRET must be set to a strong random value in production",
    ),

  // --- OAuth2 ---
  AUTH_MODE: z.enum(["oauth2", "legacy"]).default("legacy"),
  OAUTH2_CLIENT_ID: z.string().default(""),
  OAUTH2_CLIENT_SECRET: z.string().default(""),

  // --- gRPC ---
  AI_GATEWAY_GRPC_URL: z.string().default("localhost:50051"),

  // --- OpenWrt Routing ---
  // Default uses `host.docker.internal` so the bridged orchestrator can
  // reach the routing service, which runs with `network_mode: host` (bound
  // to the Jetson host's :8080). `localhost` would be the orchestrator
  // container itself and never resolve to :8080. The orchestrator compose
  // service wires `host.docker.internal` via `extra_hosts: host-gateway`.
  ROUTING_SERVICE_URL: z.string().default("http://host.docker.internal:8080"),
  // Shared bearer token for routing service (generated by scripts/setup.sh).
  // Empty default lets tests and dev laptops run without setup; routing service
  // rejects empty tokens when its own value is set.
  ROUTING_SERVICE_TOKEN: z.string().default(""),
  // WARP-44: `real` (default) talks to the routing service normally.
  // `mock` is equivalent on the orchestrator side — routing itself is
  // configured to serve fixtures.
  // `disabled` short-circuits every openwrt.client call with
  // RouterError.disabled() so the dashboard renders a "Router supervision
  // disabled" banner instead of spamming retries at a non-existent service.
  ROUTING_MODE: z.enum(["real", "mock", "disabled"]).default("real"),

  // --- WireGuard / Remote Access ---
  // Hostname or IP that peer .conf files use as their `Endpoint`. Should be
  // reachable from outside the LAN — typically a DuckDNS subdomain (Phase 4)
  // or your home router's public IP. For inside-LAN testing you can set this
  // to the OpenWrt LAN IP (192.168.50.1). Empty default makes the orchestrator
  // refuse to mint peers with a clear error rather than handing out unusable
  // configs that point at "example.com" or similar.
  WIREGUARD_ENDPOINT_HOST: z.string().default(""),
  // VPN tunnel subnet. The server takes .1, peers get .2 through .254. Must
  // not collide with the LAN (192.168.50.0/24) or cameras (192.168.100.0/24).
  WIREGUARD_VPN_SUBNET: z.string().default("10.13.13.0/24"),
  WIREGUARD_LISTEN_PORT: z.coerce.number().default(51820),
  // CIDR + DNS server that the rendered peer .conf advertises to the client.
  // Defaults match the OpenWrt LAN. Override if the LAN is reconfigured.
  WIREGUARD_LAN_CIDR: z.string().default("192.168.50.0/24"),
  WIREGUARD_DNS: z.string().default("192.168.50.1"),

  // --- Coverage extender APs (WARP-446) ---
  // Per ADR-005. `DROPLET_AP_*` prefix is mandatory (see the long
  // MATTER_* warning above for why — same risk).
  //
  // DISCOVERY_INTERVAL — mDNS scan cadence in seconds. The orchestrator's
  //   discovery poller (cron-runtime.service.ts) queries
  //   `_droplet-ap._tcp.local` and upserts each new MAC into ApDevice.
  //   10s tracks new-AP-plugged-in within the 30s AC #1 budget.
  // APPROVAL_TIMEOUT — safe_apply timeout passed to the routing service
  //   on POST /aps/:mac/approve. 60s matches the rest of the codebase's
  //   confirmation-token TTL convention (WARP-41).
  // DAWN_ENABLED — master switch to disable dawn on every AP. Default on.
  //   Off only as a debugging escape hatch when an operator suspects
  //   dawn is the cause of an issue.
  // DEFAULT_TXPOWER — dBm cap on extender radios. Keeps household-floor
  //   cells small enough for clean roaming.
  DROPLET_AP_DISCOVERY_INTERVAL: z.coerce.number().default(10),
  DROPLET_AP_APPROVAL_TIMEOUT: z.coerce.number().default(60),
  DROPLET_AP_DAWN_ENABLED: z.coerce.boolean().default(true),
  DROPLET_AP_DEFAULT_TXPOWER: z.coerce.number().default(20),

  // --- Frigate NVR ---
  FRIGATE_URL: z.string().default("http://localhost:5000"),
  CAMERA_DISCOVERY_URL: z.string().default("http://localhost:8085"),

  // --- Managed Switch ---
  // Same rationale as ROUTING_SERVICE_URL above: switch runs with
  // `network_mode: host`, so the bridged orchestrator must reach it via
  // the host gateway.
  SWITCH_SERVICE_URL: z.string().default("http://host.docker.internal:8081"),

  // --- OLED / TFT Display ---
  // Same rationale again: the display service runs with `network_mode: host`
  // on the Jetson (uvicorn on :8082). `localhost` inside the orchestrator
  // container would never resolve to it, so default to the host gateway.
  DISPLAY_SERVICE_URL: z.string().default("http://host.docker.internal:8082"),

  // --- Service-to-service auth (shared secret for routing/switch/discovery services) ---
  SERVICE_SECRET: z.string().default(""),

  // --- Service-principal bearer tokens (inbound) ---
  // Per shared_brain `agentic-workflows.md` + `LLM_AGENT.md`: services that
  // need LLM + MCP tool dispatch MUST call the orchestrator's `/api/llm/chat`
  // route, not ai-gateway directly. The orchestrator is the only thing that
  // owns the agent loop + tool routing.
  //
  // SERVICE_TOKEN_VOICE — recognised by authMiddleware for the
  // voice-io / voice-assistant service. When the incoming Bearer matches,
  // the request is treated as a `service` role principal (see jwt.service.ts
  // Role union). Empty default means "no service token configured" — voice
  // calls will 401 until an operator sets it (matches the safe default for
  // SERVICE_SECRET above).
  //
  // To rotate: change the value here AND in voice-io's compose env in
  // lockstep. Both must agree or voice → orchestrator handshake fails.
  SERVICE_TOKEN_VOICE: z.string().default(""),

  // SERVICE_TOKEN_MCP — WARP-339. Same shape as SERVICE_TOKEN_VOICE,
  // for mcp-server's outbound calls back to the orchestrator's REST
  // surface (matter, audit-log, safety-tier). The mcp-server runs as
  // a sibling container and its `createHttpClient("orchestrator")`
  // attaches this value as a Bearer on every request.
  //
  // The dual-token shape (one per service consumer) rather than a
  // shared "internal" token gives us per-service rotation and a
  // clean audit trail (matchServiceToken sets distinct AuthUser
  // principals — `_service:voice` vs `_service:mcp` — so request
  // logs attribute correctly even when both speak at the same time).
  //
  // To rotate: change the value here AND in mcp-server's compose
  // env (ORCHESTRATOR_TOKEN) in lockstep.
  SERVICE_TOKEN_MCP: z.string().default(""),

  // SERVICE_TOKEN_EMAIL — WARP-465. Bearer the email-indexer service
  // presents on POST /api/email/_ingest/* and PATCH
  // /api/email/_ingest/drafts/:id. authMiddleware's matchServiceToken
  // sets `_service:email`. To rotate: change here AND in the
  // email-indexer's compose env (ORCHESTRATOR_SERVICE_TOKEN).
  SERVICE_TOKEN_EMAIL: z.string().default(""),

  // ORCHESTRATOR_SAMPLER_TOKEN — WARP-468 / WARP-470. Bearer presented
  // by the routing service's egress_meter (off-LAN sample POST) and
  // scheduler (throughput sample POST). Both run with network_mode: host
  // so they reach the orchestrator on localhost:3000 rather than via
  // compose service DNS. authMiddleware's matchServiceToken sets
  // `_service:sampler` for either source. To rotate: change here AND in
  // services/routing's compose env (ORCHESTRATOR_SAMPLER_TOKEN).
  ORCHESTRATOR_SAMPLER_TOKEN: z.string().default(""),

  // AI_GATEWAY_SAMPLER_TOKEN — WARP-468. Bearer presented by ai-gateway's
  // off_lan_gating middleware on GET /api/network/off-lan and
  // /api/settings/off-lan to read the cloud_model_escape posture. The
  // gate fails closed (451) without a valid reading, so a missing or
  // mis-registered token blocks every cloud-model call. authMiddleware's
  // matchServiceToken sets `_service:ai-gateway`. To rotate: change here
  // AND in services/ai-gateway's compose env (AI_GATEWAY_SAMPLER_TOKEN).
  AI_GATEWAY_SAMPLER_TOKEN: z.string().default(""),

  // --- Embedded Plane PM stack (ADR-010 / WARP-501) ---
  // Service principals reach Plane via the orchestrator — never
  // direct from the dashboard or external MCP. These three vars
  // identify and authenticate that channel:
  //
  //   DROPLET_PM_API_URL — Plane API base URL on the compose network
  //   (default `http://pm-api:8000`). Used by pm-rbac.service.ts +
  //   pm-onboard route + pm.client.ts for all outbound calls. Missing
  //   → URL constructor throws → fail-closed (per pm-rbac module
  //   contract).
  //
  //   DROPLET_PM_ADMIN_TOKEN — Plane admin API key. Sent as
  //   `X-API-Key` on every PATCH/POST. Rotation: change here AND in
  //   the PM compose env (pm-api service).
  //
  //   DROPLET_PM_WEB_URL — Public-facing Plane URL (used by the
  //   onboarding wizard's success card to deep-link the user to
  //   their newly-provisioned workspace).
  DROPLET_PM_API_URL: z.string().default(""),
  DROPLET_PM_ADMIN_TOKEN: z.string().default(""),
  DROPLET_PM_WEB_URL: z.string().default(""),

  // DROPLET_PM_WEBHOOK_SECRET — HMAC signing key for Plane webhooks
  // delivered to POST /api/pm/webhook (WARP-511). Empty default —
  // the webhook handler fail-CLOSEs (503) when this is unset, per
  // engineering-handbook 04-coding-standards/security-rules.md §1.
  DROPLET_PM_WEBHOOK_SECRET: z.string().default(""),

  // --- Web Push (VAPID) ---
  // Pin these in .env after the first orchestrator boot — the push
  // service will generate ephemeral keys and log them on first run if
  // absent, but every restart with absent vars rotates the keys and
  // breaks every existing browser subscription. Generated via
  // `npx web-push generate-vapid-keys` if you want them ahead of time.
  VAPID_PUBLIC_KEY: z.string().default(""),
  VAPID_PRIVATE_KEY: z.string().default(""),
  // Contact mailto for VAPID's `aud` claim. Some push services (FCM,
  // Mozilla autopush) reject pushes without a valid contact.
  VAPID_CONTACT_EMAIL: z.string().default(""),

  // --- WARP-279: Claude-activity meta-observability dashboard ---
  // GitHub adapter — optional PAT. Repo defaults to the public droplet repo
  // and is documented under GITHUB_REPO_OWNER / GITHUB_REPO_NAME in
  // .env.example. We deliberately don't list those here: they're only read
  // by the GitHub adapter and never re-emitted as part of `config`.
  GITHUB_TOKEN: z.string().default(""),

  // Jira adapter — basic auth (email + API token) against an Atlassian
  // Cloud instance. All three are required for Jira data to populate; with
  // any one missing, the dashboard's "WARP-228 chain progress" and
  // "in-flight tickets" panels degrade to empty (with a banner), the rest
  // of the dashboard works normally. The host is the bare cloud subdomain
  // (e.g. `warp-lab.atlassian.net`, no scheme).
  JIRA_HOST: z.string().default(""),
  JIRA_EMAIL: z.string().default(""),
  JIRA_API_TOKEN: z.string().default(""),
});

export const config = envSchema.parse(process.env);
export type Config = z.infer<typeof envSchema>;
